### PR TITLE
fix(login): move to main only when the chat is loaded

### LINKED ISSUE #17629: Fake loading screen is not working in 2.33 with new onboarding
I have updated my 2.32 installation with status community on it to latest 2.33 rc. While logging in, there is `Loading sections` empty screen, which was normally hidden under fake loading screen and its not the case anymore.

[app_20250320_103854.log](https://github.com/user-attachments/files/19361106/app_20250320_103854.log)

https://github.com/user-attachments/assets/e0acee88-8769-4ddf-9b31-3f5caadd7f9c

### PR DESCRIPTION
**Pull request by jrainville**
### What does the PR do

Fixes #17629

Only moves to the main screen when the chats are loaded to avoid showing the "loading sections" message. Also removes the loadingSection as it will never have a chance to be shown again. Removes the 3 second debounce when switching to main as the loading should be all finished by that point anyway

### Affected areas

Login and onboarding too technically, but there is nothing to load

### Architecture compliance

- [x] I am familiar with the application architecture and agreed good practices.
My PR is consistent with this document: [Status Desktop Architecture Guide](https://github.com/status-im/status-desktop/blob/master/CONTRIBUTING.md)

### Screenshot of functionality (including design for comparison)

This just shows that everything works as expected. It's slow because it's not on top of my speed up branch

[move-to-app-main.webm](https://github.com/user-attachments/assets/76a6484d-b3bc-4d85-be10-0140c579bdca)

### Impact on end user

Makes sure to never sow the !loading sections" section. With the speed up PR, it makes the login a little faster too since there is no debounce

### How to test

- login and make sure the last section works

### Risk 

Described potential risks and worst case scenarios.

Tick **one**:
- [x] Low risk: 2 devs MUST perform testing as specified above and attach their results as comments to this PR **before** merging.
- [ ] High risk: QA team MUST perform additional testing in the specified affected areas **before** merging.

Worst case the last section is no respected

### CODE REVIEW

File: src/app/modules/onboarding/module.nim [hunk 1]
```diff
@@ -76,7 +76,11 @@ method delete*[T](self: Module[T]) =
   self.controller.delete
 
 method onAppLoaded*[T](self: Module[T], keyUid: string) =
```
Comment (caybro) [inline src/app/modules/onboarding/module.nim:78]: What about the `keyUid` param, still needed?

**Review by caybro — APPROVED** [review]

File: src/app/modules/onboarding/module.nim (hunk 1 above)
Comment (jrainville) [reply src/app/modules/onboarding/module.nim:78]: I guess since I don't use it, we can remove it. It was actually never used in the current onboarding. I assume it's a leftover from the previous onboarding

Comment (caybro) [reply src/app/modules/onboarding/module.nim:78]: Yeah, it indeed seems unused; at one point we thought it'd be useful as a moment to save the credentials into the keychain right @igor-sirotin ?

**Review by alexjba — APPROVED** [review]
