### PR TITLE
fix(browser): fix opening downloads folder

### LINKED ISSUE #19248: [Browser] Open and Show in folder features on the Downloads tab don't work
# Bug Report

## Steps to reproduce

1. download a file via the Status browser
2. got to the Downloads tab
3. click on Open or Show in folder

#### Expected behavior
clicking on Open starts the selected file
clicking on Show in folder opens the folder where the selected file is located

#### Actual behavior
clicking on Open doesn't do anything
clicking on Open doesn't do anything

Image

### Additional Information

- Status desktop version: https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-251106-130605-b8ec1d-pr19225-x86_64.exe
- Operating System: Windows 11

### PR DESCRIPTION
**Pull request by friofry**
Fixes #19248

Fixed "Open" and "Show in folder" features not working for browser downloads on Windows.
`Qt.openUrlExternally()` expects a URL. It works good with `UrlUtils.urlFromUserInput()` on all platfroms
Previous implementation used manual string concatenation which didn't work on Windows.

### CODE REVIEW

File: src/app/global/utils.nim [hunk 1]
```diff
@@ -48,6 +48,9 @@ QtObject:
                     "file://" & absPath
     return uriPath
 
+  proc fromLocalFile*(self: Utils, filePath: string): string {.slot.} =
+    return url_fromLocalFile(filePath)
+
```
Comment (caybro) [inline src/app/global/utils.nim]: Drop this pls; we don't need it in NIM :)

File: ui/app/AppLayouts/Browser/stores/DownloadsStore.qml [hunk 2]
```diff
@@ -26,15 +27,17 @@ QtObject {
     }
 
     function openFile(index) {
-        Qt.openUrlExternally(`file://${downloadModel.downloads[index].downloadDirectory}/${downloadModel.downloads[index].downloadFileName}`)
+        const filePath = `${downloadModel.downloads[index].downloadDirectory}/${downloadModel.downloads[index].downloadFileName}`
+        Qt.openUrlExternally(Utils.fromLocalFile(filePath))
```
Comment (caybro) [inline ui/app/AppLayouts/Browser/stores/DownloadsStore.qml]:
```suggestion
        Qt.openUrlExternally(UrlUtils.convertUrlToLocalPath(filePath))
```

Comment (caybro) [reply ui/app/AppLayouts/Browser/stores/DownloadsStore.qml]: This one will work for mobile too

File: src/app/global/utils.nim (hunk 1 above)
Comment (friofry) [reply src/app/global/utils.nim]: Will drop this. I'm using this PR to create Windows builds, so it's a draft

File: ui/app/AppLayouts/Browser/stores/DownloadsStore.qml (hunk 2 above)
Comment (friofry) [reply ui/app/AppLayouts/Browser/stores/DownloadsStore.qml]: @caybro Thanks for the suggestion! But `convertUrlToLocalPath` doesn't work on mac (works on windows). It seems does the opposite (removes the `file://` prefix)
`Qt.openUrlExternally()` expects a URL. It works good with `UrlUtils.urlFromUserInput()` on all platfroms.

Comment (caybro) [reply ui/app/AppLayouts/Browser/stores/DownloadsStore.qml]: Ah OK...
