### PR TITLE
fix: Only `scrollToMessage` when it's available in the database

### LINKED ISSUE #11759: Fix hiding chat loading animation
# Bug Report

## Description

Calling `goToMessage` for an unknown (not yet loaded) message hangs the chat loading animation forever.

This was first reported in https://github.com/status-im/status-desktop/issues/11616. 
The AC root cause was fixed there, but the animation hide logic wasn't improved.

There's another case to reproduce this: click on a replied message that wasn't loaded yet. I'm sure there're more cases out there, so we need to improve the UI logic so this just never happens.

## Code to consider

https://github.com/status-im/status-desktop/blob/ea8d00f116b2dc2b69b59af6c8bcd91d50fde066/src/app/modules/main/chat_section/chat_content/messages/module.nim#L663-L673

https://github.com/status-im/status-desktop/blob/ea8d00f116b2dc2b69b59af6c8bcd91d50fde066/src/app/modules/main/chat_section/chat_content/messages/module.nim#L757-L764

## Steps to reproduce

There're several cases to reproduce this:
1. Clicking on an message AC notification
2. Clicking on a replied message

### PR DESCRIPTION
**Pull request by igor-sirotin**
Fixes #11759

### What does the PR do

1. `scrollToMessage` will not scroll if the message doesn't exist in the database
2. Now it's impossible to click on a deleted/unavailable message (even pointing hand cursor will not appear)
3. Moved reply clicking logic to `StatusMessageReply`
4. Made "message found" animation faster 
5. Renamed `fetchMessageByMessageId` to `getMessageByMessageId`, 
because by "fetch" we usually mean "fetch from waku", which doens't happen here. And the status-go method is "get" anyway.

I should say that I wasn't able to reproduce the bug actually.
But this should fix any potential problems.

### Screenshot of functionality (including design for comparison)

https://github.com/status-im/status-desktop/assets/25482501/a69c7bd9-07dd-4830-90be-ec49630ca1a9

### CODE REVIEW

File: src/app_service/service/message/service.nim [hunk 1]
```diff
@@ -563,10 +563,10 @@ QtObject:
     except Exception as e:
       error "error: ", procName="pinUnpinMessage", errName = e.name, errDesription = e.msg
 
-  proc fetchMessageByMessageId*(self: Service, chatId: string, messageId: string):
+  proc getMessageByMessageId*(self: Service, chatId: string, messageId: string):
```
Comment (osmaczko) [inline src/app_service/service/message/service.nim:566]: Since this interacts with status-go's database it should be called async. Have you tried to search and scroll to very old message? Is there UI freeze?

**Review by osmaczko — APPROVED** [review]
Nice and clean :+1:

File: ui/app/AppLayouts/Chat/views/MembersSelectorView.qml [hunk 2]
```diff
@@ -86,13 +86,6 @@ MembersSelectorBase {
         }
 
         function processContact(contactData) {
```
Comment (caybro) [inline ui/app/AppLayouts/Chat/views/MembersSelectorView.qml:88]: This looks like a different PR ;)

File: ui/StatusQ/src/StatusQ/Components/StatusMessage.qml [hunk 3]
```diff
@@ -133,14 +133,11 @@ Control {
...
 
-            PauseAnimation {
-                duration: 600
-            }
             NumberAnimation {
                 target: highlightRect
                 property: "opacity"
                 to: 1.0
-                duration: 1500
+                duration: 250
```
Comment (jrainville) [inline ui/StatusQ/src/StatusQ/Components/StatusMessage.qml:140]: Does that reflect the design?

**Review by jrainville — COMMENTED** [review]
Like Patryk said, this calls the DB, so it might freeze the app. Either we make it async or we find another way.

File: ui/StatusQ/src/StatusQ/Components/StatusMessage.qml (hunk 3 above)
Comment (igor-sirotin) [reply ui/StatusQ/src/StatusQ/Components/StatusMessage.qml:140]: I don't think we have designs for this. 
The old animation was driving me crazy during work on this PR 😄 

Probably we could ask designers to create strict animation rules for this, but such fast change is very easy to make ourselves.

@benjthayer, do you think this change make sense?

### The old animation is extremely slow:

https://github.com/status-im/status-desktop/assets/25482501/9c8b46fb-704e-47e0-8574-31acf5484169

### The new on is much closer to Discord:

https://github.com/status-im/status-desktop/assets/25482501/e87f42c5-e747-4ad4-8c36-06f0e92a79c6

### Discord:

https://github.com/status-im/status-desktop/assets/25482501/87624901-3513-4c78-b168-9e3ebeb0f08a

File: src/app_service/service/message/service.nim (hunk 1 above)
Comment (igor-sirotin) [reply src/app_service/service/message/service.nim:566]: Hmmm. I though getting a single by id a fast operation. 🤔 
Looks quite smooth to me, even scrolling to an old message.

https://github.com/status-im/status-desktop/assets/25482501/f6d2c97a-fd1d-40a1-a5ee-55009b744286

cc @jrainville @osmaczko

Comment (osmaczko) [reply src/app_service/service/message/service.nim:566]: > Hmmm. I though getting a single by id a fast operation. 🤔 Looks quite smooth to me, even scrolling to an old message.

Right. Even fast db operations should be done async due to db locking. Long story short, the fast db operation can end up waiting in a queue of db requests, effectively blocking our UI thread. It all depends on how busy the db is at the time of the request.

File: ui/StatusQ/src/StatusQ/Components/StatusMessage.qml (hunk 3 above)
Comment (jrainville) [reply ui/StatusQ/src/StatusQ/Components/StatusMessage.qml:140]: Ok yeah I agree, the old one was very slow. I don't mind keeping the new one. Designers can create a ticket for the value they want (Ben is on vacation I think)

File: src/app_service/service/message/service.nim (hunk 1 above)
Comment (igor-sirotin) [reply src/app_service/service/message/service.nim]: Added `asyncGetMessageById` 👌

File: src/app_service/service/message/dto/call_reason.nim [hunk 4]
```diff
@@ -0,0 +1,4 @@
+type
+  GetMessageByIdCallReason* {.pure.} = enum
+    Unknown
+    ScrollTomessage
```
Comment (jrainville) [inline src/app_service/service/message/dto/call_reason.nim:4]:
```suggestion
    ScrollToMessage
```

**Review by jrainville — APPROVED** [review]

File: src/app/modules/main/chat_section/chat_content/messages/module.nim [hunk 5]
```diff
@@ -661,13 +662,21 @@ proc switchToMessage*(self: Module, messageId: string) =
...
 method scrollToMessage*(self: Module, messageId: string) =
-  if(messageId == ""):
+  if messageId == "":
     return
 
-  if(self.view.getMessageSearchOngoing()):
+  if self.view.getMessageSearchOngoing():
     return
 
+  self.controller.asyncGetMessageById(messageId, GetMessageByIdCallReason.ScrollTomessage)
```
Comment (osmaczko) [inline src/app/modules/main/chat_section/chat_content/messages/module.nim:671]: I believe more practical way of doing this would be to use a `requestID`, rather than `callReason`. There are many message modules which may trigger `asyncGetMessageById` with `ScrollTomessage` reason at the same time. If that's the case, then it would break the loading animation in some modules.

```suggestion
  self.getMessageRequestID = self.controller.asyncGetMessageById(messageId)
```

This ID could be a UUID generated by service at the time of the call, and then propagated with the response.

Comment (igor-sirotin) [reply src/app/modules/main/chat_section/chat_content/messages/module.nim:671]: hmm, good idea!

**Comment by igor-sirotin** [comment]
@osmaczko Implemented the `requestId` idea, please check it our 🙂

**Review by jrainville — APPROVED** [review]

File: src/app/modules/main/chat_section/chat_content/messages/module.nim [hunk 6]
```diff
@@ -41,6 +41,7 @@ type
     moduleLoaded: bool
     initialMessagesLoaded: bool
     firstUnseenMessageState: FirstUnseenMessageState
+    scrollToMessageRequests: Table[UUID, string]
```
Comment (osmaczko) [inline src/app/modules/main/chat_section/chat_content/messages/module.nim:44]: Not sure why do we store the table here instead of just one UUID? Message module shouldn't have more than one request ongoing:
```
  if self.view.getMessageSearchOngoing():
    return
```

File: src/app_service/service/message/service.nim [hunk 7]
```diff
@@ -563,19 +569,56 @@ QtObject:
...
+        signalData.error = "message doesn't exist"
+
+      self.events.emit(SIGNAL_GET_MESSAGE_FINISHED, signalData)
+
+    except Exception as e:
+      error "response processing failed", procName="asyncGetMessageByMessageId", errName = e.name, errDesription = e.msg
+      self.events.emit(SIGNAL_GET_MESSAGE_FINISHED, GetMessageResult( error: e.msg ))
+
+  proc asyncGetMessageById*(self: Service, messageId: string): UUID =
+    let requestId = genUUID()
```
Comment (osmaczko) [inline src/app_service/service/message/service.nim:612]: :+1:

**Review by osmaczko — APPROVED** [review]
Cool, thank you :pray: One small concern in the comments.

File: src/app/modules/main/chat_section/chat_content/messages/module.nim (hunk 6 above)
Comment (igor-sirotin) [reply src/app/modules/main/chat_section/chat_content/messages/module.nim:44]: Indeed, missed that

Comment (igor-sirotin) [reply src/app/modules/main/chat_section/chat_content/messages/module.nim]: done 👍

**Review by caybro — APPROVED** [review]
LGTM

File: ui/StatusQ/src/StatusQ/Components/StatusMessage.qml (hunk 3 above)
Comment (benjthayer) [reply ui/StatusQ/src/StatusQ/Components/StatusMessage.qml:140]: > I don't think we have designs for this. The old animation was driving me crazy during work on this PR 😄
> 
> Probably we could ask designers to create strict animation rules for this, but such fast change is very easy to make ourselves.
> 
> @benjthayer, do you think this change make sense?
> 
> ### The old animation is extremely slow:
>  Screen.Recording.2023-08-04.at.12.08.35.mov 
> ### The new on is much closer to Discord:
>  Screen.Recording.2023-08-04.at.12.13.08.mov 
> ### Discord:
>  Screen.Recording.2023-08-04.at.12.09.40.mov

Looks great to me thanks @igor-sirotin , nice enhancement 👌 . We can always tweak further / define values if needed  once we've had a chance to test. Thanks
