### PR TITLE
fix(backup): set backup path to empty string by default on Android and update backup popup

### LINKED ISSUE #19377: [Mobile] Backup now doesn't work with the default directory on Android
# Bug Report

## Steps to reproduce

1. install Status app on you mobile device
2. go to Settings >> On-device backup
3. click on Backup now

#### Expected behavior
Backup is created/updated successfully

#### Actual behavior
Backup fails. Once the user changes the default directory to some of the accessible directory on their phone, Backup is created/updated successfully.

Image

### Additional Information

Status mobile version: https://github.com/status-im/status-desktop/pull/19306
Operating System: Android 15

### PR DESCRIPTION
**Pull request by jrainville**
### What does the PR do

Fixes #19377

Sets the backup path to empty string on Android to let users know that they need to set it. Modifies the "Enable message backup" popup to enable backups in general on Android.

### Affected areas

- enable backup popup
- status-go (PR: https://github.com/status-im/status-go/pull/7146)
- backup setting

### Architecture compliance

- [x] I am familiar with the [application architecture](/docs/architecture.md) and agreed good practices.
My PR is consistent with this document: [QML Architecture Guidelines](/guidelines/QML_ARCHITECTURE_GUIDE.md)

### Screencapture of the functionality

Video showing the "new" popup plus it working. The error shown when clicking the Backup Now button is normal because no path is selected.

[andrdoid-new-user-2.webm](https://github.com/user-attachments/assets/c4d210e8-3a15-4167-88c4-2fc36649dc51)

### Impact on end user

Makes it clear that users need to set a backup path for it to work on Android. Also prevents the error toast showing when it is not set

### How to test

- Create a new Android profile
- Go to Chat two times to see the popup
- Go to Backup settings

### Risk 

Low

### CODE REVIEW

File: src/app/global/local_account_sensitive_settings.nim [hunk 1]
```diff
@@ -595,6 +595,9 @@ QtObject:
   proc getLocalBackupChosenPath*(self: LocalAccountSensitiveSettings): string {.slot.} =
     let setting = self.getLocalBackupChosenPathSetting()
     if setting == "":
+      when defined(android):
```
Comment (caybro) [inline src/app/global/local_account_sensitive_settings.nim:598]: What about iOS? 🤔

**Review by caybro — COMMENTED** [review]
LGTM in general, just wondering what about iOS

File: src/app/global/local_account_sensitive_settings.nim (hunk 1 above)
Comment (jrainville) [reply src/app/global/local_account_sensitive_settings.nim:598]: Apparently iOS is fine according to Volo. I think users can access the sandbox in iOS
