### PR TITLE
fix(@chat): display link urls

### LINKED ISSUE #4514: [base_bc] GIFs and links are not being displayed when sent in a chat
# Bug Report

## Description

1. open 1x1 chat
2. send a link
3. send a GIF

#### Expected behavior : 

1. link is shown , resolving the link depends on settings
2. GIF is shown, resolving a GIF depends on settings

#### Actual behavior : 

image

### Additional Information

base_bc branch, commit b2a0ba9892023859e9e40d2186ffbbb20b1dfab4

### PR DESCRIPTION
**Pull request by alaibe**
https://github.com/status-im/status-lib/pull/171

fixes #4514

image

### CODE REVIEW

File: src/app_service/service/message/async_tasks.nim [hunk 1]
```diff
@@ -1,6 +1,9 @@
 include ../../common/json_utils
 include ../../../app/core/tasks/common
 
+import status/statusgo_backend_new/chat as status_go_chat
```
Comment (jrainville) [inline src/app_service/service/message/async_tasks.nim:4]: You cna technically import that in `message/service` instead since `async_taks` is `include`d

File: ui/imports/shared/views/chat/LinksMessageView.qml [hunk 2]
```diff
@@ -226,7 +220,7 @@ Column {
     Component {
         id: invitationBubble
         InvitationBubbleView {
-            store: root.store
+            // store: root.store
```
Comment (jrainville) [inline ui/imports/shared/views/chat/LinksMessageView.qml:223]: Can we get rid of this?

**Review by jrainville — APPROVED** [review]
Nice job

File: ui/imports/shared/views/chat/LinksMessageView.qml (hunk 2 above)
Comment (alaibe) [reply ui/imports/shared/views/chat/LinksMessageView.qml:223]: I didn t really refactor that one and it needs a store. I don't know :)

File: src/app_service/service/message/async_tasks.nim (hunk 1 above)
Comment (alaibe) [reply src/app_service/service/message/async_tasks.nim:4]: Isn't it better to have import as close as possible to usage?

Comment (jrainville) [reply src/app_service/service/message/async_tasks.nim:4]: Maybe. The `async_task` files have been made like I said so I just followed like a good sheep

File: ui/imports/shared/views/chat/LinksMessageView.qml [hunk 3]
```diff
@@ -66,42 +66,37 @@ Column {
...
+           Connections {
+               id: linkFetchConnections
+               enabled: false
+               target: root.messageStore.messageModule
+               onLinkPreviewDataWasReceived: {
+                   let response
+                   try {
+                        response = JSON.parse(previewData)
+                   } catch (e) {
+                       console.error(previewData, e)
```
Comment (Khushboo-dev-cpp) [inline ui/imports/shared/views/chat/LinksMessageView.qml:78]: left behind by mistake?

File: ui/imports/shared/views/chat/LinksMessageView.qml [hunk 4]
```diff
@@ -66,42 +66,37 @@ Column {
...
+                       return
+                   }
+                   if (response.uuid !== linkMessageLoader.uuid) return
+                   linkFetchConnections.enabled = false
+
+                   if (!response.success) {
+                       console.error("could not get preview data")
```
Comment (Khushboo-dev-cpp) [inline ui/imports/shared/views/chat/LinksMessageView.qml:85]: this as well

**Review by Khushboo-dev-cpp — APPROVED** [review]
Hey. Just need to remove leftover code. Approving in the mean time :)

**Comment by abhi-status** [comment]
Testing blocked by --> https://github.com/status-im/status-desktop/issues/4600

**Review by iurimatias — APPROVED** [review]
tested, will rebase status-lib and merge
