### PR TITLE
fix(@dektop/chat): Fix messages timestamp update

### LINKED ISSUE #6543: Contact request message and very next message are separated with [Today] timestamp
### Description

1. create user one
2. create user two (separate instance)
3. as user one, send a message in public chat
4. as user two, click the message and send contact request
5. as user one, accept the contact request
6. as user one, send a message to 1x1 chat with user two
7. as user two, open 1x1 chat with user one

As result, the contact request message and newly received message are divided with [Today] timestamp

Screenshot 2022-07-20 at 10 41 04

### PR DESCRIPTION
**Pull request by MishkaRogachev**
Close #6543

### What does the PR do

Fixes in message model to get update on next and previous messages

### Affected areas

Chat

### Screenshot of functionality (including design for comparison)

Screenshot 2022-08-02 at 14 38 00

### CODE REVIEW

**Review by caybro — APPROVED** [review]
LGTM

File: src/app/modules/shared_models/message_model.nim [hunk 1]
```diff
@@ -309,9 +330,15 @@ QtObject:
     self.beginRemoveRows(parentModelIndex, ind, ind)
     self.items.delete(ind)
     self.endRemoveRows()
-    
-    if self.items.len > 0 and ind > 0 and ind < self.items.len:
-        self.updateItemAtIndex(ind - 1)
+
+   # if self.items.len > 0 and ind > 0 and ind < self.items.len:
+   #     self.updateItemAtIndex(ind - 1)
```
Comment (jrainville) [inline src/app/modules/shared_models/message_model.nim:335]: leftover?

**Review by jrainville — COMMENTED** [review]
Looks good, you just have a small leftover

**Review by jrainville — APPROVED** [review]

File: ui/imports/shared/views/chat/CompactMessageView.qml [hunk 2]
```diff
@@ -51,6 +51,10 @@ Item {
 
     property string message: ""
 
+    property int prevMessageIndex
+    property string prevMsgTimestamp
```
Comment (caybro) [inline ui/imports/shared/views/chat/CompactMessageView.qml:55]: `ModelRole.PrevMsgTimestamp.int: "prevMsgTimestamp"`

some type discrepancy? :)

**Review by caybro — CHANGES_REQUESTED** [review]
Just pass `int`s around

Otherwise looks good

File: ui/imports/shared/views/chat/CompactMessageView.qml (hunk 2 above)
Comment (MishkaRogachev) [reply ui/imports/shared/views/chat/CompactMessageView.qml:55]: `ModelRole.PrevMsgTimestamp.int` is just a model role enum mapping, the actual value exposed to qml using QVariant

Comment (caybro) [reply ui/imports/shared/views/chat/CompactMessageView.qml:55]: Correct but by assigning it to a `string` property you make it a string, not a number

Comment (caybro) [reply ui/imports/shared/views/chat/CompactMessageView.qml:55]: My point is, when you later want to format or display such timestamp in QML, you'd use sth like `new Date(prevMsgTimestamp).toLocaleString()` but that wouldn'T work as `Date` takes an `int` not a `string`

Comment (MishkaRogachev) [reply ui/imports/shared/views/chat/CompactMessageView.qml:55]: Timestamps exposed to QML as QVariant, not int. Using string type for timestamp in QML is also strange for me. But if you want me to replace it here, imho i also should replace timestamps in the whole chat. @saledjenic @jrainville you were working on messaging part, what is yours opinion?

Comment (jrainville) [reply ui/imports/shared/views/chat/CompactMessageView.qml:55]: It does make sense for the timestamp to be an int. I don't remember why it was put as a string at first, but I assume it was a mistake or just a misunderstanding.

Comment (caybro) [reply ui/imports/shared/views/chat/CompactMessageView.qml:55]: > Timestamps exposed to QML as QVariant, not int. Using string type for timestamp in QML is also strange for me. But if you want me to replace it here, imho i also should replace timestamps in the whole chat. @saledjenic @jrainville you were working on messaging part, what is yours opinion?

Well of course it's a `QVariant` but inside it holds an `int` not a `string`

Comment (saledjenic) [reply ui/imports/shared/views/chat/CompactMessageView.qml:55]: @MishkaRogachev if we're talking about `prevMsgTimestamp` it's coming from [here](https://github.com/status-im/status-desktop/blob/master/src/app/modules/shared_models/message_item.nim#L249-L278) and that's why it's string, cause entire object is passed as string to qml and parsed there.

Comment (MishkaRogachev) [reply ui/imports/shared/views/chat/CompactMessageView.qml:55]: So for now i would prefer to use string and if we want to change it would be much better to create new issue for that

Comment (caybro) [reply ui/imports/shared/views/chat/CompactMessageView.qml:55]: OK

**Review by caybro — APPROVED** [review]

**Review by anastasiyaig — APPROVED** [review]
