### PR TITLE
fix(community_tokens/service): fix crash when receiving bad event

### LINKED ISSUE #11176: Windows - App keeps crashing after logging in
App keeps crashing a couple of minutes after loggin in. The account that is logged in was used to mint tokens before the crash started occuring.

I've checked the same account on macos and it works fine there.

### Additional Information
**Error showing up after login:**
error
**Logs:**
[app_20230620_125404.log](https://github.com/status-im/status-desktop/files/11799412/app_20230620_125404.log)

- Status desktop version: v0.13.0-rc.2
- Operating System: Windows 11 22H2

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #11176

This fixes the crash experienced after minting. It doesn't fix the root cause. It seems like the event didn't have any data, but I couldn't reproduce the bug.

I'm still positive that this should resolve the crash though. I also added better logging if it happens again, so we'll be able to find the origin.

### CODE REVIEW

**Comment by jrainville** [comment]
@lukaszso if you can, test the Windows build with the same account. It shouldn't crash anymore and it will have logs will help debug (for a further issue).
The log will say `Error processing Collectible deployment pending transaction event`

**Comment by alexjba** [comment]
Couldn't find specific repro steps, but it looks much more stable on this branch. Still, I could reproduce twice (as opposed to every login on master) with the following stack trace:
```
DBG 2023-06-21 11:42:23.549+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=3513325 file=core.nim:27 rpc_method=wakuext_getCommunityTokens
DBG 2023-06-21 11:42:23.573+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=3513325 file=core.nim:27 rpc_method=collectibles_contractOwner
Warning: QObject::disconnect: No such signal QObject::dataChanged(QModelIndex,QModelIndex,QVector<int>) (:0, )
Warning: QObject::disconnect: No such signal QObject::headerDataChanged(Qt::Orientation,int,int) (:0, )
Warning: QObject::disconnect: No such signal QObject::rowsAboutToBeInserted(QModelIndex,int,int) (:0, )
Warning: QObject::disconnect: No such signal QObject::rowsInserted(QModelIndex,int,int) (:0, )
Warning: QObject::disconnect: No such signal QObject::columnsAboutToBeInserted(QModelIndex,int,int) (:0, )
Warning: QObject::disconnect: No such signal QObject::columnsInserted(QModelIndex,int,int) (:0, )
Warning: QObject::disconnect: No such signal QObject::rowsAboutToBeRemoved(QModelIndex,int,int) (:0, )
Warning: QObject::disconnect: No such signal QObject::rowsRemoved(QModelIndex,int,int) (:0, )
Warning: QObject::disconnect: No such signal QObject::columnsAboutToBeRemoved(QModelIndex,int,int) (:0, )
Warning: QObject::disconnect: No such signal QObject::columnsRemoved(QModelIndex,int,int) (:0, )
Warning: QObject::disconnect: No such signal QObject::rowsAboutToBeMoved(QModelIndex,int,int,QModelIndex,int) (:0, )
Warning: QObject::disconnect: No such signal QObject::rowsMoved(QModelIndex,int,int,QModelIndex,int) (:0, )
Warning: QObject::disconnect: No such signal QObject::columnsAboutToBeMoved(QModelIndex,int,int,QModelIndex,int) (:0, )
Warning: QObject::disconnect: No such signal QObject::columnsMoved(QModelIndex,int,int,QModelIndex,int) (:0, )
Warning: QObject::disconnect: No such signal QObject::layoutAboutToBeChanged(QList<QPersistentModelIndex>,QAbstractItemModel::LayoutChangeHint) (:0, )
Warning: QObject::disconnect: No such signal QObject::layoutChanged(QList<QPersistentModelIndex>,QAbstractItemModel::LayoutChangeHint) (:0, )
Warning: QObject::disconnect: No such signal QObject::modelAboutToBeReset() (:0, )
Warning: QObject::disconnect: No such signal QObject::modelReset() (:0, )
Traceback (most recent call last)
/Users/alexjbanca/Repos/status-desktop/src/nim_status_client.nim(193) nim_status_client
/Users/alexjbanca/Repos/status-desktop/src/nim_status_client.nim(190) mainProc
/Users/alexjbanca/Repos/status-desktop/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec
/Users/alexjbanca/Repos/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/alexjbanca/Repos/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/alexjbanca/Repos/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(558) onSlotCalled
/Users/alexjbanca/Repos/status-desktop/src/app/core/signals/signals_manager.nim(70) receiveSignal
/Users/alexjbanca/Repos/status-desktop/src/app/core/signals/signals_manager.nim(67) processSignal
/Users/alexjbanca/Repos/status-desktop/src/app/core/eventemitter.nim(58) emit
/Users/alexjbanca/Repos/status-desktop/src/app_service/service/community/service.nim(260) :anonymous
/Users/alexjbanca/Repos/status-desktop/src/app_service/service/community/service.nim(610) handleCommunityUpdates
/Users/alexjbanca/Repos/status-desktop/src/app/core/eventemitter.nim(58) emit
/Users/alexjbanca/Repos/status-desktop/src/app/modules/main/controller.nim(259) :anonymous
/Users/alexjbanca/Repos/status-desktop/src/app/modules/main/io_interface.nim(161) communityEdited
/Users/alexjbanca/Repos/status-desktop/src/app/modules/main/module.nim(923) communityEdited
/Users/alexjbanca/Repos/status-desktop/src/app/modules/main/view.nim(65) editItem
/Users/alexjbanca/Repos/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(556) activeSectionChanged
/Users/alexjbanca/Repos/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(32) emit
/Users/alexjbanca/Repos/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(46) qobjectCallback
/Users/alexjbanca/Repos/status-desktop/vendor/nimqml/src/nimqml/private/qvariant.nim(209) toQVariantSequence
/Users/alexjbanca/Repos/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(494) newSeq
/Users/alexjbanca/Repos/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(486) newObj
/Users/alexjbanca/Repos/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/system/gc_common.nim(430) prepareDealloc
/Users/alexjbanca/Repos/status-desktop/src/app/modules/main/communities/tokens/models/token_owners_model.nim(20) delete
/Users/alexjbanca/Repos/status-desktop/vendor/nimqml/src/nimqml/private/qabstractlistmodel.nim(39) delete
/Users/alexjbanca/Repos/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(64) delete
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by jrainville** [comment]
@alexjba it seems like it fails at a different place now :unamused: 

I'll try to add additional guards.

**Comment by jrainville** [comment]
@alexjba can you test the new build. According to your logs, it seems like the crash happened when `activeSectionChanged` was called (no idea why), and it turns out that signal was pretty useless. I tested the various ways an active community can be changed and they all reflect the changes already (we have internal signals already). 

`activeSectionChanged` should just be called when we switch from one section to another, so I feel confident removing it.

Still, I can't know for sure if that fixes your issue until you try :sweat_smile:

**Comment by jrainville** [comment]
> I have two different call stacks on two different runs. I can debug it tomorrow since it's reproducible on my end.

lol it seems like each time we fix one issue, another one pops. Anyway, yeah it would be way simpler if you could debug yourself. Trying to understand what is the community event that makes it crash would be good. Let me know if you need help

**Comment by alexjba** [comment]
Looks like it's crashing in Qt code when changing the token owners model. I think it's just one issue, but it reports different stacks because it depends when the nim GC will be triggered.

This stack is always the same:
```
    frame #1: 0x00000001036c8aa8 QtCore`___lldb_unnamed_symbol9441 + 324
    frame #2: 0x00000001036d0b34 QtCore`QSortFilterProxyModel::setSourceModel(QAbstractItemModel*) + 608
    frame #3: 0x00000001755c782c libStatusQ.dylib`qqsfpm::QQmlSortFilterProxyModel::setSourceModel(QAbstractItemModel*) + 448
    frame #4: 0x00000001036c257c QtCore`QAbstractProxyModel::qt_metacall(QMetaObject::Call, int, void**) + 96
    frame #5: 0x00000001036d4324 QtCore`QSortFilterProxyModel::qt_metacall(QMetaObject::Call, int, void**) + 32
    frame #6: 0x00000001755c1580 libStatusQ.dylib`qqsfpm::QQmlSortFilterProxyModel::qt_metacall(QMetaObject::Call, int, void**) + 32
    frame #7: 0x00000001028971e8 QtQml`___lldb_unnamed_symbol9479 + 360
    frame #8: 0x0000000102896ec4 QtQml`___lldb_unnamed_symbol9474 + 376
    frame #9: 0x0000000102895010 QtQml`QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) + 312
    frame #10: 0x0000000102875e6c QtQml`QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) + 484
    frame #11: 0x00000001037208a4 QtCore`___lldb_unnamed_symbol9943 + 148
    frame #12: 0x00000001028297ec QtQml`QQmlData::destroyed(QObject*) + 500
    frame #13: 0x0000000103718690 QtCore`QObject::~QObject() + 344
    frame #14: 0x0000000100d1e2ac nim_status_client`DOS::DosQAbstractListModel::~DosQAbstractListModel() + 68
    frame #15: 0x000000010016bb5c nim_status_client`delete__OOZvendorZnimqmlZsrcZnimqml_1817(self=0x00000002b6443530) at qobject.nim:64:2 [opt]
    frame #16: 0x000000010016c434 nim_status_client`delete__OOZvendorZnimqmlZsrcZnimqml_3023(self=0x00000002b6443530) at qabstractlistmodel.nim:39:2 [opt]
    frame #17: 0x000000010045858c nim_status_client`delete__appZmodulesZmainZcommunitiesZtokensZmodelsZtoken95owners95model_30(self=0x00000002b6443530) at token_owners_model.nim:22:2 [opt]
```

**Comment by jrainville** [comment]
@alexjba nice find. Can you fix? Feel free to add commits to this PR.

**Comment by alexjba** [comment]
> @alexjba nice find. Can you fix? Feel free to add commits to this PR.

Yes, working on it! Will add the commit here. I think it's related to https://github.com/status-im/status-desktop/issues/9345

**Comment by jrainville** [comment]
Great, thank you very much

**Comment by alexjba** [comment]
It's crashing on the following flow:
1. Expose `TokenOwnersModel` in the UI through `TokenModel`
2. `TokenOwnersModel` is used in QML through [SortFilterProxyModel](https://github.com/status-im/SortFilterProxyModel/blob/6a471f1bef1288407751400d93b12b7fa911474d/qqmlsortfilterproxymodel.cpp) to display data in Community Settings
3. Trigger a community update -> Nim GC collects `TokenOwnersModel `
4. Set `null` sourceModel in `SortFilterProxyModel ` -> `QSortFilterProxyModel ` tries to access the old model and crashes

While the same approach used [here](https://github.com/status-im/status-desktop/issues/9345) appears to fix the issue, I think it's a different root cause.
I've applied the same workaround on this `filteredModel` https://github.com/status-im/status-desktop/blob/master/ui/app/AppLayouts/Chat/panels/communities/TokenHoldersPanel.qml#LL39C2-L39C36 and the crash is fixed.

I'd expect the `QSortFilterProxyModel ` to connect to the `destroyed` event of the sourceModel and clean everything at step 3, but it doesn't happen (couldn't see any `destroyed` event when it's crashing).

IMO when the GC collects `TokenOwnersModel ` the UI should be informed before deleting the QObject instance.

**Comment by caybro** [comment]
> It's crashing on the following flow:
> 
> 1. Expose `TokenOwnersModel` in the UI through `TokenModel`
> 2. `TokenOwnersModel` is used in QML through [SortFilterProxyModel](https://github.com/status-im/SortFilterProxyModel/blob/6a471f1bef1288407751400d93b12b7fa911474d/qqmlsortfilterproxymodel.cpp) to display data in Community Settings
> 3. Trigger a community update -> Nim GC collects `TokenOwnersModel `
> 4. Set `null` sourceModel in `SortFilterProxyModel ` -> `QSortFilterProxyModel ` tries to access the old model and crashes
> 
> While the same approach used [here](https://github.com/status-im/status-desktop/issues/9345) appears to fix the issue, I think it's a different root cause. I've applied the same workaround on this `filteredModel` https://github.com/status-im/status-desktop/blob/master/ui/app/AppLayouts/Chat/panels/communities/TokenHoldersPanel.qml#LL39C2-L39C36 and the crash is fixed.
> 
> I'd expect the `QSortFilterProxyModel ` to connect to the `destroyed` event of the sourceModel and clean everything at step 3, but it doesn't happen (couldn't see any `destroyed` event when it's crashing).
> 
> IMO when the GC collects `TokenOwnersModel ` the UI should be informed before deleting the QObject instance.

I think the problem lies here (and would also explain why you never saw the `destroyed` signal):
```cpp
::DosQAbstractListModel *dos_qabstractlistmodel_create(void *dObjectPointer,
                                                       ::DosQMetaObject *metaObjectPointer,
                                                       ::DObjectCallback dObjectCallback,
                                                       ::DosQAbstractItemModelCallbacks *callbacks)
{
    auto metaObjectHolder = static_cast<DOS::DosIQMetaObjectHolder *>(metaObjectPointer);
    auto model = new DOS::DosQAbstractListModel(dObjectPointer,
                                                metaObjectHolder->data(),
                                                dObjectCallback,
                                                *callbacks);
    QQmlEngine::setObjectOwnership(model, QQmlEngine::CppOwnership);
    return static_cast<QObject *>(model);
}
```

**Comment by alexjba** [comment]
> I'd expect the `QSortFilterProxyModel ` to connect to the `destroyed` event of the sourceModel and clean everything at step 3, but it doesn't happen (couldn't see any `destroyed` event when it's crashing).

Looks like this is the reason why Qt doesn't know the object is destroyed.. 🤦 
https://github.com/status-im/status-desktop/blob/master/vendor/DOtherSide/lib/src/DOtherSide.cpp#L878C1-L879C1

**Comment by alexjba** [comment]
It's ready for review. I've added this commit on top: https://github.com/status-im/status-desktop/pull/11196/commits/287129490d1b0e9b71ea67b8c71df3f363ca9d75

File: vendor/DOtherSide/lib/src/DOtherSide.cpp [hunk 1]
```diff
@@ -875,7 +875,6 @@ ::DosQObject *dos_qobject_create(void *dObjectPointer, ::DosQMetaObject *metaObj
 void dos_qobject_delete(::DosQObject *vptr)
 {
     auto qobject = static_cast<QObject *>(vptr);
-    qobject->disconnect();
```
Comment (osmaczko) [inline vendor/DOtherSide/lib/src/DOtherSide.cpp:878]: Good catch @alexjba.

This can potentially cause problems if the object is still in use, for example, if there are pending events for the object in the event queue, leading to crashes.

I believe, this is a bit safer approach: https://github.com/status-im/nimqml/pull/50

Comment (alexjba) [reply vendor/DOtherSide/lib/src/DOtherSide.cpp:878]: Nice! Much better! 👍

Comment (alexjba) [reply vendor/DOtherSide/lib/src/DOtherSide.cpp]: @osmaczko WDYT of keeping this commit even if `dos_qobject_delete` is not used anymore? Just not to leave there code we know can crash the app. `dos_qobject_delete` might look promising to the next developer 😄

https://github.com/status-im/status-desktop/commit/287129490d1b0e9b71ea67b8c71df3f363ca9d75

**Review by alexjba — APPROVED** [review]
Tested and LGTM!

**Review by osmaczko — APPROVED** [review]

**Comment by jrainville** [comment]
@osmaczko @alexjba bad news, the changes in this commit https://github.com/status-im/status-desktop/pull/11196/commits/ee9bf96e6a9c7bc1ff5e2b678ba641a4704fbb5f (the nimqml bump) make the app crash when an account is added to the wallet.

Good news is Alex's changes to DOtherSide is ok.

So if @alexjba you  give the thumbs up that your DOtherSide changes also fix the crash from the original issue, we can rollback on the nimqml change and just merge with the DOtherSide fix.

**Comment by osmaczko** [comment]
> @osmaczko @alexjba bad news, the changes in this commit [ee9bf96](https://github.com/status-im/status-desktop/commit/ee9bf96e6a9c7bc1ff5e2b678ba641a4704fbb5f) (the nimqml bump) make the app crash when an account is added to the wallet.

It seems highly improbable... :eyes: Are you sure it's not a random crash? How can I reproduce it?

> Good news is Alex's changes to DOtherSide is ok.
> 
> So if @alexjba you give the thumbs up that your DOtherSide changes also fix the crash from the original issue, we can rollback on the nimqml change and just merge with the DOtherSide fix.

Sounds good to me, I will investigate nimqml bump separately.

**Comment by alexjba** [comment]
> @osmaczko @alexjba bad news, the changes in this commit [ee9bf96](https://github.com/status-im/status-desktop/commit/ee9bf96e6a9c7bc1ff5e2b678ba641a4704fbb5f) (the nimqml bump) make the app crash when an account is added to the wallet.

I've reproduced it twice. Different call stacks 🤦 

Authorise with biometrics
```
/Users/alexjbanca/Repos/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(558) onSlotCalled
/Users/alexjbanca/Repos/status-desktop/src/app_service/service/wallet_account/service.nim(566) onDerivedAddressesFetched
/Users/alexjbanca/Repos/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim(517) []
/Users/alexjbanca/Repos/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/tables.nim(246) []
/Users/alexjbanca/Repos/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/tables.nim(234) raiseKeyError
Error: unhandled exception: key not found: derivedAddresses [KeyError]
2023-06-26 21:53:56.412001+0300 nim_status_client[84293:2166690] [client] No error handler for XPC error: Connection invalid
```

Authorise with password:
```
frame #0: 0x0000000100d12da8 nim_status_client`dos_qobject_signal_emit + 432
    frame #1: 0x000000010016a078 nim_status_client`emit__OOZvendorZnimqmlZsrcZnimqml_1718(qobject=<unavailable>, signalName=<unavailable>, arguments=0x000000016fdfc410, argumentsLen_0=0) at qobject.nim:32:2 [opt]
    frame #2: 0x00000001006d7c90 nim_status_client`setDisablePopup__appZmodulesZshared95modulesZkeycard95popupZview_73 [inlined] diablePopupChanged__appZmodulesZshared95modulesZkeycard95popupZview_68(self=0x00000001023b6d40) at macros.nim:556:2 [opt]
    frame #3: 0x00000001006d7c04 nim_status_client`setDisablePopup__appZmodulesZshared95modulesZkeycard95popupZview_73(self=0x00000001023b6d40, value=<unavailable>) at view.nim:62:2 [opt]
    frame #4: 0x000000010072bd68 nim_status_client`preActionActivities__appZbootZapp95controller_17440(self=0x00000002bf167140, currFlowType=<unavailable>, currStateType='+') at module.nim:0:84 [opt]
    frame #5: 0x000000010072d618 nim_status_client`onCancelActionClicked__appZbootZapp95controller_17764(self=0x00000002bf167140) at module.nim:328:2 [opt]
    frame #6: 0x0000000100b09e58 nim_status_client`onCancelActionClicked__appZmodulesZshared95modulesZkeycard95popupZio95interface_109(self=0x00000002bf167140) at io_interface.nim:109:3 [opt]
    frame #7: 0x00000001006d6cdc nim_status_client`onSlotCalled__appZmodulesZshared95modulesZkeycard95popupZview_534 [inlined] onCancelActionClicked__appZmodulesZshared95modulesZkeycard95popupZview_103(self=0x00000001023b6d40) at view.nim:104:2 [opt]
```

**Comment by jrainville** [comment]
> Are you sure it's not a random crash? How can I reproduce it?

100% sure. The CI e2e tests fail, but I could also reproduce with local e2e and just doing the action manually.

The test I used is "The user manages a generated account". You can also generate an account yourself. It crashes once you generate the account.

The logs are not super useful:
```
Traceback (most recent call last)
/home/jonathan/dev/status-desktop/src/nim_status_client.nim(193) nim_status_client
/home/jonathan/dev/status-desktop/src/nim_status_client.nim(190) mainProc
/home/jonathan/dev/status-desktop/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec
/home/jonathan/dev/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/home/jonathan/dev/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/home/jonathan/dev/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(564) onSlotCalled
/home/jonathan/dev/status-desktop/src/app/modules/shared_modules/keycard_popup/view.nim(104) onCancelActionClicked
/home/jonathan/dev/status-desktop/src/app/modules/shared_modules/keycard_popup/io_interface.nim(109) onCancelActionClicked
/home/jonathan/dev/status-desktop/src/app/modules/shared_modules/keycard_popup/module.nim(328) onCancelActionClicked
/home/jonathan/dev/status-desktop/src/app/modules/shared_modules/keycard_popup/module.nim(186) preActionActivities
/home/jonathan/dev/status-desktop/src/app/modules/shared_modules/keycard_popup/view.nim(62) setDisablePopup
/home/jonathan/dev/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(556) diablePopupChanged
/home/jonathan/dev/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(32) emit
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [Makefile:750: run-linux] Segmentation fault (core dumped)
```

**Comment by jrainville** [comment]
@alexjba can you try this branch again. I force-pushed and removed the nimqml change. Check if you still have the original issue. Thanks

**Comment by jrainville** [comment]
e2e pass now, so at least there's that

**Comment by alexjba** [comment]
> @alexjba can you try this branch again. I force-pushed and removed the nimqml change. Check if you still have the original issue. Thanks

The original issue is fixed.

**Comment by alexjba** [comment]
I still can't add a new account, but seems like this issue is back https://github.com/status-im/status-desktop/issues/11010. This time on account derivation.
