### PR TITLE
fix(@desktop/onboarding): fix crash when restoring keys

### LINKED ISSUE #3191: Crash on recovering account
1. install latest master and make sure the data folder is clean
2. recover any known account using seed phrase and proceed to login

As result, the app crashes

```Users/jenkins/workspace/s-desktop_branches_macos_PR-3186/src/status/tasks/marathon/mailserver/worker.nim(162) workerThread
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3186/vendor/nim-task-runner/vendor/nim-chronos/chronos/asyncloop.nim(1082) waitFor
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3186/vendor/nim-task-runner/vendor/nim-chronos/chronos/asyncloop.nim(279) poll
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3186/src/status/tasks/marathon/mailserver/worker.nim(148) worker
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3186/src/status/tasks/marathon/mailserver/worker.nim(111) processMessage
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3186/src/status/tasks/qt.nim(16) finish
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3186/vendor/nimqml/src/nimqml.nim(40) signal_handler
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
QObject::~QObject: Timers cannot be stopped from another thread

### PR DESCRIPTION
**Pull request by alaibe**
fixes #3191

When retrieving keys, this value is nil

### CODE REVIEW

File: src/app/profile/core.nim [hunk 1]
```diff
@@ -41,14 +41,17 @@ proc init*(self: ProfileController, account: Account) =
   let appearance = self.status.settings.getSetting[:int](Setting.Appearance)
   let messagesFromContactsOnly = self.status.settings.getSetting[:bool](Setting.MessagesFromContactsOnly)
   let sendUserStatus = self.status.settings.getSetting[:bool](Setting.SendUserStatus)
-  let currentUserStatus = self.status.settings.getSetting[:JsonNode](Setting.CurrentUserStatus)["statusType"].getInt()
+  let currentUserStatus = self.status.settings.getSetting[:JsonNode](Setting.CurrentUserStatus)
+  var statusType = 0
+  if currentUserStatus != nil:
+    statusType = currentUserStatus["statusType"].getInt()
```
Comment (richard-ramos) [inline src/app/profile/core.nim:47]: It should be possible to replace this for:
```suggestion
  let currentUserStatus = self.status.settings.getSetting[:JsonNode](Setting.CurrentUserStatus){"statusType"}.getInt()
```
since this seems to be an optional value.

**Review by richard-ramos — APPROVED** [review]

**Comment by anastasiyaig** [comment]
it is tested, the failing linux build is not related to the branch (also fails in master)
