### PR TITLE
fix(messenger_contacts): Add toast notification when removing a contact

### LINKED ISSUE #10497: Contacts: No toast is displayed after removing a contact
# Bug Report

## Description

Split from and dependant on https://github.com/status-im/status-desktop/pull/10336

After removing a contact, an in app toast notification is expected but not currently displayed

## Steps to reproduce

Remove a contact via the contact's profile
Observe that no toast is displayed

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/aarch64/job/package/job/PR-10336/20/ 
- Operating System: Mac

### PR DESCRIPTION
**Pull request by shinnok**
# What

Show a toast notification when a contact is removed by the user. This is in addition to the system message displayed in the message view.

# Demo

SCR-20231002-lcfq-3

Fixes #10497

### CODE REVIEW

File: src/app/modules/main/chat_section/module.nim [hunk 1]
```diff
@@ -1013,9 +1013,10 @@ method onNewMessagesReceived*(self: Module, sectionIdMsgBelongsTo: string, chatI
   let messageBelongsToActiveChat = self.controller.getActiveChatId() == chatIdMsgBelongsTo
 
   singletonInstance.globalEvents.showMessageNotification(notificationTitle, plainText, sectionIdMsgBelongsTo,
-    self.controller.isCommunity(), messageBelongsToActiveSection, chatIdMsgBelongsTo, messageBelongsToActiveChat,
-    message.id, notificationType.int, chatTypeMsgBelongsTo == ChatType.OneToOne,
-    chatTypeMsgBelongsTo == ChatType.PrivateGroupChat)
+
+  self.controller.isCommunity(), messageBelongsToActiveSection, chatIdMsgBelongsTo, messageBelongsToActiveChat,
+  message.id, notificationType.int, chatTypeMsgBelongsTo == ChatType.OneToOne,
+  chatTypeMsgBelongsTo == ChatType.PrivateGroupChat)
```
Comment (jrainville) [inline src/app/modules/main/chat_section/module.nim:1019]: Can you undo this change? We use the "tab" to show that those lines belong to the previous call

**Review by jrainville — APPROVED** [review]
Nice work

**Review by caybro — APPROVED** [review]
