### PR TITLE
fix(l10n) Translations missing on LoginScreen

### LINKED ISSUE #18883: [l10n] Translations missing on LoginScreen
# Bug Report

## Steps to reproduce

1. Open Status 
2. Switch to Korean and restart your app
3. See the first log-in screen

#### Expected behavior
the first log in screen is in Korean

#### Actual behavior
the first log in screen is in English

Image

### Additional Information

- Status desktop version: v2.35.1
- Operating System: Windows 10

### PR DESCRIPTION
**Pull request by caybro**
### What does the PR do

- we need to actually set our default language and init the language service _prior_ to loading main.qml (Onboarding & Login Screen) as we don't handle dynamic retranslations yet

Fixes #18883

### Affected areas

Login Screen

### Architecture compliance

- [x] I am familiar with the [application architecture](/docs/architecture.md) and agreed good practices.
My PR is consistent with this document: [QML Architecture Guidelines](/guidelines/QML_ARCHITECTURE_GUIDE.md)

### Screencapture of the functionality

Snímek obrazovky z 2025-09-22 12-55-29

### Impact on end user

Login screen uses the translated texts

### How to test

Just start the app

### Risk 

low

### CODE REVIEW

File: src/app/boot/app_controller.nim [hunk 1]
```diff
@@ -355,11 +355,12 @@ proc initializeQmlContext(self: AppController) =
   singletonInstance.engine.setRootContextProperty("localAccountSettings", self.localAccountSettingsVariant)
   singletonInstance.engine.setRootContextProperty("globalUtils", self.globalUtilsVariant)
   singletonInstance.engine.setRootContextProperty("metrics", self.metricsVariant)
-  singletonInstance.engine.load(newQUrl("qrc:///main.qml"))
 
-  # We need to init a language service once qml is loaded
```
Comment (osmaczko) [inline src/app/boot/app_controller.nim:360]: I am wondering why this explicit comment was made before?

**Review by osmaczko — APPROVED** [review]

File: src/app/boot/app_controller.nim (hunk 1 above)
Comment (caybro) [reply src/app/boot/app_controller.nim:360]: I _think_ that at some point the live retranslation was in place but as it's disabled now, it can't work that way

**Review by jrainville — APPROVED** [review]
