### PR TITLE
fix(StatusWindow): fix changing the window state(s)

### LINKED ISSUE #14132: Window changes from maximum to normal size when you click on the Dock icon
## Steps to reproduce
1. Maximize the Status Desktop window size
2. Switch to another application 
3. Click the Status icon in the system tray Dock
4. The window changes size from maximized to normal size

#### Expected behavior
the application should remain maximized at step 4 (as other applications)

#### Actual behavior
the window should remain maximized

https://github.com/status-im/status-desktop/assets/1083341/dd62005e-8d19-4d0f-9103-255f383a77a1

### Additional Information

- Status desktop version: 2.28.0-rc.1
- Operating System: MacOS 14.4

### PR DESCRIPTION
**Pull request by caybro**
### What does the PR do

- since the window can be a combination of several states (e.g. maximized + fullscreen + minimized), use the newer `windowStates()` [flags](https://doc.qt.io/qt-5/qt.html#WindowState-enum) to track and toggle them
- call `makeStatusAppActive()` in all the identical codepaths (clicking tray icon, activating a mac or win instance, running a second instance, etc)
- fixes restoring the window to its previous state(s) when activating from the tray or dock icon
- use some more standard keyboard shortcuts

Fixes #14132

### Affected areas

main.qml, StatusWindow

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

[Záznam obrazovky z 2024-05-10 03-31-33.webm](https://github.com/status-im/status-desktop/assets/5377645/b52a538c-a773-423a-9183-d4454d809d7f)

### CODE REVIEW

**Review by saledjenic — APPROVED** [review]

File: ui/StatusQ/src/statuswindow.cpp [hunk 1]
```diff
@@ -1,43 +1,30 @@
...
 }
 
 void StatusWindow::toggleFullScreen()
 {
-    if (m_isFullScreen) {
-        showNormal();
-    } else {
-        showFullScreen();
-    }
+    setWindowStates(windowStates() ^ Qt::WindowFullScreen);
```
Comment (friofry) [inline ui/StatusQ/src/statuswindow.cpp:24]: In the #14132 ticket I had a problem with the `Maximized` state. The FullScreen state usually creates a separate desktop on mac

Comment (caybro) [reply ui/StatusQ/src/statuswindow.cpp:24]: But this is about the "fullscreen" state, which is a separate thing from maximized. Anyways, pls give it a try if it also solves your problem; if not, yell back :)

**Review by Seitseman — APPROVED** [review]
LGTM

File: ui/StatusQ/src/statuswindow.cpp (hunk 1 above)
Comment (friofry) [reply ui/StatusQ/src/statuswindow.cpp:24]: I've tested the branch and it works pefectly!

Comment (friofry) [reply ui/StatusQ/src/statuswindow.cpp:24]: I noticed another glitch with the double title bar  (first I clicked on full screen, then the "exit full screen" button).

image

Comment (caybro) [reply ui/StatusQ/src/statuswindow.cpp:24]: OK, that _might_ be something I introduced :/ Can you test on master without this PR? I don't have access to a mac

Comment (friofry) [reply ui/StatusQ/src/statuswindow.cpp:24]: I've tested on master and there is no double title bar when normalising from full screen. 

The system just makes a small jump: 

https://github.com/status-im/status-desktop/assets/1083341/732d40fa-12d5-48fb-a88a-382ce47e16df

Comment (caybro) [reply ui/StatusQ/src/statuswindow.cpp:24]: Thanks for testing! I'll fix the double window decoration

Comment (caybro) [reply ui/StatusQ/src/statuswindow.cpp:25]: @friofry pls update and give it another try, thanks :)

Comment (friofry) [reply ui/StatusQ/src/statuswindow.cpp:25]: the fix works 👍

**Review by friofry — APPROVED** [review]
