### PR TITLE
fix(showcase): unbreak drag and drop reordering

### LINKED ISSUE #13329: [Profile Showcase - General] Review existing drag/drop actions in Accounts / Assets / Collectibles and Communities. It seems in the current app state these actions are broken.

### PR DESCRIPTION
**Pull request by caybro**
- unify the signature of the method to `move(from, to, count)` so that both ListModel and NIM have it the same
- realize the move operation using the proper `begin/endMoveRows` instead of doing a full model reset
- simplify signaling `dataChanged()` for all model roles (nimqml now follows the C++ impl)

Fixes #13329

### What does the PR do

Fixes DND in profile showcase settings

### Affected areas

Settings/Profile/showcase tabs

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

[Záznam obrazovky z 2024-02-06 09-19-17.webm](https://github.com/status-im/status-desktop/assets/5377645/0dc3b5b0-2eb1-418d-8a62-53fde7ca7777)

### CODE REVIEW

File: src/app/modules/main/profile_section/profile/models/profile_preferences_communities_model.nim [hunk 1]
```diff
@@ -184,16 +173,25 @@ QtObject:
     if ind != -1:
       self.remove(ind)
 
-  proc move*(self: ProfileShowcaseCommunitiesModel, fromIndex: int, toIndex: int) {.slot.} =
-    if fromIndex < 0 or fromIndex >= self.items.len:
+  proc move*(self: ProfileShowcaseCommunitiesModel, fromRow: int, toRow: int, dummyCount: int = 1) {.slot.} =
```
Comment (alexjba) [inline src/app/modules/main/profile_section/profile/models/profile_preferences_communities_model.nim:176]: `dummyCount` will probably end up in a warning because it is not used. Try to use `_`

**Review by alexjba — APPROVED** [review]
LGTM!
Minor suggestion below

File: src/app/modules/main/profile_section/profile/models/profile_preferences_communities_model.nim (hunk 1 above)
Comment (caybro) [reply src/app/modules/main/profile_section/profile/models/profile_preferences_communities_model.nim:176]: Ah, honestly didn't notice as there are too many warning already :/

**Review by micieslak — APPROVED** [review]
LGTM!
