### PR TITLE
fix(@desktop): missing context menu on SystemTrayIcon

### LINKED ISSUE #2919: missing context menu to quit app on windows
On Windows, when closing and reopening the app, it seems like multiple instances of the app are running and causing some sort of db conflict. I get a 'wrong password' entry in these cases and when I check I see multiple instances in the tray on Windows https://www.loom.com/share/ec87e33363de4c52ab712f51118904f9

### Current
When _Closing_ the app Window it appears to me as a user that I _Quit_ the app. This expectation is reinforced by having to enter my password after Clicking on the app icon to restart Status Desktop. When entering my password I get a wrong password error. I have to manually force quit the app via Task manager and restart to avoid this error. There is no UI to Quit the application when the Window is closed

### Expected

- When closing and reopening the application window I can enter a correct password without error message to access my account
- I can quit the application from the tray by right-clicking on the Status app icon (see Discord for example)
Screenshot 2021-07-15 110145

Issue occurred with Master of 15/07 on Windows

### PR DESCRIPTION
**Pull request by pinebit**
Fixes #2919 

Do not merge before https://github.com/status-im/dotherside/pull/29 and https://github.com/status-im/nimqml/pull/21 are merged.

### CODE REVIEW

File: src/nim_status_client.nim [hunk 1]
```diff
@@ -47,7 +47,7 @@ proc mainProc() =
   enableHDPI()
   initializeOpenGL()
 
-  let app = newQApplication("Status Desktop")
+  let app = newQGuiApplication()
```
Comment (richard-ramos) [inline src/nim_status_client.nim:50]: Since the `Status Desktop` argument was removed,  wouldnt we have to call `setApplicationDisplayName` to set the title?

Comment (pinebit) [reply src/nim_status_client.nim:50]: If you were diving deeper and saw where what "Status Desktop" argument went... it went to argv[0] that supposed to represent the executable filepath. `"Status Desktop"` string is not an executable filepath and therefore it never was the "application display name".
What you are looking for is there already, in main.qml:46
`Qt.application.name = qsTrId("status-desktop")`

**Review by jrainville — APPROVED** [review]

**Comment by richard-ramos** [comment]
I'm running into this error when launching desktop. (I rm'ed vendor/* completely just to confirm)
```
richard@laptop:~/status/status-desktop$ make run
Building: resources.rcc
Running: bin/nim_status_client
Network Cache Dir:  "/home/richard/status/status-desktop/Status/tmp/netcache"
Traceback (most recent call last)
/home/richard/status/status-desktop/src/nim_status_client.nim(220) nim_status_client
/home/richard/status/status-desktop/src/nim_status_client.nim(204) mainProc
/home/richard/status/status-desktop/vendor/nimqml/src/nimqml/private/qqmlapplicationengine.nim(15) load
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [Makefile:428: run-linux] Error 1
```

Here's the GDB stacktrace:
```
-Type <RET> for more, q to quit, c to continue without paging--
Thread 1 "nim_status_clie" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt 10
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff51acf4d in QString::fromLocal8Bit(char const*, int) (size=-1, str=0x1 <error: Cannot access memory at address 0x1>)
    at ../../include/QtCore/../../src/corelib/text/qstring.h:671
#2  QCoreApplication::arguments() () at kernel/qcoreapplication.cpp:2455
#3  0x00007ffff743fbf4 in contextFactory() () at scenegraph/qsgcontextplugin.cpp:120
#4  0x00007ffff74403a9 in QSGContext::createWindowManager() () at scenegraph/qsgcontextplugin.cpp:228
#5  0x00007ffff744959a in QSGRenderLoop::instance() () at scenegraph/qsgrenderloop.cpp:220
#6  0x00007ffff74c116a in QQuickWindowPrivate::init(QQuickWindow*, QQuickRenderControl*) (this=0x555556188490, c=0x5555563efb90, control=0x0) at items/qquickwindow.cpp:630
#7  0x0000555555ea92d9 in StatusWindow::StatusWindow(QWindow*) ()
#8  0x0000555555dfd8bf in void QQmlPrivate::createInto<StatusWindow>(void*) ()
#9  0x00007ffff6e9224e in QQmlType::create(QObject**, void**, unsigned long) const
    (this=this@entry=0x7fffffffce90, out=out@entry=0x7fffffffcea8, memory=memory@entry=0x7fffffffcec0, additionalMemory=additionalMemory@entry=144) at qml/qqmltype.cpp:485
#10 0x00007ffff6ee572e in QQmlObjectCreator::createInstance(int, QObject*, bool)
    (this=this@entry=0x5555562bf800, index=index@entry=0, parent=parent@entry=0x0, isContextObject=isContextObject@entry=true) at qml/qqmlobjectcreator.cpp:1203
#11 0x00007ffff6ee8c7e in QQmlObjectCreator::create(int, QObject*, QQmlInstantiationInterrupt*)
    (this=0x5555562bf800, subComponentIndex=<optimized out>, parent=parent@entry=0x0, interrupt=interrupt@entry=0x0) at qml/qqmlobjectcreator.cpp:205
#12 0x00007ffff6e735b8 in QQmlComponentPrivate::beginCreate(QQmlContextData*) (this=0x5555562e88d0, context=<optimized out>) at qml/qqmlcomponent.cpp:917
#13 0x00007ffff6e709e5 in QQmlComponentPrivate::doBeginCreate(QQmlComponent*, QQmlContext*) (this=<optimized out>, q=0x55555635a880, context=<optimized out>) at qml/qqmlcomponent.cpp:362
#14 0x00007ffff6e70a58 in QQmlComponent::create(QQmlContext*) (this=0x55555635a880, context=<optimized out>) at qml/qqmlcomponent.cpp:809
#15 0x00007ffff6ed88fc in QQmlApplicationEnginePrivate::finishLoad(QQmlComponent*) (this=this@entry=0x55555633e600, c=c@entry=0x55555635a880) at qml/qqmlapplicationengine.cpp:134
#16 0x00007ffff6ed8a8e in QQmlApplicationEnginePrivate::startLoad(QUrl const&, QByteArray const&, bool) (this=0x55555633e600, url=..., data=..., dataFlag=dataFlag@entry=false)
    at qml/qqmlapplicationengine.cpp:118
#17 0x00007ffff6ed8abd in QQmlApplicationEngine::load(QUrl const&) (this=<optimized out>, url=<optimized out>) at qml/qqmlapplicationengine.cpp:264
#18 0x00005555556fb4f3 in load__FYgu6oVycaHtUhp8bHAwGA (self=0x7fffedb8cac8, url=0x7fffedba3ba8)
    at /home/richard/status/status-desktop/vendor/nimqml/src/nimqml/private/qqmlapplicationengine.nim:15
#19 0x0000555555deaa3d in mainProc__m7gKUv239cTlei8d6JcfbeA () at /home/richard/status/status-desktop/src/nim_status_client.nim:204

```

**Comment by pinebit** [comment]
Fixed now.

**Review by jrainville — APPROVED** [review]

File: src/nim_status_client.nim (hunk 1 above)
Comment (borismelnik) [reply src/nim_status_client.nim:50]: First - why its should be translated? and how executable name have to do with display name?

Comment (pinebit) [reply src/nim_status_client.nim:50]: https://stackoverflow.com/a/38371112

Comment (borismelnik) [reply src/nim_status_client.nim:50]: Sorry but i don't see any answers on any questions in this thread.

Comment (pinebit) [reply src/nim_status_client.nim:50]: > and how executable name have to do with display name?

> From V5, these will fall back to the executable name if the property is not set.

As for the first question: I quoted existing code from main.qml. I dont know why someone decided to translate it.
