### PR TITLE
fix(@desktop/chat): [very hard to replicate] 1 to 1 chat window contains messages from other contacts

### LINKED ISSUE #5668: [very hard to replicate] 1 to 1 chat window contains messages from other contacts
# Bug Report

## Description

1 to 1 chats seem to contain messages from other contacts.

Also, @PascalPrecht noticed this discrepancy where a public chat msg was seen on a 1 to 1 chat -> [here](https://discord.com/channels/624205794384281629/697843216048717905/971327104698449960)

## Steps to reproduce

1. Launch app, sign in (Usr-1) and send a contact request to a user (Usr-2)
2. Sign out and sign in as Usr-2 and accept the contact request from Usr-1
3. Send a msg to Usr-1 and then sign out
4. Sign in as another user (Usr-3) and send a contact request and then a msg to Usr-1
5. Sign out and sign back in as Usr-1
6. Accept the contact request from Usr-3 
7. Check the 1 to 1 chat from Usr-2

#### Expected behavior
The user must only see the msg from the selected user

#### Actual behavior
The chat window also shows msg from another 1 to 1 chat 
image

### Additional Information

- Status desktop version: Master : d4ef0ff5e864d342857b51f58cea67c5db5004c2

### PR DESCRIPTION
**Pull request by saledjenic**
Main issue was in the `handleMessagesUpdate` proc. That proc receives array of chats and array of messages for all chats added to the array of chats, but the thing was that we were referring only to the chat on index `0` and sending all messages (even they are belonging to different chats) as messages of that chat on index `0`.

Fixes #5668

### CODE REVIEW

**Review by richard-ramos — APPROVED** [review]

**Review by PascalPrecht — APPROVED** [review]
Nice!

**Review by alaibe — APPROVED** [review]
Good find!

File: src/app_service/service/message/service.nim [hunk 1]
```diff
@@ -181,22 +166,34 @@ QtObject:
...
-      messages: messages
-    )
-    self.events.emit(SIGNAL_NEW_MESSAGE_RECEIVED, data)
+    for i in 0 ..< chats.len:
+      if(chats[i].chatType == ChatType.Unknown):
+        error "error: new message with an unknown chat type received", chatId=chats[i].id
+        continue
+      
+      if chats[i].communityId.len == 0:
+        chats[i].communityId = singletonInstance.userProfile.getPubKey()
```
Comment (osmaczko) [inline src/app_service/service/message/service.nim:186]: looks super suspicious, why is that :thinking:?

wasn't the code below more descriptive/precise?
```
let sectionId = if chats[i].communityId.len > 0: chats[i].communityId else: singletonInstance.userProfile.getPubKey()
```

Comment (saledjenic) [reply src/app_service/service/message/service.nim:186]: @osmaczko what's the difference you see between this:
```
let sectionId = if chats[i].communityId.len > 0: chats[i].communityId else: singletonInstance.userProfile.getPubKey()

# and then in the place of usage we had this line:
sectionId: sectionId,
```
and this:
```
if chats[i].communityId.len == 0:
   chats[i].communityId = singletonInstance.userProfile.getPubKey()

# now in the place of usage we have this line:
sectionId: chats[i].communityId,
```

so in terms of code, we're doing the same thing, if `communityId` is not set, we set it to public key of the logged in user, but the difference is that we're sending signal for each chat now instead only for a single chat positioned on the index `0` in the `chats` array, and that was the issue actually.

Comment (saledjenic) [reply src/app_service/service/message/service.nim:191]: If this condition `chats[i].communityId.len == 0` is true, means that chat belongs to `Chat` section, and since we switched to channel group id of the `Chat` section is the same as public key of logged in user.
