### PR TITLE
fix(@desktop/chat): add a blocked bar for blocked user profile

### LINKED ISSUE #4673: re-add to master: feat(Chat/BlockedContacts) Add a Blocked bar for blocked user profile
b5f4e3783cb7b651372f3ff9ab2d2befb33fd7ac

### PR DESCRIPTION
**Pull request by saledjenic**
- blocked bar is added for profile popup
- blocked bar is added for a chat

Within this pr new field `blocked` is added to the item and subItem of the `chatsModel` and it is updated correctly in case of `Chat` section. Adding `blocked` to subItem gives us possibility to easily add "blocking" feature to community's channels later (when that become a request), but till then `blocked` prop is set to `false` in case of community for all channels.

Fixes #4673

### CODE REVIEW

File: src/app/modules/main/chat_section/sub_item.nim [hunk 1]
```diff
@@ -8,10 +8,10 @@ type
     parentId: string
 
 proc initSubItem*(id, parentId, name, icon: string, isIdenticon: bool, color, description: string, `type`: int, 
-  amIChatAdmin: bool, hasUnreadMessages: bool, notificationsCount: int, muted, active: bool, position: int): SubItem =
+  amIChatAdmin: bool, hasUnreadMessages: bool, notificationsCount: int, muted, blocked, active: bool, position: int): SubItem =
```
Comment (noeliaSD) [inline src/app/modules/main/chat_section/sub_item.nim:11]: Without knowing nothing about nim.. should it be defined, as well, that `blocked` is a `bool`? Maybe the same happens with `muted`..

File: src/app/modules/main/chat_section/module.nim [hunk 2]
```diff
@@ -108,14 +108,19 @@ proc buildChatUI(self: Module, events: EventEmitter,
...
+      chatName = contactDetails.displayName
+      chatImage = contactDetails.icon
+      isIdenticon = contactDetails.isIdenticon
+      blocked = contactDetails.details.isBlocked()
 
     let amIChatAdmin = self.amIMarkedAsAdminUser(c.members)
 
     let item = initItem(c.id, chatName, chatImage, isIdenticon, c.color, c.description, c.chatType.int, amIChatAdmin, 
-    hasNotification, notificationsCount, c.muted, active = false, c.position, c.categoryId)
+    hasNotification, notificationsCount, c.muted, blocked=blocked, active=false, c.position, c.categoryId)
```
Comment (noeliaSD) [inline src/app/modules/main/chat_section/module.nim:123]: Should it be only passing `blocked`without the need of assignement?

**Comment by noeliaSD** [comment]
@saledjenic some minor comments, not sure if correct as don't know nim! 
The task itself LGTM, I've tested and works fine and it has been very nice to follow the flow of adding a new property to the model and how it is the complete developement flow!

File: src/app/modules/main/chat_section/sub_item.nim (hunk 1 above)
Comment (saledjenic) [reply src/app/modules/main/chat_section/sub_item.nim:11]: @noeliaSD in `Nim` defining proc like `proc procName(param1, param2, param3: AnyNimType)` is the same as `proc procName(param1: AnyNimType, param2: AnyNimType, param3: AnyNimType)`, that's the matter of personal preference or coding style.

File: src/app/modules/main/chat_section/module.nim (hunk 2 above)
Comment (saledjenic) [reply src/app/modules/main/chat_section/module.nim:123]: @noeliaSD please check few lines above, `blocked` is the variable defined locally for that proc and `blocked` is the name of the parameter expected in `initItem`.

File: src/app/modules/main/chat_section/sub_item.nim (hunk 1 above)
Comment (noeliaSD) [reply src/app/modules/main/chat_section/sub_item.nim:11]: > @noeliaSD in `Nim` defining proc like `proc procName(param1, param2, param3: AnyNimType)` is the same as `proc procName(param1: AnyNimType, param2: AnyNimType, param3: AnyNimType)`, that's the matter of personal preference or coding style.

Ok! Perfect!! Thanks for the explanaition!

File: src/app/modules/main/chat_section/module.nim (hunk 2 above)
Comment (noeliaSD) [reply src/app/modules/main/chat_section/module.nim:123]: > @noeliaSD please check few lines above, `blocked` is the variable defined locally for that proc and `blocked` is the name of the parameter expected in `initItem`.

Got it! :)

**Review by noeliaSD — APPROVED** [review]

**Review by alaibe — APPROVED** [review]

File: src/app/modules/main/chat_section/module.nim (hunk 2 above)
Comment (jrainville) [reply src/app/modules/main/chat_section/module.nim:123]: It is still correct to say that it's not necessary to define the param name. It could have been only `c.muted, blocked,...`

IMO, defining the param name is only necessary when the value passed is not clear, line the next one. Saying the param is `active` is helpful, because `true` doesn't mean much.

Anyway, all that to say that you can remove `blocked=` here.

**Review by jrainville — APPROVED** [review]
Nice job

**Comment by saledjenic** [comment]
> Anyway, all that to say that you can remove blocked= here.

@jrainville perfectly agree with you, overlooked that, updated.
