### PR TITLE
(Chat): Display system messages about adding/removing members immediately after an update is performed

### LINKED ISSUE #9876: Chats: If you remove/add user from the group chat, system message will be displayed only after app restart
# Bug Report

## Description

If you remove/add the user from the group chat, the system message that the user left/added the group will be displayed only after the app restart

## Steps to reproduce

1. Create a private group chat
2. Remove/add one of the members

#### Expected behavior
The system message that [user] left the group/was added is present

#### Actual behavior
The system message that [user] left the group/ was added is absent

https://user-images.githubusercontent.com/117639195/225014837-d43b7056-034c-48ce-80cf-8fff8e398035.mov

### Additional Information
 
- Status desktop version: 0.10.0-rc13
- Operating System: macos

TODO: it would be nice to resolve, when user left the group and when user was removed by admin from the group

### PR DESCRIPTION
**Pull request by friofry**
fixes #9876, #10702

### What does the PR do
chats/service.nim

1. `addGroupMembers`/`removeMemberFromGroupChat` now analyzes and processes the `GroupChatResponse`
2. Similarly to the `processMessageUpdateAfterSend`, the procedure `processGroupChatUpdateAfterSend` has been added. Now they both use the `signalChatsAndMessagesUpdates` proc, which emits signals to notify UI of new chats/messages
3. Added a separate `parseGroupChatResponse` method to parse GroupChatResponse, since this structure has 'chat' and ChatResponse has 'chats'

### Screenshot of functionality (including design for comparison)

https://github.com/status-im/status-desktop/assets/1083341/67bf41f1-da24-4665-a01b-dabc2c2d06fb

### CODE REVIEW

File: src/app_service/service/chat/service.nim [hunk 1]
```diff
@@ -400,22 +400,41 @@ QtObject:
...
+      if chatMap.hasKey(msg.chatId):
+        let chat = chatMap[msg.chatId]
+        self.events.emit(SIGNAL_SENDING_SUCCESS, MessageSendingSuccess(message: msg, chat: chat))
+
+  proc processMessageUpdateAfterSend*(self: Service, response: RpcResponse[JsonNode]): (seq[ChatDto], seq[MessageDto]) =
+    result = self.parseChatResponse(response)
+    var (chats, messages) = result
+    self.signalChatsAndMessagesUpdates(chats, messages)
+
+  proc processGroupChatUpdateAfterSend*(self: Service, response: RpcResponse[JsonNode]): (ChatDto, seq[MessageDto]) =
```
Comment (igor-sirotin) [inline src/app_service/service/chat/service.nim:434]:
```suggestion
  proc processGroupChatUpdateResponse*(self: Service, response: RpcResponse[JsonNode]): (ChatDto, seq[MessageDto]) =
```

Comment (igor-sirotin) [reply src/app_service/service/chat/service.nim:434]: Also, do we actually need to return `(ChatDto, seq[MessageDto])`, if we're discarding it in both usages?

File: src/app_service/service/chat/service.nim [hunk 2]
```diff
@@ -400,22 +400,41 @@ QtObject:
...
     for msg in messages:
-      for chat in chats:
-        if chat.id == msg.chatId:
-          self.events.emit(SIGNAL_SENDING_SUCCESS, MessageSendingSuccess(message: msg, chat: chat))
-          break
+      if chatMap.hasKey(msg.chatId):
+        let chat = chatMap[msg.chatId]
+        self.events.emit(SIGNAL_SENDING_SUCCESS, MessageSendingSuccess(message: msg, chat: chat))
+
+  proc processMessageUpdateAfterSend*(self: Service, response: RpcResponse[JsonNode]): (seq[ChatDto], seq[MessageDto]) =
```
Comment (igor-sirotin) [inline src/app_service/service/chat/service.nim:429]: I know it's not your code, but this `AfterSend` is quite weird. 
The name of the function should describe what it does, not when it will be called. 😄 

```suggestion
  proc processMessageUpdateResponse*(self: Service, response: RpcResponse[JsonNode]): (seq[ChatDto], seq[MessageDto]) =
```

**Review by igor-sirotin — APPROVED** [review]

File: src/app_service/service/chat/service.nim (hunk 2 above)
Comment (friofry) [reply src/app_service/service/chat/service.nim:429]: Yes, that makes sense!
Since `protocol/messenger.go` uses the `MessengerResponse` type, it might be better to use the same name in proc. Something like `proc processMessengerResponse*(self: Service, response: RpcResponse[JsonNode]): `.

File: src/app_service/service/chat/service.nim (hunk 1 above)
Comment (friofry) [reply src/app_service/service/chat/service.nim:434]: fixed

File: src/app_service/service/chat/service.nim [hunk 3]
```diff
@@ -400,25 +400,43 @@ QtObject:
         chats.add(chat)
     result = (chats, messages)
 
-  proc processMessageUpdateAfterSend*(self: Service, response: RpcResponse[JsonNode]): (seq[ChatDto], seq[MessageDto]) =
-    result = self.parseChatResponse(response)
-    var (chats, messages) = result
+  proc parseGroupChatResponse*(self: Service, response: RpcResponse[JsonNode]): (ChatDto, seq[MessageDto]) =
+    var chat: ChatDto
+    var messages: seq[MessageDto] = @[]
+    if response.result{"chat"} != nil:
```
[the remark this answers is not in the document]
Comment (friofry) [reply src/app_service/service/chat/service.nim:406]: Done ✅

File: src/app_service/service/chat/service.nim [hunk 4]
```diff
@@ -400,25 +400,43 @@ QtObject:
         chats.add(chat)
     result = (chats, messages)
 
-  proc processMessageUpdateAfterSend*(self: Service, response: RpcResponse[JsonNode]): (seq[ChatDto], seq[MessageDto]) =
-    result = self.parseChatResponse(response)
-    var (chats, messages) = result
+  proc parseGroupChatResponse*(self: Service, response: RpcResponse[JsonNode]): (ChatDto, seq[MessageDto]) =
```
[the remark this answers is not in the document]
Comment (friofry) [reply src/app_service/service/chat/service.nim]: Fixed

**Review by jrainville — APPROVED** [review]
