### PR TITLE
fix(@desktop/wallet) make collection expansion more responsive

### LINKED ISSUE #8406: Expanding a collection freezes UI until collectibles are fetched
# Bug Report

## Description

Collectibles are fetched in a blocking way after expanding a collection, so the whole UI freezes until the fetch is complete.
Make it async and add some "loading" animation.

[collectibles_freeze-2022-11-23_09.55.55.webm](https://user-images.githubusercontent.com/11161531/203552915-26a369b7-fc77-4190-89b9-0db0d371d35d.webm)

## Steps to reproduce

Expand a couple of Collections to notice this effect.

### Additional Information

- Status desktop version: v0.8.0rc2
- Operating System: Kubuntu 22.04

### PR DESCRIPTION
**Pull request by dlipicar**
### What does the PR do
Fixes #8406
Collection fetch is now non-blocking. This makes collection expansion more responsive.
Added a couple of changes to Collectibles service as preparation for future work.

Old:
[collection_expand_old-2022-11-29_15.42.29.webm](https://user-images.githubusercontent.com/11161531/204618274-1f0309df-47f0-4e20-a3bb-060a93f9e806.webm)

New:
[collection_expand_new-2022-11-29_15.37.38.webm](https://user-images.githubusercontent.com/11161531/204618300-9cf525a3-0f26-4d82-9729-6525f71a9143.webm)

Depends on https://github.com/status-im/status-desktop/pull/8487

### Affected areas
Wallet -> Collectibles

### CODE REVIEW

File: src/app_service/service/collectible/service.nim [hunk 1]
```diff
@@ -47,37 +59,74 @@ QtObject:
...
+
+          let collectiblesJson = responseObj["collectibles"]
+          if (collectiblesJson.kind == JArray):
+            data.collectibles = map(collectiblesJson.getElems(), proc(x: JsonNode): CollectibleDto = x.toCollectibleDto())
     except Exception as e:
       let errDesription = e.msg
-      error "error: ", errDesription
-      return
+      error "error onGetCollectibles: ", errDesription
+    self.events.emit(GetCollectibles, data)
```
Comment (saledjenic) [inline src/app_service/service/collectible/service.nim:120]: @dlipicar please rename this signal to `collectiblesFetched` or some name by your choice which will describe what we're doing, this way is a bit confusing for one who connects to it. I would expect that I have to get/fetch them from somewhere if I would receive it.

**Review by saledjenic — APPROVED** [review]

File: src/app_service/service/collectible/service.nim (hunk 1 above)
Comment (dlipicar) [reply src/app_service/service/collectible/service.nim:120]: I did exactly that on a separate PR :D https://github.com/status-im/status-desktop/issues/8407
In the new PR, it gets renamed to "SIGNAL_COLLECTIBLES_UPDATED", here I only wanted to be consistent with the signal name we have for Collections. 

I'll make it ready for review when this one gets merged.

**Review by alaibe — APPROVED** [review]
