### PR TITLE
fix(delete): fix closing the app before login would make it crash

### LINKED ISSUE #12880: Segmentation fault (Linux)
### Description

```
Traceback (most recent call last)
/home/anastasiya/status-desktop/src/nim_status_client.nim(208) nim_status_client
/home/anastasiya/status-desktop/src/nim_status_client.nim(181) mainProc
/home/anastasiya/status-desktop/src/app/boot/app_controller.nim(297) delete
/home/anastasiya/status-desktop/src/app/modules/startup/io_interface.nim(19) delete
/home/anastasiya/status-desktop/src/app/modules/startup/module.nim(87) delete
/home/anastasiya/status-desktop/vendor/nimqml/src/nimqml/private/qqmlapplicationengine.nim(29) setRootContextProperty
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [Makefile:815: run-linux] Segmentation fault (core dumped)
```

1. build the app on linux (latest master)
2. close the app by clicking cross button
3. check the console

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #12880

There were two problems:
1. We manually delete the startup module on login to free memory. Part of that clean up includes remove the QVariant (` singletonInstance.engine.setRootContextProperty("startupModule", newQVariant())`), but since that code was put in the `delete` function of the module, it meant it was also executed on quit, and you can't call `setRootContextProperty` on quit
2. The wallet module is created on app start. That's fine, it doesn't do anything. However, it has a sub module that later in its cycle creates account items, but most of the time, those account items are not initiated, so on `delete`, there was a crash.

### CODE REVIEW

**Comment by anastasiyaig** [comment]
I can confirm this PR fixes issue that were facing my tests, when running - the app was crashing in wallet module. Now they are good

https://ci.status.im/job/status-desktop/job/e2e/job/manual/1124/allure/

**Review by saledjenic — APPROVED** [review]

File: src/app/modules/main/wallet_section/send/view.nim [hunk 1]
```diff
@@ -35,11 +35,13 @@ QtObject:
...
     self.accounts.delete
     self.senderAccounts.delete
-    self.selectedSenderAccount.delete
+    if self.selectedSenderAccount != nil:
+      self.selectedSenderAccount.delete
     self.fromNetworksModel.delete
     self.toNetworksModel.delete
     self.transactionRoutes.delete
-    self.selectedReceiveAccount.delete
+    if self.selectedSenderAccount != nil:
```
Comment (caybro) [inline src/app/modules/main/wallet_section/send/view.nim:43]: Now this looks wrong... :) And would still crash under some conditions imo

```suggestion
    if self.selectedReceiveAccount != nil:
```

**Comment by jakubgs** [comment]
Can't really review this, but thank you for tracking this down.

**Review by caybro — CHANGES_REQUESTED** [review]
Sorry for the red flag :)

**Comment by anastasiyaig** [comment]
can someone do this change? Jo is on vacation and i need this pr @caybro

**Comment by caybro** [comment]
> can someone do this change? Jo is on vacation and i need this pr @caybro

Yeah, I can do it, just a minute

**Comment by caybro** [comment]
> > can someone do this change? Jo is on vacation and i need this pr @caybro
> 
> Yeah, I can do it, just a minute

Done, let's just wait for the build to finish :)

**Review by caybro — APPROVED** [review]

**Comment by anastasiyaig** [comment]
I will be brave to merge it :)

**Comment by jrainville** [comment]
I'm not yet on vacation, but thanks for doing it for me :laughing:

**Comment by anastasiyaig** [comment]
oh , i am so sorry @jrainville 

image
