### PR TITLE
fix(@desktop/communities): community import has some issues

### LINKED ISSUE #4206: Community import has some issues
I tried importing the community for the waku v2 dogfooding community, but it had some issues:

- The spinner never stopped spinning (I waited more than 5 minutes)
- Once I closed and re-opened, the community was there, but missing a lot of stuff
  - No image
  - No color
  - Missing members
  - No description

The channels are there however and have messages

My guess is the import just didn't work. 

I sadly don't have logs since I was using a release build on Windows.

It might also be related to being connected to the wakuv2-test fleet

### PR DESCRIPTION
**Pull request by saledjenic**
Fixes #4206

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

File: src/app_service/service/community/service.nim [hunk 1]
```diff
@@ -635,11 +639,48 @@ QtObject:
   proc importCommunity*(self: Service, communityKey: string) =
     try:
       let response = status_go.importCommunity(communityKey)
```
Comment (osmaczko) [inline src/app_service/service/community/service.nim:641]: Is this call blocking the GUI thread?

File: ui/app/AppLayouts/Chat/popups/community/AccessExistingCommunityPopup.qml [hunk 2]
```diff
@@ -72,35 +66,19 @@ StatusModal {
...
                 }
 
-
-                root.error = root.store.chatsModelInst.communities.importCommunity(communityKey, Utils.uuid())
-                if (!!root.error) {
-                    creatingError.text = error;
-                    return creatingError.open();
-                }
-
+                root.store.communitiesModuleInst.importCommunity(communityKey);
```
Comment (osmaczko) [inline ui/app/AppLayouts/Chat/popups/community/AccessExistingCommunityPopup.qml:79]:
```suggestion
                root.store.importCommunity(communityKey);
```

File: ui/app/AppLayouts/Chat/views/ContactsColumnView.qml [hunk 3]
```diff
@@ -431,52 +430,46 @@ Item {
...
-//            }
-
-//            Global.toastMessage.displayCloseButton = false
-//            Global.toastMessage.displayLink = false
-//            Global.toastMessage.iconColor = Style.current.primary
-//            Global.toastMessage.open()
-//        }
-//    }
+    Connections {
+        target: root.store.communitiesModuleInst
```
Comment (osmaczko) [inline ui/app/AppLayouts/Chat/views/ContactsColumnView.qml:434]: Seems to be not aligned with our QML architecture. Not sure how to solve such a case in a different way though..

File: src/app_service/service/community/service.nim (hunk 1 above)
Comment (saledjenic) [reply src/app_service/service/community/service.nim:641]: @osmaczko yes it is, we discussed that in private chat already. So the only way to avoid this is to call this in an async way. I just used the way how it was in the "old" master, but will try to update it now and make an async call to the status import community end point.

File: ui/app/AppLayouts/Chat/popups/community/AccessExistingCommunityPopup.qml (hunk 2 above)
Comment (saledjenic) [reply ui/app/AppLayouts/Chat/popups/community/AccessExistingCommunityPopup.qml:79]: @osmaczko yes, I missed that, if we want to stick to some qml rules we introduced, we have call appropriate function from the store which will do what it needs with the real "module" behind.

**Comment by anastasiyaig** [comment]
@saledjenic please take a look, channels are not visible after creating them without restarting the app, also when joining the recovered community - it does not show up.

Master seems to be not having this issue (at first glance). Was able to add a channel in community and see it without restarting the app


https://user-images.githubusercontent.com/82375995/152328782-223a1a8e-20cd-4ca5-b0fb-25be8267f2a6.mov

File: ui/app/AppLayouts/Chat/views/ContactsColumnView.qml (hunk 3 above)
Comment (saledjenic) [reply ui/app/AppLayouts/Chat/views/ContactsColumnView.qml:434]: @saledjenic this is not the case here. We already have a level of indirection in the store:
```
property var communitiesModuleInst: communitiesModule
```
so it would be "wrong" to use here `communitiesModule` directly, but using `communitiesModuleInst` is totally fine.

File: src/app_service/service/community/service.nim (hunk 1 above)
Comment (osmaczko) [reply src/app_service/service/community/service.nim:641]: I triggered this discussion on purpose. We should decide how to not block GUI thread.

According to our private chat discussion, the ideal solution would be to make status_go API async by nature. That is `importCommunity` should not block, it should be treated just as a simple command. In order to get the response, the App should be connected to `communityImported` signal and react accordingly:
```
proc importCommunity*(self: Service, communityKey: string) =
    status_go.importCommunity(communityKey)
    setCommunityIsBeingImported(communityKey) # GUI shows busy rotator/popup
...

self.events.on(SignalType.CommunityImported.event) do(e: Args):
    handleImportedCommunity(e)
...
```
Note that this approach would require changes in status_go.

Another solution would be to execute status_go calls in a separate thread:
```
proc importCommunity*(self: Service, communityKey: string) =
    status_go_wrapper.importCommunity(communityKey).then(handleImportedCommunity(response))
    setCommunityIsBeingImported(communityKey) # GUI shows busy rotator/popup
```

**Comment by saledjenic** [comment]
@anastasiyaig please check it out again, I tested it and this is how it is in my case [video](https://drive.google.com/file/d/1W2PyrmRpNEmcLLH8Gld3Mx3jwXXi7mOc/view?usp=sharing). Or share with me a community you're trying to import.

File: src/app_service/service/community/service.nim (hunk 1 above)
Comment (saledjenic) [reply src/app_service/service/community/service.nim:641]: @osmaczko yes, that's what we discussed.

**Comment by saledjenic** [comment]
@osmaczko as of making "import community" call in an async way, I've tried and spent some time to make it work, and a job was put in a queue and added to the threadpool well, as well job is executed, but calling `arg.finish` method from the thread doesn't trigger a slot added to the task, and at this moment I am not sure why. Nim doesn't give any hints, warnings, errors on that topic. 

So let's merge this and make it work as it was in the "old" master, and deal with improvements we discussed on a more global level (cause it's not only import community call suffering from the blocking UI) in another task.

**Review by anastasiyaig — APPROVED** [review]

**Review by osmaczko — APPROVED** [review]
