### PR TITLE
fix(community): community would appear even if not activated

### LINKED ISSUE #5454: User is taken to the Community channel directly after logging in
# Bug Report

## Description

User is taken to the Community channel directly after logging in. 

## Steps to reproduce

- Launch app and create a new Community and a few Community channels
- Add a couple of known contacts to this Community
- Sign Out and Quit
- Remove Data folder
- Launch app again and use the seed phrase to restore the same account

#### Expected behavior
- User must land on the Chat view

#### Actual behavior
- User is shown the Community that was created and **the Settings cog is now missing**

https://www.loom.com/share/3ca2cadec9124739968ac895ee89af6d

### Additional Information

- Status desktop version: Master : f2898b6bf75ed3aae8fc8abe641646949bf78823

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #5454

So this was a bug/feature. We never knew that if you are admin of a community, lose your data, re-import and then receive a new signal for that community, it would come back. It,s pretty cool.

However, if you have the community flag off in Advanced settings, it would appear randomly and remove the setting cog button.

Now we make sure the Communities are enabled before showing it.

### CODE REVIEW

File: src/app/modules/main/controller.nim [hunk 1]
```diff
@@ -229,12 +229,17 @@ proc getActiveSectionId*(self: Controller): string =
...
+    # Communities are not supposed to be shown
+    return
+
   self.activeSectionId = sectionId
 
   if(sectionType == SectionType.Chat or sectionType == SectionType.Community):
     # We need to take other actions here, in case of Chat or Community sections like
     # notify status go that unviewed mentions count is updated and so...
-    echo "deal with appropriate service..."
+    discard
```
Comment (jrainville) [inline src/app/modules/main/controller.nim:242]: I removed that echo because it was annoying and this `if` is more a TODO than anything

**Review by stefandunca — APPROVED** [review]

**Review by alaibe — APPROVED** [review]

**Review by endulab — APPROVED** [review]

File: src/app/modules/main/controller.nim [hunk 2]
```diff
@@ -229,12 +229,17 @@ proc getActiveSectionId*(self: Controller): string =
   result = self.activeSectionId
 
 proc setActiveSection*(self: Controller, sectionId: string, sectionType: SectionType) =
+  if sectionType == SectionType.Community and
+      not singletonInstance.localAccountSensitiveSettings.getCommunitiesEnabled():
```
Comment (osmaczko) [inline src/app/modules/main/controller.nim:233]: I am just wondering if this setting shouldn't determine backend behavior as well, that is: to not build/maintain communities data/models when disabled. If that is the case this check would not be needed here.

File: src/app/modules/main/controller.nim (hunk 1 above)
Comment (saledjenic) [reply src/app/modules/main/controller.nim:242]: @jrainville feel free to remove the entire `if` condition since it does nothing. :)

**Review by saledjenic — APPROVED** [review]

File: src/app/modules/main/controller.nim (hunk 2 above)
Comment (saledjenic) [reply src/app/modules/main/controller.nim:233]: @osmaczko you have right, we shouldn't get here if community is not enabled, so the real reason why does this proc get triggered should be somewhere else.

As I see this is called in case if someone makes a certain community active from the qml side (that should not be the case if communities are disabled, in that case they are not displayed in the app), and there are some more cases like `SIGNAL_COMMUNITY_JOINED`, `SIGNAL_COMMUNITY_CREATED`, `SIGNAL_COMMUNITY_IMPORTED`, `SIGNAL_COMMUNITY_LEFT`. In all these cases we shouldn't emit community related signals if communities are disabled.

Comment (osmaczko) [reply src/app/modules/main/controller.nim:236]: > The only downside is that if we do that, we would need to force the user to reboot the app for the changes to take effect, because we'd need to load all communities, build the UI, etc.

What if we block all signals from the service? 
Instead of:
`self.events.emit(SIGNAL_COMMUNITY_JOINED, CommunityArgs(community: community))`
we could:
`self.maybeEmit(SIGNAL_COMMUNITY_JOINED, CommunityArgs(community: community))`
where `maybeEmit` is:
```
  proc maybeEmit(self: Service, signal string, args CommunityArgs) =
    if singletonInstance.localAccountSensitiveSettings.getCommunitiesEnabled():
      self.events.emit(signal, args)
```

Please let me know what you think about this solution.
