### PR TITLE
fix(@desktop/chat): can't join to group chat by clicking [Join chat] or decline invitation with [Decline invitation]

### LINKED ISSUE #4766: Can't join to group chat by clicking [Join chat]
### Description

1. create account on mobile
2. create account on desktop
3. add each other to contacts
4. on mobile create a group chat with desktop account
5. open the group chat on desktop
6. click Join chat

Screenshot 2022-02-09 at 16 27 40

### PR DESCRIPTION
**Pull request by saledjenic**
Fixes #4766

### CODE REVIEW

File: src/app/modules/main/chat_section/chat_content/messages/module.nim [hunk 1]
```diff
@@ -383,3 +383,31 @@ method requestMoreMessages*(self: Module) =
...
 method fillGaps*(self: Module, messageId: string) =
   self.controller.fillGaps(messageId)
+
+method joinGroupChat*(self: Module) =
+  self.controller.joinGroupChat()
+
+method leaveChat*(self: Module) =
+  self.controller.leaveChat()
+
+method didIJoinedChat*(self: Module): bool =
```
Comment (jrainville) [inline src/app/modules/main/chat_section/chat_content/messages/module.nim:393]: This has an English error.
It can be changed to `haveIJoinedChat` or `isChatJoined`

File: src/app/modules/main/chat_section/chat_content/messages/module.nim [hunk 2]
```diff
@@ -383,3 +383,31 @@ method requestMoreMessages*(self: Module) =
...
+  let chatDto = self.controller.getChatDetails()
+  if(chatDto.chatType != ChatType.PrivateGroupChat):
+    return true
+
+  let myPublicKey = singletonInstance.userProfile.getPubKey()
+  for member in chatDto.members:
+    if (member.id == myPublicKey):
+      return member.joined
+  return true
```
Comment (jrainville) [inline src/app/modules/main/chat_section/chat_content/messages/module.nim:402]: Shouldn't it return `false` in case of not finding in the members?

File: src/app/modules/shared_models/message_model.nim [hunk 3]
```diff
@@ -48,6 +49,11 @@ QtObject:
     new(result, delete)
     result.setup
 
+    # This is just a clean way to have all roles in a seq, without typing long seq manualy, and this way we're sure that
+    # all new added roles will be included here as well.
+    for i in result.roleNames().keys:
+      result.allKeys.add(i)
```
Comment (jrainville) [inline src/app/modules/shared_models/message_model.nim:55]: Clean 👌

File: ui/app/AppLayouts/Chat/stores/MessageStore.qml [hunk 4]
```diff
@@ -205,4 +205,22 @@ QtObject {
...
+
+    function leaveChat() {
+         if(!messageModule)
+            return
+        messageModule.leaveChat();
+    }
+
+    function didIJoinedChat() {
+         if(!messageModule)
+            return true
```
Comment (jrainville) [inline ui/app/AppLayouts/Chat/stores/MessageStore.qml:223]: Again, maybe it should be false by default?

**Review by jrainville — COMMENTED** [review]
Good work

**Review by borismelnik — APPROVED** [review]

**Review by abhi-status — APPROVED** [review]
