### PR TITLE
fix(@desktop/profile): show ENS username in profile page if available

### LINKED ISSUE #3424: ENS username section is missing at the Profile when ENS is set
**Expected:**

image

https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/👤-Profile⎜Desktop?node-id=1818%3A13632

**Current state:**

image

### PR DESCRIPTION
**Pull request by PascalPrecht**
Closes #3424

### CODE REVIEW

File: src/app/profile/views/ens_manager.nim [hunk 1]
```diff
@@ -93,6 +93,17 @@ QtObject:
     result.pendingUsernames = initHashSet[string]()
     result.setup
 
+  proc getFirstEnsUsername(self: EnsManager): string {.slot.} =
+    if self.usernames.len > 0:
+      return self.usernames[0]
+    return ""
```
Comment (PascalPrecht) [inline src/app/profile/views/ens_manager.nim:99]: This is needed because if a user hasn't set a "preferred username" (remember accounts can have multiple ens names), we need to decide for them.

**Review by alaibe — APPROVED** [review]

**Comment by anastasiyaig** [comment]
Screenshot 2021-09-13 at 10 51 57
