### PR TITLE
fix(@desktop/walet): cpp: Enable UI to show wallet section

### LINKED ISSUE #4824: Cpp: Enable UI to show the different sections

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
fixes #4824

### What does the PR do

Enables the wallet on startup of the c++ app and list the wallet accounts

Screenshot from 2022-02-16 22-52-46

### CODE REVIEW

File: src-cpp/app/modules/shared/section_model.cpp [hunk 1]
```diff
@@ -0,0 +1,128 @@
...
+    roles[PendingRequestsToJoinModel] = "pendingRequestsToJoin";
+    return roles;
+}
+
+int SectionModel::rowCount(const QModelIndex& parent = QModelIndex()) const
+{
+    return m_items.size();
+}
+
+QVariant SectionModel::data(const QModelIndex& index, int role) const
```
[the remark this answers is not in the document]
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/shared/section_model.cpp:44]: hahahah :D I know what you mean, I don't know of code generator for these, I've always hand written these. but maybe worth a check?

File: src-cpp/app/modules/shared/section_item.cpp [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+    m_access(access),
+    m_ensOnly(ensOnly)
+{
+qDebug()<<" SECTION TYPE SET = "<< sectionType;
+}
+
+SectionType SectionItem::getSectionType()
+{
+    return m_sectionType;
+}
```
[the remark this answers is not in the document]
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/shared/section_item.cpp:54]: can you explain what you mean a bit more?

File: src-cpp/app/global/app_sections_config.h [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+
+const QString BROWSER_SECTION_ID = "browser";
+const QString BROWSER_SECTION_NAME = "Browser";
+const QString BROWSER_SECTION_ICON = "browser";
+
+const QString NODEMANAGEMENT_SECTION_ID = "nodeManagement";
+const QString NODEMANAGEMENT_SECTION_NAME = "Node Management";
+const QString NODEMANAGEMENT_SECTION_ICON = "node";
+
+const QString SETTINGS_SECTION_ID = "profileSettings";
```
[the remark this answers is not in the document]
Comment (Khushboo-dev-cpp) [reply src-cpp/app/global/app_sections_config.h:22]: I have simply taken this over from the nim code. dont want to change cause the UI is same for now, and may need these exact values when showing stuff, maybe once some implements Settings, it can be changed?

File: src-cpp/app/modules/main/module.h [hunk 4]
```diff
@@ -26,14 +27,14 @@ class Module : public QObject, virtual public IModuleAccess
     std::unique_ptr<Modules::Main::Wallet::IWalletModuleAccess> m_walletModulePtr;
 
     void connect();
+    void checkIfModuleDidLoad();
```
[the remark this answers is not in the document]
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/main/module.h:30]: interesting, let me check.

File: src-cpp/app/modules/shared/section_item.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (alaibe) [reply src-cpp/app/modules/shared/section_item.cpp:54]: Sure, I am new to cpp so what I say might be stupid but I had the impression that we can do that in cpp:
```
class A
{
public:
   readonly int x;
}
```

So instead of declaring all the get accessor they are there for us thanks to the readonly
Makes sense?

File: src-cpp/app/modules/main/module.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/main/module.h:30]: btw this would mean blocking our application at the point where we call wait, signals and slots make it properly async and its Qt functionality for async. in order to make it happen here we will anyway have to create a function call back and pass it along with the call and wait for it to be hit.

File: src-cpp/app/modules/shared/section_item.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/shared/section_item.cpp:54]: Hey no not at all, we dont have readonly in c++, we need to right getter and setters, so this is not possible.

File: src-cpp/app/modules/main/module.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (alaibe) [reply src-cpp/app/modules/main/module.h:29]: I'd say that currently everything is blocking so it would still be a step forward! but you are right. when calling await, that will block the app and using a callback might works

Another solution is that load function return a sequence of future. That way we only block the app once. not sure if it is legit to block when everything is loading.

File: src-cpp/app/modules/shared/section_item.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (alaibe) [reply src-cpp/app/modules/shared/section_item.cpp:53]: Alright then!

File: src-cpp/app/modules/main/module.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/main/module.h:29]: yes, I think when load things should not be blocked, but once everything is ready in its own time it updates and we know its all loaded. Currently its not all blocked, with signals and slots we achieve the c++'s function callback

File: src-cpp/app/modules/shared/section_model.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (richard-ramos) [reply src-cpp/app/modules/shared/section_model.cpp:44]: Maybe https://github.com/Cavewhere/lib-qt-qml-tricks/ QQmlObjectListModel? we could use this and the `QML_******_PROPERTY` to define the QObject properties without having to manually create getters/setters. See an example [here](https://github.com/Cavewhere/lib-qt-qml-tricks/tree/727d2dd8716f6c019f92d10c797ed70d7aee1495/examples/NiceModels)

File: src-cpp/app/modules/main/module.cpp [hunk 5]
```diff
@@ -33,6 +37,11 @@ void Module::load()
     m_controllerPtr->init();
     m_viewPtr->load();
 
+    // Add Wallet Section to Sections model
+    auto walletSectionItem = new SectionItem(WALLET_SECTION_ID, SectionType::Wallet, WALLET_SECTION_NAME, "", "", WALLET_SECTION_ICON, "", false);
```
Comment (richard-ramos) [inline src-cpp/app/modules/main/module.cpp:41]: Should we use `make_unique` instead of `new` to not use raw pointers? If not, is it possible we could be running into a memory leak here due to not deleting the walletSectionItem later? (which I think should happen if we logout)

Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/main/module.cpp:41]: yes that's a miss from me!! will fix  thanks for pointing it out

File: src-cpp/app/modules/shared/section_model.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/shared/section_model.cpp:44]: heee I dont really like this. I feel its abstracts too much, maybe I am not used to it. I think its good the way it, we are only trying to find a way to remove implementing getter right, this brings in a lot more than that

File: src-cpp/app/modules/main/view.cpp [hunk 6]
```diff
@@ -15,5 +16,27 @@ void View::load()
...
+void View::addItem(Shared::Models::SectionItem* item)
+{
+    m_sectionModel.addItem(item);
+    emit sectionsModelChanged();
+}
+
+SectionModel* View::getSectionsModel()
+{
+    return &m_sectionModel;
+}
```
Comment (borismelnik) [inline src-cpp/app/modules/main/view.cpp:28]: Wow... what if i do `delete getSectionsModel()`?

File: src-cpp/app/modules/main/view.cpp [hunk 7]
```diff
@@ -15,5 +16,27 @@ void View::load()
...
+
+SectionItem* View::getActiveSection()
+{
+    return m_sectionModel.getActiveItem();
+}
+
+void View::setActiveSection(QString Id)
+{
+    m_sectionModel.setActiveSection(Id);
+    activeSectionChanged();
```
Comment (borismelnik) [inline src-cpp/app/modules/main/view.cpp:38]: `QString id` should be `const QString& id`

Comment (borismelnik) [reply src-cpp/app/modules/main/view.cpp:38]: and i think we should check equal before emit some signals to avoid useless calls.

File: src-cpp/app/modules/main/module.cpp (hunk 5 above)
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/main/module.cpp:41]: Done! please do check , awaiting approvals @richard-ramos , @alaibe

File: src-cpp/app/modules/shared/section_item.h [hunk 8]
```diff
@@ -0,0 +1,118 @@
...
+    Chat = 0,
+    Community,
+    Wallet,
+    Browser,
+    ProfileSettings,
+    NodeManagement
+};
+class SectionItem: public QObject
+{
+    Q_OBJECT
```
Comment (borismelnik) [inline src-cpp/app/modules/shared/section_item.h:22]: This can be a `Q_GADGET`?

File: src-cpp/app/modules/shared/section_item.h [hunk 9]
```diff
@@ -0,0 +1,118 @@
...
+    Q_PROPERTY(QString description READ getDescription)
+    Q_PROPERTY(QString image READ getImage)
+    Q_PROPERTY(QString icon READ getIcon)
+    Q_PROPERTY(QString color READ getColor)
+    Q_PROPERTY(bool hasNotification READ getHasNotification)
+    Q_PROPERTY(int notificationsCount READ getNotificationsCount)
+    Q_PROPERTY(bool active READ getIsActive NOTIFY activeChanged)
+    Q_PROPERTY(bool enabled READ getIsEnabled)
+    Q_PROPERTY(bool joined READ getHasJoined)
+    Q_PROPERTY(bool isMember READ getIsMember)
```
Comment (borismelnik) [inline src-cpp/app/modules/shared/section_item.h:36]: if you use `non-notify` properties you can use `member` in `Q_PROPERTY`

File: src-cpp/app/modules/shared/section_model.cpp [hunk 10]
```diff
@@ -0,0 +1,128 @@
+#include "section_model.h"
+
+namespace Shared
+{
+namespace Models
+{
```
Comment (borismelnik) [inline src-cpp/app/modules/shared/section_model.cpp:6]: if we can use `c++17` we can do `namespace Shared::Models {`

File: src-cpp/app/modules/shared/section_model.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (borismelnik) [reply src-cpp/app/modules/shared/section_model.cpp:44]: @alaibe it's a QAbstractItemModel interface which used inside Qt views for some optimisations.

File: src-cpp/app/modules/shared/section_model.h [hunk 11]
```diff
@@ -0,0 +1,64 @@
...
+        MembersModel,
+        PendingRequestsToJoinModel
+    };
+
+    explicit SectionModel(QObject* parent = nullptr);
+    ~SectionModel() = default;
+
+    QHash<int, QByteArray> roleNames() const;
+    virtual int rowCount(const QModelIndex&) const;
+    virtual QVariant data(const QModelIndex& index, int role) const;
```
Comment (borismelnik) [inline src-cpp/app/modules/shared/section_model.h:49]: Why this methods is `virtual` if you `override` it?

**Review by borismelnik — CHANGES_REQUESTED** [review]

File: src-cpp/app/modules/main/module.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (borismelnik) [reply src-cpp/app/modules/main/module.h:29]: No reasons to make it `async`.

[the remark this answers is not in the document]
Comment (borismelnik) [reply src-cpp/app/modules/main/module.h:29]: @Khushboo-dev-cpp Qt has synchronisation between threads by `Qt::ConnectionType`. But direct call like `.` or `->` never call it in another thread.

File: src-cpp/app/modules/main/module.cpp (hunk 5 above)
Comment (borismelnik) [reply src-cpp/app/modules/main/module.cpp:41]: @richard-ramos are you sure about `unique` here?

File: src-cpp/app/modules/main/view.cpp (hunk 6 above)
Comment (borismelnik) [reply src-cpp/app/modules/main/view.cpp:28]: and what happens if view removed, but someone has a pointer?

File: src-cpp/app/modules/main/module.cpp (hunk 5 above)
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/main/module.cpp:41]: hey @borismelnik Iv passed it as a shared_ptr now. directly in the view.

File: src-cpp/app/modules/main/view.cpp (hunk 7 above)
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/main/view.cpp:38]: Agreed! will improve :)

File: src-cpp/app/modules/shared/section_item.h (hunk 9 above)
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/shared/section_item.h:36]: aaah I just read that just now, thanks for pointing it out, however do you know how do I make it read only?
Q_PROPERTY(bool enabled MEMBER m_isEnabled), this would mean read and write both right?

File: src-cpp/app/modules/shared/section_model.cpp (hunk 10 above)
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/shared/section_model.cpp:6]: Damn I forgot about this awesome thing :) thanks will use it

File: src-cpp/app/modules/shared/section_model.h (hunk 11 above)
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/shared/section_model.h:49]: missed removing them, will remove :)

File: src-cpp/app/modules/shared/section_item.h (hunk 9 above)
Comment (borismelnik) [reply src-cpp/app/modules/shared/section_item.h:36]: but that properties never changed?

File: src-cpp/app/global/app_sections_config.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (borismelnik) [reply src-cpp/app/global/app_sections_config.h:22]: do you know that every include should create personal instance of every each object here? it's a C++ you can use enum for it.

File: src-cpp/app/modules/main/module.cpp [hunk 12]
```diff
@@ -4,6 +4,10 @@
 #include "module.h"
 #include "singleton.h"
 #include "modules/main/wallet/module.h"
+#include "../shared/section_item.h"
+#include "../global/app_sections_config.h"
+
+using namespace Shared::Models;
```
Comment (borismelnik) [inline src-cpp/app/modules/main/module.cpp:10]: thats bad. use it locally or never pls :)

File: src-cpp/app/modules/shared/section_item.h (hunk 9 above)
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/shared/section_item.h:36]: what do you mean?
if I pass Q_PROPERTY(bool enabled MEMBER m_isEnabled), someone on the QML side, using it could also assign values to this m_isEnabled right? and we dont want that

File: src-cpp/app/modules/main/view.cpp [hunk 13]
```diff
@@ -1,10 +1,11 @@
 #include "view.h"
 
+using namespace Shared::Models;
```
Comment (borismelnik) [inline src-cpp/app/modules/main/view.cpp:3]: the same as above. No reasons to use namespaces without usage :)

File: src-cpp/app/modules/main/view.cpp (hunk 6 above)
Comment (borismelnik) [reply src-cpp/app/modules/main/view.cpp:28]: if view is owner - create it like `m_sectionModel = new SectionModel(view)` without smart pointers.

File: src-cpp/app/modules/shared/section_item.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (borismelnik) [reply src-cpp/app/modules/shared/section_item.cpp:53]: that is not true :) first one:
```
class Test {
public:
    Test(int p): m_p(p) {}
private:
    const int m_p;
};
```

File: src-cpp/app/modules/shared/section_model.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (alaibe) [reply src-cpp/app/modules/shared/section_model.cpp:44]: @richard-ramos tbh it is quite good, it made me think of the macro we did in backend. Even if we don t import this specific lib, maybe at some point we will write abstraction based on our need. At least it is good to know it is doable

File: src-cpp/app/modules/shared/section_item.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (borismelnik) [reply src-cpp/app/modules/shared/section_item.cpp:53]: and second:
```
SectionType SectionItem::getSectionType() const
{
    return m_sectionType;
}
```

**Review by alaibe — APPROVED** [review]

File: src-cpp/app/modules/shared/section_item.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/shared/section_item.cpp:53]: Hey what @alaibe mentioned was a readonly property without having the need to write getters, which means in the example you mentioned ->
```
class Test {
public:
    Test(int p): m_p(p) {}:
    const int m_p;
};
````
the m_p basically is public and not desirable and vulnerable ?

**Review by anastasiyaig — APPROVED** [review]

File: src-cpp/app/global/app_sections_config.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (Khushboo-dev-cpp) [reply src-cpp/app/global/app_sections_config.h:22]: Will add a to-do to improve this for however works on this later for now, I only want to bring up Wallet as of now.

File: src-cpp/app/modules/shared/section_item.h (hunk 8 above)
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/shared/section_item.h:22]: can use it cause I have NOTIFY for one of the Q_PROPERTY?

File: src-cpp/app/boot/app_controller.cpp [hunk 14]
```diff
@@ -111,7 +110,7 @@ void AppController::connect()
     // self.statusFoundation.status.events.once("nodeStopped") do(a: Args):
     // TODO: remove this once accounts are not tracked in the AccountsModel
     // self.statusFoundation.status.reset()
-    QObject::connect(dynamic_cast<QObject*>(m_mainModulePtr.get()), SIGNAL(loaded()), this, SLOT(mainDidLoad()));
+    QObject::connect(dynamic_cast<QObject*>(m_mainModulePtr), SIGNAL(loaded()), this, SLOT(mainDidLoad()));
```
[the remark this answers is not in the document]
Comment (borismelnik) [reply src-cpp/app/boot/app_controller.cpp:113]: and pls use new form:
`QObject::connect(m_mainModulePtr, &Modules::Main::Module::loaded, this, &AppController:;mainDidLoad);`

File: src-cpp/app/boot/app_controller.h [hunk 15]
```diff
@@ -29,7 +29,7 @@ class AppController : public QObject, AppControllerDelegate
     // Modules
     // To-Do make this a shared pointer and remove circular dependency.
     Modules::Startup::ModuleAccessInterface* m_startupModule;
-    std::unique_ptr<Modules::Main::IModuleAccess> m_mainModulePtr;
+    Modules::Main::IModuleAccess* m_mainModulePtr;
```
Comment (borismelnik) [inline src-cpp/app/boot/app_controller.h:32]: minor: `m_mainModule` cos its not smart pointer anymore

File: src-cpp/app/modules/main/module.cpp [hunk 16]
```diff
@@ -4,35 +4,33 @@
...
     m_moduleLoaded = false;
     connect();
 }
 
 void Module::connect()
 {
-    QObject::connect(m_viewPtr.get(), &View::viewLoaded, this, &Module::viewDidLoad);
-    QObject::connect(dynamic_cast<QObject*>(m_walletModulePtr.get()), SIGNAL(loaded()), this, SLOT(walletDidLoad()));
+    QObject::connect(m_viewPtr, &View::viewLoaded, this, &Module::viewDidLoad);
+    QObject::connect(dynamic_cast<QObject*>(m_walletModulePtr), SIGNAL(loaded()), this, SLOT(walletDidLoad()));
```
Comment (borismelnik) [inline src-cpp/app/modules/main/module.cpp:26]: the same as above

File: src-cpp/app/modules/main/module.cpp [hunk 17]
```diff
@@ -4,35 +4,33 @@
...
 }
 
 void Module::load()
 {
-    Global::Singleton::instance()->engine()->rootContext()->setContextProperty("mainModule", m_viewPtr.get());
+    Global::Singleton::instance()->engine()->rootContext()->setContextProperty("mainModule", m_viewPtr);
```
Comment (borismelnik) [inline src-cpp/app/modules/main/module.cpp:31]: if its yours - maybe make sense add method `Global::Singleton::instance()->setQmlContextProperty(...)`

File: src-cpp/app/modules/main/wallet/accounts/controller.h [hunk 18]
```diff
@@ -8,15 +8,9 @@
...
+namespace Modules::Main::Wallet::Accounts
 {
-namespace Main
-{
-namespace Wallet
-{
-namespace Accounts
-{
-class Controller : public QObject, IAccountsController
+class Controller : public QObject, IController
```
Comment (borismelnik) [inline src-cpp/app/modules/main/wallet/accounts/controller.h:13]: which type of inheritance for `IController`? private?

File: src-cpp/app/modules/main/wallet/accounts/model.h [hunk 19]
```diff
@@ -38,18 +31,14 @@ class Model : public QAbstractListModel
     explicit Model(QObject* parent = nullptr);
     ~Model() = default;
 
-    QHash<int, QByteArray> roleNames() const;
-    virtual int rowCount(const QModelIndex&) const;
-    virtual QVariant data(const QModelIndex& index, int role) const;
+    QHash<int, QByteArray> roleNames() const override;
+    int rowCount(const QModelIndex&) const override;
+    QVariant data(const QModelIndex& index, int role) const override;
```
Comment (borismelnik) [inline src-cpp/app/modules/main/wallet/accounts/model.h:36]: minor: are you sure its not `final`?

File: src-cpp/app/modules/main/wallet/module.cpp [hunk 20]
```diff
@@ -5,33 +5,29 @@
...
     m_moduleLoaded = false;
     connect();
 }
 
 void Module::connect()
 {
-    QObject::connect(m_viewPtr.get(), SIGNAL(viewLoaded()), this, SLOT(viewDidLoad()));
-    QObject::connect(dynamic_cast<QObject*>(m_accountsModulePtr.get()), SIGNAL(loaded()), this, SLOT(accountsDidLoad()));
+    QObject::connect(m_viewPtr, SIGNAL(viewLoaded()), this, SLOT(viewDidLoad()));
+    QObject::connect(dynamic_cast<QObject*>(m_accountsModulePtr), SIGNAL(loaded()), this, SLOT(accountsDidLoad()));
```
Comment (borismelnik) [inline src-cpp/app/modules/main/wallet/module.cpp:25]: the same as above

File: src-cpp/app/modules/shared/section_item.cpp [hunk 21]
```diff
@@ -0,0 +1,154 @@
...
+
+namespace Shared::Models
+{
+SectionItem::SectionItem(QString id,
+                         SectionType sectionType,
+                         QString name,
+                         QString description,
+                         QString image,
+                         QString icon,
+                         QString color,
```
Comment (borismelnik) [inline src-cpp/app/modules/shared/section_item.cpp:13]: should be `const QString&`

File: src-cpp/app/modules/shared/section_item.cpp [hunk 22]
```diff
@@ -0,0 +1,154 @@
...
+{
+    return m_sectionType;
+}
+
+QString SectionItem::getId()
+{
+    return m_id;
+}
+
+QString SectionItem::getName()
```
Comment (borismelnik) [inline src-cpp/app/modules/shared/section_item.cpp:60]: in whole file it should be `const QString&`

Comment (borismelnik) [reply src-cpp/app/modules/shared/section_item.cpp:60]: every each getter should be `const`

File: src-cpp/app/modules/shared/section_model.cpp [hunk 23]
```diff
@@ -0,0 +1,124 @@
...
+}
+
+QVariant SectionModel::data(const QModelIndex& index, int role) const
+{
+    if(!index.isValid())
+    {
+        return QVariant();
+    }
+
+    if(index.row() < 0 || index.row() > m_items.size())
```
Comment (borismelnik) [inline src-cpp/app/modules/shared/section_model.cpp:49]: `index.row() >= m_items.size()` cos `m_items.at(m_items.size())` is out of range

File: src-cpp/app/modules/shared/section_model.cpp [hunk 24]
```diff
@@ -0,0 +1,124 @@
...
+
+    for (int i = 0; i < m_items.size(); ++i) {
+        auto newIndex = createIndex(i, 0, nullptr);
+        if(m_items[i]->getIsActive())
+        {
+            m_items[i]->setIsActive(false);
+            dataChanged(newIndex, newIndex, QVector<int>(ModelRole::Active));
+
+        }
+        if (m_items[i]->getId() == Id)
```
Comment (borismelnik) [inline src-cpp/app/modules/shared/section_model.cpp:103]: y'know what happens here?
Every each Qt container is `Copy-to-write` but `operator[]` has a non-const version. So here m_items can be copied every time when `m_items[i]` called.  Use `.at` for access to elements.

File: src-cpp/app/modules/shared/section_model.cpp [hunk 25]
```diff
@@ -0,0 +1,124 @@
...
+        {
+            m_items[i]->setIsActive(true);
```
Comment (borismelnik) [inline src-cpp/app/modules/shared/section_model.cpp:105]: here the same as above. So we can have a double copy here.

**Review by borismelnik — CHANGES_REQUESTED** [review]
Still need some improvements, sorry :(

File: src-cpp/app/boot/app_controller.cpp (hunk 14 above)
[the remark this answers is not in the document]
Comment (Khushboo-dev-cpp) [reply src-cpp/app/boot/app_controller.cpp:113]: Hey I need to cast as the interface which is exposed is not Object and I cannot use this new format of connect for this approach . that's why it needs to be like this, I will use qoject_cast thought

File: src-cpp/app/boot/app_controller.h (hunk 15 above)
Comment (Khushboo-dev-cpp) [reply src-cpp/app/boot/app_controller.h:32]: but it is still a pointer?

File: src-cpp/app/boot/app_controller.cpp (hunk 14 above)
[the remark this answers is not in the document]
Comment (Khushboo-dev-cpp) [reply src-cpp/app/boot/app_controller.cpp:113]: Also inserting the IModuleAccess is not a good idea, leads to ambiguous inheritance from QObject later on

File: src-cpp/app/modules/main/module.cpp (hunk 16 above)
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/main/module.cpp:26]: won't work as IModuleAccess does not inherit from QObject

File: src-cpp/app/modules/main/module.cpp (hunk 17 above)
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/main/module.cpp:31]: what do you mean by if it is yours? we would could use setQmlContextProperty though as it is only used in qml? if that's what you mean?

File: src-cpp/app/modules/main/wallet/accounts/model.h (hunk 19 above)
Comment (Khushboo-dev-cpp) [reply src-cpp/app/modules/main/wallet/accounts/model.h:36]: I think we can keep it as override, final makes sure no one else is able ton inherit form this class further
/

**Comment by Khushboo-dev-cpp** [comment]
Fixed all except for our the signal declared in Interface file, until we find a solution together, request you to please approve @borismelnik :)
And maybe either I take care of it in my subsequent task or we can create another task for me to improve this.

File: src-cpp/app/boot/app_controller.h (hunk 15 above)
Comment (borismelnik) [reply src-cpp/app/boot/app_controller.h:32]: it's convention for smart pointers - add `Ptr` to the end

**Review by borismelnik — APPROVED** [review]
