### PR TITLE
fix(browser-provider): fix browser provider not asking for authorization

### LINKED ISSUE #4721: Authorizing Dapps is broken in the browser
Opening a Dapp no longer gives the authorize popup

```
js: Invalid asm.js: Unexpected token
Ignoring additional arguments while invoking method "postMessage" on object WebProviderObj_QMLTYPE_363(0x55f46e326730) : 2 arguments given, but method only takes 1 .
qml: Error parsing the message data SyntaxError: JSON.parse: Parse error
js: Uncaught (in promise) Error: Provider not set or invalid
DBG 2022-02-03 11:30:01.685-05:00 NewBE_callPrivateRPC                       topics="rpc" tid=36890 file=core.nim:24 rpc_method=eth_call
DBG 2022-02-03 11:30:01.710-05:00 NewBE_callPrivateRPC                       topics="rpc" tid=36890 file=core.nim:24 rpc_method=eth_call
Ignoring additional arguments while invoking method "postMessage" on object WebProviderObj_QMLTYPE_363(0x55f46e326730) : 2 arguments given, but method only takes 1 .
qml: Error parsing the message data SyntaxError: JSON.parse: Parse error
Ignoring additional arguments while invoking method "postMessage" on object WebProviderObj_QMLTYPE_363(0x55f46e326730) : 2 arguments given, but method only takes 1 .
qml: Error parsing the message data SyntaxError: JSON.parse: Parse error
Ignoring additional arguments while invoking method "postMessage" on object WebProviderObj_QMLTYPE_363(0x55f46e326730) : 2 arguments given, but method only takes 1 .
qml: Error parsing the message data SyntaxError: JSON.parse: Parse error
Ignoring additional arguments while invoking method "postMessage" on object WebProviderObj_QMLTYPE_363(0x55f46e326730) : 2 arguments given, but method only takes 1 .
qml: Error parsing the message data SyntaxError: JSON.parse: Parse error
Ignoring additional arguments while invoking method "postMessage" on object WebProviderObj_QMLTYPE_363(0x55f46e326730) : 2 arguments given, but method only takes 1 .
qml: Error parsing the message data SyntaxError: JSON.parse: Parse error
Ignoring additional arguments while invoking method "postMessage" on object WebProviderObj_QMLTYPE_363(0x55f46e326730) : 2 arguments given, but method only takes 1 .
qml: Error parsing the message data SyntaxError: JSON.parse: Parse error
Ignoring additional arguments while invoking method "postMessage" on object WebProviderObj_QMLTYPE_363(0x55f46e326730) : 2 arguments given, but method only takes 1 .
qml: Error parsing the message data SyntaxError: JSON.parse: Parse error
Ignoring additional arguments while invoking method "postMessage" on object WebProviderObj_QMLTYPE_363(0x55f46e326730) : 2 arguments given, but method only takes 1 .
qml: Error parsing the message data SyntaxError: JSON.parse: Parse error
```

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #4721

This was hard to debug, because it hapended with the merge/clash of master and base_bc.

Basically, both master and base_bc sent the provider calls correctly, but when they merged, they both had small mistakes that compounded in each other, making it totally explode.
Also, tracking bugs with the provider is hard.

Anyway, the issue was that we passed 1 parameter at one place, and two at an other, so the call ended up not working. Also, I hit the "No implementation available" issue, but again, I didn't have that message, it just crashed.

### CODE REVIEW

File: src/app_service/service/provider/service.nim [hunk 1]
```diff
@@ -289,11 +289,11 @@ proc process(self: Service, data: APIRequest): string =
     "data": value
   }
 
-method postMessage*(self: Service, message: string): string =
-  case message.requestType():
-  of RequestTypes.Web3SendAsyncReadOnly: self.process(message.toWeb3SendAsyncReadOnly())
-  of RequestTypes.HistoryStateChanged: """{"type":"TODO-IMPLEMENT-THIS"}""" ############# TODO:
-  of RequestTypes.APIRequest: self.process(message.toAPIRequest())
+method postMessage*(self: Service, requestType: string, message: string): string =
```
Comment (saledjenic) [inline src/app_service/service/provider/service.nim:292]: @jrainville isn't easier to have here `RequestTypes` as a type of `requestType` param, than `string?`

**Review by saledjenic — APPROVED** [review]
@jrainville it works fine, approved.

File: src/app_service/service/provider/service.nim (hunk 1 above)
Comment (jrainville) [reply src/app_service/service/provider/service.nim]: Updated

**Review by abhi-status — APPROVED** [review]
