### PR TITLE
fix(@desktop/wallet): send transaction to address UI is broken

### LINKED ISSUE #4623: [base_bc] send transaction to address UI is broken
### Description

Screenshot 2022-01-28 at 16 05 17

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
fixes #4623

### What does the PR do

This fixes the issue that when wallet address is added to send modal, an incorrect contact information is not displayed.

### Affected areas

Wallet

### Screenshot of functionality
Screenshot 2022-02-01 at 7 03 53 PM

Screenshot 2022-02-01 at 7 04 46 PM

### CODE REVIEW

**Review by alaibe — COMMENTED** [review]
Can you terminate the flow? It looks like Continue stays grey

**Comment by jrainville** [comment]
FYI, I'm working on making the Send transaction flow work in my own branch

**Comment by Khushboo-dev-cpp** [comment]
> Can you terminate the flow? It looks like Continue stays grey

Hey what do you mean by this @alaibe

**Comment by Khushboo-dev-cpp** [comment]
> FYI, I'm working on making the Send transaction flow work in my own branch

hey thanks for letting me know, does the in anyway overlap with what you are doing? https://app.zenhub.com/workspaces/status-desktop-5ea70d29c12ee928df5ae848/issues/status-im/status-desktop/4610

File: src/app_service/service/contacts/async_tasks.nim [hunk 1]
```diff
@@ -21,6 +21,8 @@ const lookupContactTask: Task = proc(argEncoded: string) {.gcsafe, nimcall.} =
     # TODO refactor those calls to use the new backend and also do it in a signle call
     pubkey = ens_utils.pubkey(arg.value)
     address = ens_utils.address(arg.value)
+  else:
+    pubkey = ""
```
Comment (saledjenic) [inline src/app_service/service/contacts/async_tasks.nim:25]: @Khushboo-dev-cpp just because of consistency and to be sure, would be good to add `address = ""` as well in this else block.

**Review by saledjenic — APPROVED** [review]
@Khushboo-dev-cpp nice find, approved.

**Review by alaibe — APPROVED** [review]
As Jo is making it work

File: src/app_service/service/contacts/async_tasks.nim (hunk 1 above)
Comment (Khushboo-dev-cpp) [reply src/app_service/service/contacts/async_tasks.nim:25]: Sure :)

**Review by anastasiyaig — APPROVED** [review]
