### PR TITLE
fix(@desktop/permissions): Fix displaying tokens in permissions

### LINKED ISSUE #13773: Required permissions in join community flow are not displayed
# Bug Report

## Description

When joining token gated community, the required permission is not displayed

## Steps to reproduce

- Try to join a community that is token-gated

#### Expected behavior

- The permission required should be visible. Something like this:

Screenshot 2024-02-28 at 16 42 31

- And in share addresses user should see also the permissions like this:

Screenshot 2024-02-28 at 16 43 03

#### Actual behavior

image

AND

Screenshot 2024-02-28 at 16 36 15

### Additional Information

- Status desktop version: **2.27.0-rc5**
- Operating System: _macos_

### PR DESCRIPTION
**Pull request by endulab**
The model with tokens should be updated also when we import community data.

Fix #13773

https://github.com/status-im/status-desktop/assets/61889657/18346d58-1e7c-41fc-81ea-fb7ca9324d30

### CODE REVIEW

File: src/app/modules/main/communities/module.nim [hunk 1]
```diff
@@ -95,7 +95,8 @@ type
 method setCommunityTags*(self: Module, communityTags: string)
 method setAllCommunities*(self: Module, communities: seq[CommunityDto])
 method setCuratedCommunities*(self: Module, curatedCommunities: seq[CommunityDto])
-proc buildTokensAndCollectiblesFromCommunities(self: Module)
+proc buildTokensAndCollectiblesFromAllCommunities(self: Module)
```
Comment (noeliaSD) [inline src/app/modules/main/communities/module.nim:98]: Maybe it would be nice a comment here to better understand the difference between `Communities` and `AllCommunities`! ;)

**Review by noeliaSD — APPROVED** [review]
Just a small comment! Otherwise, LGTM!

**Review by jrainville — APPROVED** [review]
