### PR TITLE
fix(token-order): global has settings check that introduced side effects

### LINKED ISSUE #14383: Token Management: Create custom order is missing from the app
# Bug Report

## Description

When the user has not created any custom order the app should show an option to create custom order in the sorting menu. Currently it always shows "Custom order" as if it was already created.

## Steps to reproduce

1. Create a fresh account
2. Log in
3. Go to wallet
4. Open the sorting menu

#### Expected behavior
There is an option "Create custom order"
#### Actual behavior
"Custom order" and "Edit custom order" is shown instead
### Additional Information

https://github.com/status-im/status-desktop/assets/52439419/00588346-a311-4e28-9ec0-dea72911419c

- Status desktop version: master
- Operating System: macOS

### PR DESCRIPTION
**Pull request by stefandunca**
### Closes #14383
    
The "settings exist" done via `ManageTokensController::hasSettings()` was using the global store, hence not working user based. Therefore, after an onboarding the previous user's settings presence was taken into account.

The fix now uses the order data that is loaded externally per user.

`HEAD~1` also  fixes an annoying warning that was distracting from debugging

### CODE REVIEW

File: ui/StatusQ/src/wallet/managetokenscontroller.cpp [hunk 1]
```diff
@@ -276,9 +276,7 @@ QString ManageTokensController::settingsGroupName() const
 
 bool ManageTokensController::hasSettings() const
 {
-    Q_ASSERT(!m_settingsKey.isEmpty());
-    const auto groups = m_settings.childGroups();
-    return groups.contains(settingsGroupName());
+    return m_settingsData.size() > 0;
```
Comment (caybro) [inline ui/StatusQ/src/wallet/managetokenscontroller.cpp:279]:
```suggestion
    return !m_settingsData.isEmpty();
```

Comment (caybro) [reply ui/StatusQ/src/wallet/managetokenscontroller.cpp:279]: You don't need to count them all :)

**Review by caybro — APPROVED** [review]
LGTM

With a small improvement hint

File: ui/StatusQ/src/wallet/managetokenscontroller.cpp (hunk 1 above)
Comment (caybro) [reply ui/StatusQ/src/wallet/managetokenscontroller.cpp]: Haha, forgot it's a `QHash`, so there's no difference :)

There would be though in case of a `QList`:
```cpp
inline bool isEmpty() const noexcept { return d->end  == d->begin; }
```
