### PR TITLE
fix(@general): keystore management

### LINKED ISSUE #5390: Import same account from 2 different status account
Create account A: import mnemonic for account B
Create account C: import mnemonic for account B

image

### PR DESCRIPTION
**Pull request by alaibe**
fixes #5390

Keystore file needs to be store per account and not globally to avoid conflict. We will then use same as mobile:
current_keystore / key uid of the account

status-go: https://github.com/status-im/status-go/pull/2664

### CODE REVIEW

File: src/app_service/service/accounts/service.nim [hunk 1]
```diff
@@ -46,6 +49,53 @@ proc getImportedAccount*(self: Service): GeneratedAccountDto =
...
 
+# Remove extra copied keystore that are not needed (can be remove 1st jan 2023)
+proc deleteExtraKeyStoreFile*(self: Service) =
+  let accounts = status_account.getAccounts().result
+  var deleteCandidates: seq[string] = @[]
+  for path in walkFiles(self.keyStoreDir & "*"):
+    var found = false
+    for account in accounts.getElems():
+      let address = account{"address"}.getStr.replace("0x", "")
+      if path.endsWith(address):
```
Comment (saledjenic) [inline src/app_service/service/accounts/service.nim:60]: @alaibe are the files under the `keyStoreDir` always without extension on all platforms? I checked on mac, and they are, but not sure about windows and linux, if so than all good, if not maybe `contains` would be better than `endsWith`.

File: src/app_service/service/accounts/service.nim [hunk 2]
```diff
@@ -46,6 +49,53 @@ proc getImportedAccount*(self: Service): GeneratedAccountDto =
...
+        found = true
+        break
+
+    if not found:
+      deleteCandidates.add(path)
+
+  if len(deleteCandidates) == 2:
+    return
```
Comment (saledjenic) [inline src/app_service/service/accounts/service.nim:68]: @alaibe just curious... why do we return here of there are only 2 delete candidates?

**Review by saledjenic — CHANGES_REQUESTED** [review]
@alaibe code looks ok. I checked out this branch and built it and deleted `Status` folder, when I was about to finalize new account creation I am got this error `error:                                     topics="accounts-service" tid=26512483 file=service.nim:193 procName=saveAccountAndLogin errName=KeyError errDesription="key not found: colorHash"` and wasn't able to test changes, does that happen to you?

File: src/app_service/service/accounts/service.nim (hunk 1 above)
Comment (alaibe) [reply src/app_service/service/accounts/service.nim:60]: On linux too they are, good point about Windows (i think they are too). Jo will also test the PR he can confirm or not?

File: src/app_service/service/accounts/service.nim (hunk 2 above)
Comment (alaibe) [reply src/app_service/service/accounts/service.nim:68]: I will add a comment to make it clear, this is in case you never imported any account in the wallet, there would be 4 files in the keystore, 2 of them will be considered orphan, but we should keep them. This is why the 2

**Comment by alaibe** [comment]
@saledjenic PR has been updated, thanks

**Comment by anastasiyaig** [comment]
I tested it as extensively as i could and it looks just fine. 
https://ethstatus.testrail.net/index.php?/runs/view/8999

**Review by anastasiyaig — APPROVED** [review]

**Comment by jrainville** [comment]
@alaibe I tested this PR to see if it fixed the "can't change password" issue and I can confirm that it works now. Good job! https://github.com/status-im/status-desktop/issues/5351

**Review by borismelnik — APPROVED** [review]

**Review by richard-ramos — APPROVED** [review]
