### PR TITLE
fix(@activity_center): fix dup messages

### LINKED ISSUE #4631: [base_bc] Activity Centre shows duplicated activities
# Bug Report

## Description

Every time there is an activity (with replies and mentions) in a channel, the Activity Centre shows duplicated entries for both Mentions & Replies.
After a sign out and sign back in, the Activity Centre shows the correct entries with no duplicates.

## Steps to reproduce

- Create a channel and add a contact to the community
- Using another app instance or the phone app, post some messages in the channel
- Include replies and mentions in the chat
- Open Activity Centre

#### Expected behavior
The Activity Centre must show the correct activities with no duplication.

#### Actual behavior
https://www.loom.com/share/1047d4c32b6f4b968ff4206ff84d1d62

### Additional Information

- Status desktop version: base_bc - commit : 839347e769e0257d2471f9f22d3ba1b585387867

### PR DESCRIPTION
**Pull request by alaibe**
fixes #4631

Only keep event from the services related to AC

### CODE REVIEW

File: src/app/modules/main/activity_center/controller.nim [hunk 1]
```diff
@@ -38,14 +36,9 @@ method delete*[T](self: Controller[T]) =
   discard
 
 method init*[T](self: Controller[T]) =
-  self.events.on(SIGNAL_ACTIVITY_CENTER_NOTIFICATIONS_LOADED) do(e: Args):
+  self.events.on(activity_center_service.SIGNAL_ACTIVITY_CENTER_NOTIFICATIONS_LOADED) do(e: Args):
     let args = ActivityCenterNotificationsArgs(e)
-    self.delegate.pushActivityCenterNotifications(args.activityCenterNotifications)
-
-  self.events.on(chat_service.SIGNAL_CHAT_UPDATE) do(e: Args):
```
Comment (alaibe) [inline src/app/modules/main/activity_center/controller.nim:45]: @jrainville I am not sure this one was relevant, indeed we are now using the service to handle event. Could you confirm? I am also not seeing any activityCenterNotifications added in SIGNAL_CHAT_UPDATE

**Review by richard-ramos — APPROVED** [review]

**Comment by alaibe** [comment]
@jrainville @anastasiyaig ping ;)

**Review by anastasiyaig — APPROVED** [review]
