### PR TITLE
fix(@desktop/profile): Custom picture is not applied everywhere in the app without restart

### LINKED ISSUE #4099: [refactoring/base_02] Custom picture is not applied everywhere in the app without restart
# Bug Report

## Description

Custom picture is not applied everywhere in the app

## Steps to reproduce

1. open profile
2. edit picture and set is any custom picture
3. check online identifier 

#### Expected behavior

custom profile pic is applied across the app

#### Actual behavior

Screenshot 2021-11-11 at 20 35 48

### Additional Information

- Status desktop version: r`efactoring_base02` branch, commit https://github.com/status-im/status-desktop/commit/224cb706623c84e3573010c41d435bdea19ffa19
- Operating System: masOS Big Sur

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
fix(@desktop/profile): Custom picture is not applied everywhere in the app without restart

fixes #4099

### What does the PR do### Affected areas

Profile and NavBar

### Screenshot of functionality

https://user-images.githubusercontent.com/60327365/142012022-13b92bfc-0cae-4c9e-ba9e-ed94a200e82a.mov

### CODE REVIEW

**Review by jrainville — COMMENTED** [review]
This looks like it works, but I wonder if it wouldn't be even cleaner if the service instead emitted an event that is listened to by the singleton userProfile to change its appropriate properties.
That way, the profile section doesn't need to know about the singleton properties (even though it's a singleton, so it's normal other modules know about it)
Anyway, it also makes it simpler if multiple modules call the service, then the userProfile would get updated "automatically"

File: src/app/modules/main/profile_section/profile/controller.nim [hunk 1]
```diff
@@ -61,7 +61,11 @@ method getProfile*[T](self: Controller[T]): item.Item =
...
 method storeIdentityImage*[T](self: Controller[T], address: string, image: string, aX: int, aY: int, bX: int, bY: int): identity_image.IdentityImage =
-  self.profileService.storeIdentityImage(address, image, aX, aY, bX, bY)
+  result = self.profileService.storeIdentityImage(address, image, aX, aY, bX, bY)
+  singletonInstance.userProfile.setThumbnailImage(result.thumbnail)
+  singletonInstance.userProfile.setLargeImage(result.large)
 
 method deleteIdentityImage*[T](self: Controller[T], address: string): string =
-  self.profileService.deleteIdentityImage(address)
\ No newline at end of file
+  result = self.profileService.deleteIdentityImage(address)
```
Comment (saledjenic) [inline src/app/modules/main/profile_section/profile/controller.nim:69]: @Khushboo-dev-cpp this is a response of `deleteIdentityImage` call which currently returns an empty string, but since that is a response of delete command, that is not something what will be here in the future or that method in the future may return success or failor of deleting image action.  So I would suggest using just this and not relaying on the response:
```
singletonInstance.userProfile.setThumbnailImage("")
singletonInstance.userProfile.setLargeImage("")
```

**Review by saledjenic — CHANGES_REQUESTED** [review]

**Comment by saledjenic** [comment]
> This looks like it works, but I wonder if it wouldn't be even cleaner if the service instead emitted an event that is listened to by the singleton userProfile to change its appropriate properties. That way, the profile section doesn't need to know about the singleton properties (even though it's a singleton, so it's normal other modules know about it) Anyway, it also makes it simpler if multiple modules call the service, then the userProfile would get updated "automatically"

@jrainville this what you suggested is on of the options we had, but since the details about logged in user (`userProfile`) are being used in almost every part of the app on both Nim and qml sides, we decided to expose it as a registered context and each its property as read `QtProperty` that way due to qml binding and because of corresponding signals of those properties qml will be notified every time a property is changed. That's far less typing than having slots in every module. So conclusion, `userProfile` is used only for reading/fetching details about logged in user (since it doesn't have write properties) and properties are set from a single point from the nim side.

File: src/app/modules/main/profile_section/profile/controller.nim (hunk 1 above)
Comment (Khushboo-dev-cpp) [reply src/app/modules/main/profile_section/profile/controller.nim:69]: Done!

**Review by jrainville — APPROVED** [review]

**Review by saledjenic — APPROVED** [review]
