### PR TITLE
fix(wallet): display collectibles even if account is not in total

### LINKED ISSUE #15128: No collectibles on collectibles tab if account is excluded from total balance
# Bug Report

## Description

When account (own or watch-only) is selected but excluded from total balance, no collectibles for it are displayed

## Steps to reproduce
- Add a watch only account with NFTs
- Open collectibles tab

#### Expected behavior
Collectibles are displayed

#### Actual behavior
No collectibles

### Additional Information
Works on release [2.28.2-rc.1](https://github.com/status-im/status-desktop/releases/tag/untagged-9b26279f69803b4ca9f8)
- Status desktop version: https://github.com/status-im/status-desktop/commit/99d2f6e69
- Operating System: MacOS 14.1.1

https://github.com/status-im/status-desktop/assets/15627093/6fd51cdc-5140-40b8-9875-251ee4563747

### PR DESCRIPTION
**Pull request by alaibe**
balance

fixes #15128
image

### CODE REVIEW

**Comment by alaibe** [comment]
@Cuteivist that s potentially another problem. all accounts do not display collectible and activity if they are excluded
Not sure if a bug or by design!

**Review by saledjenic — APPROVED** [review]

**Comment by benjthayer** [comment]
> @alaibe I'm nearly sure it was by design. Maybe @benjthayer or @dlipicar will know something.

Hey @Cuteivist the design intent was that the `All accounts` view should include the assets, collectibles and activity of watched addresses _only_ if that watched address is set to be included in balance. If set to excluded, the assets, collectibles and activity of that watched address should be excluded from the `All accounts` view. The user has the option to include/exclude each watched address individually.

File: src/app/modules/main/wallet_section/all_collectibles/controller.nim [hunk 1]
```diff
@@ -47,7 +47,7 @@ proc init*(self: Controller) =
     self.delegate.refreshNetworks()
 
 proc getWalletAddresses*(self: Controller): seq[string] =
-  return self.walletAccountService.getWalletAddresses()
```
Comment (dlipicar) [inline src/app/modules/main/wallet_section/all_collectibles/controller.nim:50]: The function name makes me think this should work :D
It probably need to be renamed to know what behavior to expect.
