### PR TITLE
fix(@desktop/contacts): multiple contact related issues fixed

### LINKED ISSUE #5354: Cannot Remove contacts
# Bug Report

## Description

The user is not able to remove contacts via : 

- Contacts list ( Settings --> Messaging --> Contacts, requests and Blocked Users)
      - Click on `...` on one of the contacts and `View Profile` --> `Remove Contact`

- Chat view 
      - Click on the Contact's profile header at the top and hit `Remove Contact`
      
#### Expected behavior
This contact must be shown as 'Not a contact'

#### Actual behavior
Nothing happens

https://user-images.githubusercontent.com/95302135/161716462-e6e66f79-7cf4-4bd4-b7ff-715246227398.mp4

### Additional Information

- Status desktop version: Master : b54111f82ac0bdbecdace09358080f53891a5505

### PR DESCRIPTION
**Pull request by saledjenic**
Multiple contact related issues fixed.

`status-go` PR:
- https://github.com/status-im/status-go/pull/2635

Fixes #5354 #5225 #5198

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

**Review by richard-ramos — APPROVED** [review]

File: src/backend/contacts.nim [hunk 1]
```diff
@@ -13,7 +13,7 @@ proc getContactById*(id: string): RpcResponse[JsonNode] {.raises: [Exception].}
   result = callPrivateRPC("getContactByID".prefix, payload)
 
 proc blockContact*(id: string): RpcResponse[JsonNode] {.raises: [Exception].} =
-  result = callPrivateRPC("blockContact".prefix, %* [id])
+  result = callPrivateRPC("blockContactDesktop".prefix, %* [id])
```
Comment (endulab) [inline src/backend/contacts.nim:16]: I have a feeling that this name is not good since it is not descriptive at all. If we need some different functionality than basic blockContact, it should be named "blockContactAndDoSth...". Adding a new versions of functions with adding ...Desktop is not a good way in my opinion. The same refers to changes in go layer.

**Review by endulab — APPROVED** [review]

**Review by stefandunca — APPROVED** [review]
I didn't test it, I just checked for logical errors

File: src/backend/contacts.nim (hunk 1 above)
Comment (saledjenic) [reply src/backend/contacts.nim:16]: @endulab `blockContactDesktop` name is here just to signify that it should be used instead `blockContact` call for the desktop app. Basically it's the same as `blockContact` but just doesn't set `Added` flag and doesn't delete chat for the blocked user from the db. 

Furthermore... this is temporary here till we sort out contacts related flags on the `status-go` side and after that we will remove it.

**Comment by iurimatias** [comment]
https://ethstatus.testrail.net/index.php?/runs/view/8987&group_by=cases:title&group_order=asc

**Review by iurimatias — APPROVED** [review]
https://ethstatus.testrail.net/index.php?/runs/view/8987&group_by=cases:title&group_order=asc
