### PR TITLE
fix(communities): enable leaving and then re-joining a community

### LINKED ISSUE #4568: [base_bc] can't rejoin a community
### Description

1. create community
2. leave it
3. open community list (+ -> community)
4. click a community in the list (the one u just left)

https://user-images.githubusercontent.com/82375995/150999547-becc6324-4bcc-419e-90de-c5c046ca59fd.mov

```
d=392309 file=core.nim:24 rpc_method=wakuext_leaveCommunity
qml: Wrong section type:  1  or section id:  0x032b24a09287a989f8ced8e318f382a3bb38d4283e7ed9e906bb703fa2438f8d4e
deal with appropriate service...
```

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #4568

### CODE REVIEW

File: src/app_service/service/community/service.nim [hunk 1]
```diff
@@ -377,6 +377,11 @@ QtObject:
         error "error: ", methodName="leaveCommunity", errDesription = "result is nil"
         return
 
+      # Update community so that joined, member list and isMember are updated
+      let updatedCommunity = response.result["communities"][0].toCommunityDto()
```
Comment (saledjenic) [inline src/app_service/service/community/service.nim:381]: @jrainville I guess this is here because of `communities` module? 

Just two things briefly to discuss:
- I am wondering if a logged in user leaves certain community isn't that update propagated from the `status-go` to all members of that community, I expected that info to be received via `messages.new` sent from `status-go`.  So are we sure that a community is updated appropriately in a runtime for other members when after I leave it?
- From the logical point of view, you must admit, it looks a bit weird to update a community you're about to leave. But this part will be deleted, I guess, once we update that `communities module` (as we discussed in some other PR) and get prepare the data provided by `communities module` on demand (when we really need them), that way maintaining an accurate states of community, members there and so won't be needed. This job is waiting for us. :)

**Review by saledjenic — APPROVED** [review]

**Review by alaibe — APPROVED** [review]

File: src/app_service/service/community/service.nim (hunk 1 above)
Comment (jrainville) [reply src/app_service/service/community/service.nim:381]: I just tested and we indeed don't receive a signal from status-go when we leave a community. I also tested with mobile leaving a community and I didn't receive a signal either, so there seems to be a problem on status-go. 
I'll open an issue in status-go to track it.

**Review by iurimatias — CHANGES_REQUESTED** [review]
this didn't work for me. I left the community I created, and now cannot rejoin

see video, clicking button doesn't do anything
https://user-images.githubusercontent.com/176720/151405074-0e86081e-0c1a-43f5-8581-c7cbe230a323.mov

**Comment by jrainville** [comment]
@iurimatias I tested again and I can rejoin correctly. Can you try again and if you can repro the issue, give me steps and/or the data dir.

**Comment by iurimatias** [comment]
@jrainville i'll send you the data folder

**Comment by jrainville** [comment]
@iurimatias it should fixed now. I'll squash once I have your thumbs up

**Comment by abhi-status** [comment]
This works on Ubuntu for me.

**Review by abhi-status — APPROVED** [review]

**Comment by jrainville** [comment]
@iurimatias I fixed the missing name issue. There will still be the issue that the color will be missing from the channels. It would require more work to populate that. I'd suggest fixing that in another issue/PR

**Review by alaibe — APPROVED** [review]

**Comment by alaibe** [comment]
@jrainville I think this has been fixed by Sale/Richard in a PR where they merge chat rather than replace

**Comment by iurimatias** [comment]
it works now
