### PR TITLE
fix(community): fix chat loading forever on first switch

### LINKED ISSUE #20165: Community channel content fails to load until channel is switched
## Summary

Channel content inside communities does not load on initial navigation. The message area remains empty indefinitely. Switching to another channel and back forces the content to load. On macOS, a loading spinner persists at the top of the channel even after messages appear.

## Environment

| | iOS | macOS |
|--|-----|-------|
| **OS version** | iOS 26.2.1 | macOS Tahoe 26.3 |
| **App version** | 2.36.2-1-gcfdd5187f-dirty | 2.37.0 |
| **Status Go** | 10.31.0-15-ga98ba0bd7 | 10.33.0-8-gca7f58711 |
| **Qt version** | 6.9.2 | 6.9.2 |
| **Reproducible** | Yes | Yes |

## Steps to reproduce

1. Open Status app
2. Navigate to any community
3. Open a channel within the community
4. Observe that the channel content does not load — the message area stays empty

**Workaround:** Switch to a different channel, then switch back. Content loads on the second attempt. On macOS desktop, restarting the app also resolves the issue permanently.

## Expected behavior

Channel content should load immediately (or within a few seconds) when a channel is selected.

## Actual behavior

- **iOS + macOS:** Channel content never loads on first navigation. Waited for an extended period — no messages appeared. Reproducible across different channels within communities.
- **macOS:** The issue resolved itself after the first app restart and did not reoccur. This suggests the bug may be tied to initial app launch / first sync after install or update.
- **macOS only (additional issue):** Even after content loads (via the channel-switch workaround), a loading spinner sometimes remains visible at the top of the message list and does not disappear.

## Severity

**High** — Core functionality (reading community channels) is broken without the workaround. Even though the desktop issue may resolve after a restart, this is a critical first-impression problem: new users encountering empty channels on first launch are likely to assume the app is broken and abandon it.

## Additional notes

- The issue is not channel-specific — it reproduces across different channels in different communities.
- On macOS, the problem disappeared after the first app restart, pointing to a possible race condition during initial sync or community data hydration.
- The macOS residual spinner suggests a separate UI state management bug (loading state not cleared after data fetch completes).
@

### PR DESCRIPTION
**Pull request by jrainville**
### What does the PR do

Fixes #20165

When we get the ID for the first message of a chat, we then try to fetch that message in batches. However, there is a slight chance that the message will be fetched from the normal store fetches instead of the DB fetch, which did not check for the searched message. This caused the loading to never end.

### Affected areas

messages module

### Quality checklist

- [x] I am familiar with the [application architecture](/docs/architecture.md) and agreed good practices.
My PR is consistent with this document: [QML Architecture Guidelines](/guidelines/QML_ARCHITECTURE_GUIDE.md)
- [x] I have updated the necessary documentation if needed (eg: updated BUILDING.md if I updated dependencies)

### Screencapture of the functionality

[fixed-chat-loading.webm](https://github.com/user-attachments/assets/361dd57c-32e2-4402-8f59-cc216fedc589)

### Impact on end user

Fixes the infinite loading

### How to test

Spectate a community, wait for some messages to load and click the chat

### Risk 

Low. The risk is that the bug is not fully fixed

### CODE REVIEW

File: src/app/modules/main/chat_section/chat_content/messages/module.nim [hunk 1]
```diff
@@ -535,7 +538,6 @@ method onGetMessageById*(self: Module, requestId: UUID, messageId: string, messa
     return
 
   self.checkIfMessageLoadedAndScroll()
-  self.reevaluateViewLoadingState()
```
Comment (jrainville) [inline src/app/modules/main/chat_section/chat_content/messages/module.nim:538]: `checkIfMessageLoadedAndScroll` already calls `reevaluateViewLoadingState`, so this line is not needed

File: ui/imports/shared/views/chat/MessageView.qml [hunk 2]
```diff
@@ -290,7 +290,7 @@ Loader {
 
 
     function startMessageFoundAnimation() {
-        if (root.active && root.item.startMessageFoundAnimation) {
+        if (root.active && root.item && root.item.startMessageFoundAnimation) {
```
Comment (jrainville) [inline ui/imports/shared/views/chat/MessageView.qml:293]: This just fixes a warning
