### PR TITLE
fix(@desktop/chat): edit channel modal to show up-to-date values

### LINKED ISSUE #3313: edit channel modal keeps previously edited description instead of newest one
https://images.zenhubusercontent.com/261270348/6226a937-2605-4973-8981-3709951c1534/test.mp4

### PR DESCRIPTION
**Pull request by pinebit**
Fixes #3313

### CODE REVIEW

File: src/app/chat/views/channel.nim [hunk 1]
```diff
@@ -296,11 +295,9 @@ QtObject:
     result = selectedChannel.muted  
 
   proc getChatItemById*(self: ChannelView, id: string): QObject {.slot.} =
-    if self.chatItemViews.hasKey(id): return self.chatItemViews[id]
     let chat = self.getChannelById(id)
     let chatItemView = newChatItemView(self.status)
     chatItemView.setChatItem(chat)
-    self.chatItemViews[id] = chatItemView
```
Comment (PascalPrecht) [inline src/app/chat/views/channel.nim:303]: @pinebit you're probably aware of this, still pointing it out to be sure:

`getChatItemById` returns a `QObject` which, if not kept in memory, can potentially be garbage collected while the view still references it (that's why I've introduced this table originally).

Has this somehow changed?

**Review by PascalPrecht — COMMENTED** [review]
Changes LGTM except for one thing

File: src/app/chat/views/channel.nim (hunk 1 above)
Comment (pinebit) [reply src/app/chat/views/channel.nim:303]: I checked the usage of this function. It is only used in two places when we display the corresponding context menu. The reference to this object is kept by `ChatContextMenu` and in turn by `CreateChannelPopup`. It is Okay if it will be destroyed if both the menu and the popup are closed.
The table you introduced added another side effect. It cached old chat data, therefore after editing a chat title and/or description, it displayed old data when the user entered the popup second time.

Comment (PascalPrecht) [reply src/app/chat/views/channel.nim:303]: Gotcha, thanks for clarifying!
