### PR TITLE
fix[Chat] Jump to popup missing channel emojis

### LINKED ISSUE #16623: [Chat] Jump to popup missing channel emojis
# Bug Report

It just shows the letter identicon instead, missing the emoji assigned to the channel

Image

### Additional Information

- Status desktop version: master
- Operating System: linux

### PR DESCRIPTION
**Pull request by caybro**
### What does the PR do

- add `emoji` to the channel list model
- add sorting by channel name
- fix hiding unavailable channels due to permissions, or the chat not being active

Fixes #16623

### Affected areas

StatusSearchListPopup (Ctrl+K search)

### Architecture compliance

- [x] I am familiar with the application architecture and agreed good practices.
My PR is consistent with this document: [Status Desktop Architecture Guide](https://github.com/status-im/status-desktop/blob/master/CONTRIBUTING.md)

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

image

### CODE REVIEW

**Comment by jrainville** [comment]
@caybro I added a commit that fixes it.

I don't know what wasn't working for you initially. The IDs are all long IDs, so no need to remove prefixes or anything. I think maybe you have a reversed condition somewhere, because in the end,  the code is pretty simple.

[hidden-chat.webm](https://github.com/user-attachments/assets/d8cb06c5-7462-42c4-8eff-01554193758d)

File: src/app_service/service/contacts/dto/contacts.nim [hunk 1]
```diff
@@ -77,12 +77,12 @@ proc toImages(jsonObj: JsonNode): Images =
...
 proc toContactRequestState*(value: int): ContactRequestState =
   result = ContactRequestState.None
-  if value >= ord(low(ContactRequestState)) or value <= ord(high(ContactRequestState)):
+  if value >= ord(low(ContactRequestState)) and value <= ord(high(ContactRequestState)):
       result = ContactRequestState(value)
 
 proc toTrustStatus*(value: int): TrustStatus =
   result = TrustStatus.Unknown
-  if value >= ord(low(TrustStatus)) or value <= ord(high(TrustStatus)):
+  if value >= ord(low(TrustStatus)) and value <= ord(high(TrustStatus)):
```
Comment (jrainville) [inline src/app_service/service/contacts/dto/contacts.nim:85]: Nice find. This could have made the app crash :grimacing:

**Review by jrainville — APPROVED** [review]
Nice work

File: src/app_service/service/contacts/dto/contacts.nim (hunk 1 above)
Comment (caybro) [reply src/app_service/service/contacts/dto/contacts.nim:85]: Right, I forgot to mention that! I assume this could very well crash if it was given an out of range value

**Review by micieslak — APPROVED** [review]
Cool!

Tested, works fine.
