### PR TITLE
fix(@desktop/chat): prevent double addition of private chat

### LINKED ISSUE #2999: 1x1 chat is duplicated when initiating it from different places (send message, view profile or start new chat)
1. start a 1x1 chat with + button -> start new chat
2. navigate to the same person profile from public chat -> send message

As result, the 1x1 chat shortcut is duplicated

https://user-images.githubusercontent.com/82375995/126557608-69ab5268-c921-4b13-bc4a-326657e8405c.mov

Deleting such a such crashes the app:

`Object 0x7fb910e9e750 destroyed while one of its QML signal handlers is in progress.
Most likely the object was deleted synchronously (use QObject::deleteLater() instead), or the application is running a nested event loop.
This behavior is NOT supported!
qrc:/app/AppLayouts/Chat/components/ChatContextMenu.qml:148: function() { [native code] }
Traceback (most recent call last)
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/nim_status_client.nim(228) nim_status_client
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/nim_status_client.nim(168) mainProc
/Users/jenkins/workspace/us-desktop_branches_macos_master/vendor/nimqml/src/nimqml/private/qqmlapplicationengine.nim(40) delete
SIGABRT: Abnormal termination.
`

Screenshot 2021-07-21 at 12 17 26

### PR DESCRIPTION
**Pull request by alaibe**
fixes #2999

Before:
image

After:
We switch to the already existing channel

### CODE REVIEW

File: src/app/chat/views/channels_list.nim [hunk 1]
```diff
@@ -103,9 +103,16 @@ QtObject:
     self.endResetModel()
 
   proc addChatItemToList*(self: ChannelsList, channel: Chat): int =
-    self.beginInsertRows(newQModelIndex(), 0, 0)
-    self.chats.insert(channel, 0)
-    self.endInsertRows()
+    var found = false
+    for chat in self.chats:
+      if chat.id == channel.id:
+        found = true
```
Comment (pinebit) [inline src/app/chat/views/channels_list.nim:109]: should you quit/break the loop once found?

**Review by pinebit — APPROVED** [review]

File: src/app/chat/views/channels_list.nim (hunk 1 above)
Comment (alaibe) [reply src/app/chat/views/channels_list.nim:109]: yep, you're right ;) updated

**Review by jrainville — APPROVED** [review]
