### PR TITLE
fix(chat_section): fix changing active chat on leaving another group chat

### LINKED ISSUE #9147: Active chat is changing after leaving non-opened group chat
# Bug Report

## Description

If you have few group chats and you are on group chat A and closing group chat B - your active chat is changing to a random one

## Steps to reproduce

1. Create a few group chats
2. Select one of them
3. Leave non-opened group chat

#### Expected behavior

You stay on the active chat after the leave

#### Actual behavior

Your active chat is switched randomly

https://user-images.githubusercontent.com/117639195/212746141-280df6b1-acc1-4c5a-88a9-885560e923b4.mov

### Additional Information

- Status desktop version: 0.9.0-rc2
- Operating System: macOS

### PR DESCRIPTION
**Pull request by friofry**
Fixes #9147

### What does the PR do
when handling SIGNAL_CHAT_LEFT and SIGNAL_COMMUNITY_CHANNEL_DELETED signals
the currently active chat will be kept as active if another chat has been deleted

### Affected areas

chat_section

### StatusQ checklist
no UI changes

### Screenshot of functionality (including design for comparison)

https://github.com/status-im/status-desktop/assets/1083341/0e300696-5b35-41df-9f93-3ef0df1f53c1

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

**Review by mprakhov — APPROVED** [review]

File: src/app/modules/main/chat_section/module.nim [hunk 1]
```diff
@@ -738,7 +738,10 @@ method onCommunityChannelDeletedOrChatLeft*(self: Module, chatId: string) =
   self.view.chatsModel().removeItemById(chatId)
   self.removeSubmodule(chatId)
 
-  self.setFirstChannelAsActive()
+  # check if the currently active chat has been deleted
```
Comment (kounkou) [inline src/app/modules/main/chat_section/module.nim:741]: Hi there, nice finding, the comment seems confusing to me. 
I was expecting :

```nim
let activeChatId = self.controller.getActiveChatId()
if isDeleted(activeChatId):
   # take action
   ...
```

Could you explain why do we need to setFirstChannelAsActive() if the chatId is the same as the activeChat please?
In the end we might not need the comment, the code should be self explanatory unless there's a specific decision you want to explain more here...

**Review by kounkou — APPROVED** [review]
Left a comment, but it's more an improvment than a critical comment. Nice finding. Thanks

File: src/app/modules/main/chat_section/module.nim (hunk 1 above)
Comment (friofry) [reply src/app/modules/main/chat_section/module.nim]: Sure, updated the branch
