### PR TITLE
fix: make changing local nicknames of contacts work again 

### LINKED ISSUE #4173: Setting local nickname of contact crashes application
# Bug Report

## Description

When trying to set the local nickname of a contact, the application crashes. The reason is the same as what's reported in https://github.com/status-im/status-desktop/issues/4171: `base_bc` uses no longer existing APIs of status-go.

## Steps to reproduce

1. Open profile popup of some contact
2. Select nickname
3. Enter nickname and hit save

#### Expected behavior

Changing the nickname, should reflect the change in all contact related components.

#### Actual behavior

The application crashes.

### Additional Information

- Status desktop version: `c67384367`
- Operating System: macOS Cataline (10.15.3)

### PR DESCRIPTION
**Pull request by PascalPrecht**
This fixes #4173 again. The problem is that changing the local nickname
of a contact now uses new APIs in Status Desktop which emit new events that
older code isn't aware off. Namely, the event handling in the chat section
doesn't get informed anymore that the contact has changed, so it won't update
the view accordingly.

This commit fixes it by subscribing to that newly introduced event
and then updating the view with the payload data.

Notice that this is a quick fix and will most likely be obsolete, once
the chat section has moved to the new architecture as well.

Fixes #4173

### CODE REVIEW

File: src/app/chat/event_handling.nim [hunk 1]
```diff
@@ -29,6 +31,14 @@ proc handleChatEvents(self: ChatController) =
     let notifications = ActivityCenterNotificationsArgs(e).activityCenterNotifications
     self.view.pushActivityCenterNotifications(notifications)
 
+  self.status.events.on("new-contactNicknameChanged") do(e: Args):
+    var evArgs = ContactNicknameUpdatedArgs(e)
+    #let contact = Profile(
+    #  id: evArgs.contactId,
+    #  localNickname: evArgs.nickname
+    #)
+    #self.view.updateChannelForContacts(@[contact])
```
Comment (PascalPrecht) [inline src/app/chat/event_handling.nim:40]: It seems the change in local nicknames via profile popup isn't propagated to the view because the code uses the new `app_service` which emits `new-contactNicknameChanged`, which this module here isn't aware of.

So what I'm trying to do is to have it listen to that event so we can update the view accordingly (similar to what it does in `contactUpdate` below).

However, adding line 35 causes the app to crash. 

```
Object 0x7ff881013a80 destroyed while one of its QML signal handlers is in progress.
Most likely the object was deleted synchronously (use QObject::deleteLater() instead), or the application is running a nested event loop.
This behavior is NOT supported!
qrc:/app/AppLayouts/Chat/popups/ProfilePopup.qml:244: function() { [native code] }
```

The `ContactNicknameUpdatedArgs` type has been introduced in `status-lib` in a branch with the same name as this one. This commit is also pointing at that branch.

So the type exists and the code is compiling just fine.

**Comment by anastasiyaig** [comment]
@PascalPrecht when adding a nickname to someone that i did not add to contacts yet, the field is blank and error in console appears:

```
INF 2021-12-23 16:53:12.888+03:00 getPinnedMailserver                        topics="mailserver-interaction" tid=5795773 file=settings.nim:100 fleet=eth.prod result=
qrc:/app/AppLayouts/Chat/popups/NicknamePopup.qml:63: TypeError: Property 'onClicked' of object StatusButton_QMLTYPE_68(0x7fa711fafc30) is not a function
```

https://user-images.githubusercontent.com/82375995/147250251-5c239d12-9e99-4c71-901c-9f546d41f374.mov

I am not sure if this scenario is acceptable at all , assigning a nickname to someone that was not in your contacts yet, do u see any limitations in code logic for that?

**Review by richard-ramos — APPROVED** [review]

**Comment by anastasiyaig** [comment]
@PascalPrecht can u please look into this?

**Comment by PascalPrecht** [comment]
@anastasiyaig updating the PR in a few

**Review by anastasiyaig — APPROVED** [review]

**Comment by PascalPrecht** [comment]
Thanks for testing @anastasiyaig !
