### PR TITLE
fix(@desktop/chat): ensure replacement of mentions with pubkey works …

### LINKED ISSUE #3492: Mentions by ENS are not working in communities
When mentioning someone in community channel via ENS, the mention is not working:

Screenshot 2021-09-13 at 17 00 20

### PR DESCRIPTION
**Pull request by PascalPrecht**
…in communities

There were two issues why mentions didn't work in communities:

1. The function that replaces mentions with pubkey looked in the wrong place
2. The same function always prepented `userName` with `@` which isn't always necessary

This commit fix this by ensuring the replacement function looks in the community memberlist
instead of a messageList and also by checking if a `userName` already starts with a `@`
and only prepends it if not.

Fixes #3492

### CODE REVIEW

File: src/app/chat/views/messages.nim [hunk 1]
```diff
@@ -78,8 +78,22 @@ QtObject:
...
+      
+      var user = if self.communities.activeCommunity.active:
+        self.communities.activeCommunity.members.getUserFromPubKey(publicKey)
+      else:
+        self.messageList[self.channelView.activeChannel.id].userList.userDetails[publicKey]
+
+      let userName = if user.userName.startsWith('@'):
+        user.userName
+      else:
+        "@" & user.userName
```
Comment (PascalPrecht) [inline src/app/chat/views/messages.nim:96]: There's most likely a nicer way to express this in Nim

**Review by alaibe — APPROVED** [review]
