### PR TITLE
fix(@desktop/community): added option to delete community channel

### LINKED ISSUE #4415: [base_bc] option to delete community channel is missing
# Bug Report

## Steps to reproduce

1. create a community
2. create a channel
3. right click on the channel

option to delete is missing

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
fixes #4415

### What does the PR do

Adds missing delete channel functionality in communities

### Affected areas

communities 

### Screenshot of functionality

https://user-images.githubusercontent.com/60327365/149994016-40c2dd4d-1f1c-439f-b2f8-78d72b9592c6.mov

### CODE REVIEW

**Comment by anastasiyaig** [comment]
@Khushboo-dev-cpp 

- this option `delete` is not visible before i restart the app, can we fix that or it worth a separate issue? 
- Also, it disappears right after i use it for the first time, like i cant delete more than 1 channel in a row without restart
- delete action does not delete the channel if i delete it from channel options (3 dots at the top right corner) . The channel appears there after restart


https://user-images.githubusercontent.com/82375995/150078335-0c052f3a-42f1-4c0f-b17e-680a51a3758e.mov

File: src/app/modules/main/chat_section/controller.nim [hunk 1]
```diff
@@ -162,18 +166,33 @@ method setActiveItemSubItem*(self: Controller, itemId: string, subItemId: string
...
+method deleteChat*(self: Controller, itemId: string) =
   let allChats = self.chatService.getAllChats()
-
   self.activeSubItemId = ""
   if allChats.len == 0:
     self.activeItemId = ""
   else:
     self.activeItemId = allChats[0].id
 
+  echo "Todo for chat "
```
Comment (PascalPrecht) [inline src/app/modules/main/chat_section/controller.nim:187]: This a left over?

**Review by PascalPrecht — COMMENTED** [review]
Changes look nice and structured.
There seems to be a leftover though.

Also, might wanna address @anastasiyaig comments. I haven't run it myself.

Based on Nastya's video, I don't think a community chat should have a "Leave chat" option. It should be a "Delete channel" option. Also, only the admin of a community should be allowed to do that.

**Comment by anastasiyaig** [comment]
yes @PascalPrecht . it appears as `leave` before restarting the app, then it is `delete` but when u delete a channel - it is again `leave`

**Comment by PascalPrecht** [comment]
@anastasiyaig The whole "restarting app" part is unclear to me. Of course, the app needs to be restarted when there's a code change. But I hardly believe that's what you're referring to.

When exactly do you need to restart the app?

**Comment by anastasiyaig** [comment]
@PascalPrecht 

1. I run the PR . I see `leave chat` for community channel instead of `delete`
2. i close the app (logout ) and login back. In this case for the same community and channel i see proper `delete` option for community channel
3. i hit delete option and close the app (logout), login back. Now i see `leave channel` option again instead of `delete`

File: src/app/modules/main/chat_section/controller.nim (hunk 1 above)
Comment (Khushboo-dev-cpp) [reply src/app/modules/main/chat_section/controller.nim:187]: Hey Pascal. no not left over, the remove for 1x1 chat will also land here, its not implemented yet. but maybe I can turn that echo into a comment instead?

**Comment by Khushboo-dev-cpp** [comment]
> @PascalPrecht
> 
> 1. I run the PR . I see `leave chat` for community channel instead of `delete`
> 2. i close the app (logout ) and login back. In this case for the same community and channel i see proper `delete` option for community channel
> 3. i hit delete option and close the app (logout), login back. Now i see `leave channel` option again instead of `delete`

Hey @anastasiyaig 
1. So 1 is indeed a problem and different one, it would be great of we can open a ticker for that. @PascalPrecht  I tried to check it and it seems when the channel is added the amIAdmin is false which should really be true.
2. This I haven't seen, I was able to delete all of them as seen in the video.
3. I again missed the delete option from the 3 dots :D. Will add it now

**Comment by Khushboo-dev-cpp** [comment]
on other thoughts let me just fix the no option to delete after adding a new channel as well :)

File: src/app/modules/main/chat_section/controller.nim [hunk 2]
```diff
@@ -162,18 +166,33 @@ method setActiveItemSubItem*(self: Controller, itemId: string, subItemId: string
...
+
+method removeChat*(self: Controller, itemId: string) =
```
Comment (saledjenic) [inline src/app/modules/main/chat_section/controller.nim:189]: @Khushboo-dev-cpp since chat/channel may be deleted through the context menu even it is not the active one in that moment (so no need to deal with `self.activeItemId` and `self.activeSubItemId`) you can freely remove `deleteChannel` and `deleteChat` from this controller and use passed `itemId` and handle everything in a few lines within this method, something like this:
```
method removeChat*(self: Controller, itemId: string) =
  if self.isCommunitySection:
    self.communityService.deleteCommunityChat(self.getMySectionId(), itemId)
  else:
    self.chatService.deleteChatById(itemId) #this is not implemented yet I think
```

File: src/app/modules/main/chat_section/controller.nim [hunk 3]
```diff
@@ -162,18 +166,33 @@ method setActiveItemSubItem*(self: Controller, itemId: string, subItemId: string
...
+  if self.isCommunitySection:
+    self.deleteChannel(itemId)
+  else:
+    self.deleteChat(itemId)
+
+method onCommunityChannelDeleted*(self: Controller) =
```
Comment (saledjenic) [inline src/app/modules/main/chat_section/controller.nim:195]: @Khushboo-dev-cpp this is unnecessary here, cause you already have all the data you need when channel is deleted and you're in `onCommunityChannelDeleted` method. So please remove this one from here and put a logic in `module.nim` something like this:
```
method onCommunityChannelDeleted*(self: Module, communityId: string, chatId: string) =
  if(not self.chatContentModules.contains(chatId)):
    return

  self.view.chatsModel().removeItemById(chatId)
  self.removeSubmodule(chatId)
  
  if(self.view.chatsModel().getCount() == 0):
    return

  # set the first channel as the active one in model
  let item = self.view.chatsModel().getItemAtIndex(0) # not sure if we have this method, if not add it
  if(item.subItems.getCount() == 0):
    self.setActiveItemSubItem(item.id, "")
  else
    let subItem = item.subItems.getItemAtIndex(0) # not sure if we have this method, if not add it
    self.setActiveItemSubItem(item.id, subItem.id)
```

**Review by saledjenic — CHANGES_REQUESTED** [review]
@Khushboo-dev-cpp changes look good, I added some improvements. Request changes on this and waiting for "remove chat" option.

**Review by PascalPrecht — APPROVED** [review]

File: src/app/modules/main/chat_section/controller.nim [hunk 4]
```diff
@@ -139,6 +144,9 @@ method isCommunity*(self: Controller): bool =
 method getJoinedCommunities*(self: Controller): seq[CommunityDto] =
   return self.communityService.getJoinedCommunities()
 
+method getCommunityById*(self: Controller, communityId: string): CommunityDto =
+  return self.communityService.getCommunityById(communityId)
```
Comment (jrainville) [inline src/app/modules/main/chat_section/controller.nim:148]: I think you can rename this `getCommunity`, since this chat_section represents one community (the community ID is `sectionId`). 
```suggestion
method getCommunityById*(self: Controller): CommunityDto =
  return self.communityService.getCommunityById(self.sectionId)
```

File: src/app_service/service/community/service.nim [hunk 5]
```diff
@@ -276,6 +276,8 @@ QtObject:
 
       if response.result != nil and response.result.kind != JNull:
         let community = response.result["communities"][0].toCommunityDto()
+        # add this to the joinedCommunities list
+        self.joinedCommunities[community.id] = community
```
Comment (jrainville) [inline src/app_service/service/community/service.nim:280]: I can't comment above, but on line 249, we'd need to remove from `joinedCommunities` like you did here

**Review by jrainville — COMMENTED** [review]
Good job. I wanted to check if you had conflicts with my branch and gave some quick feedback on the way

File: src/app/modules/main/chat_section/controller.nim (hunk 4 above)
Comment (Khushboo-dev-cpp) [reply src/app/modules/main/chat_section/controller.nim]: done :)

**Review by anastasiyaig — APPROVED** [review]

File: src/app/modules/main/chat_section/controller.nim [hunk 6]
```diff
@@ -139,6 +144,9 @@ method isCommunity*(self: Controller): bool =
 method getJoinedCommunities*(self: Controller): seq[CommunityDto] =
   return self.communityService.getJoinedCommunities()
 
+method getCommunity*(self: Controller, communityId: string): CommunityDto =
+  return self.communityService.getCommunityById(communityId)
```
Comment (jrainville) [inline src/app/modules/main/chat_section/controller.nim:148]: I guess I wasn't clear. I meant we can get rid of the `communityId` altogether, since the chat_section represents only one community. In this case, `self.sectionId` is the `communityId`. 
From the way you use the function, it seems like you will never actually fecth the info of another community other than the one represented by `sectionId`. 
That was why I suggested changing it to `getCommunity`, or maybe `getMyCommunity` if it's clearer.

File: src/app_service/service/community/service.nim [hunk 7]
```diff
@@ -244,9 +244,22 @@ QtObject:
...
+
+      if response.error != nil:
+        let error = Json.decode($response.error, RpcError)
+        raise newException(RpcException, "Error leaving community: " & error.message)
+
+      if response.result == nil or response.result.kind == JNull:
+        error "error: ", methodName="leaveCommunity", errDesription = "result is nil"
+        return
+
+      let community = response.result["communities"][0].toCommunityDto()
```
Comment (jrainville) [inline src/app_service/service/community/service.nim:257]: This is not necessary. You already have the ID of the community from the function args.

**Review by saledjenic — APPROVED** [review]
@Khushboo-dev-cpp all good from my side, thanks for updating suggested.

File: src/app_service/service/community/service.nim (hunk 7 above)
Comment (saledjenic) [reply src/app_service/service/community/service.nim:257]: @Khushboo-dev-cpp this is a nice optimization, since we actually just need to need to know if `status_go.leaveCommunity(communityId)` call passed with success or not, and the `communityId` is already known. Maybe one day we may improve `status-go` and actually update a response of this call to return just if action passed with success or not.

File: src/app/modules/main/chat_section/controller.nim (hunk 6 above)
Comment (Khushboo-dev-cpp) [reply src/app/modules/main/chat_section/controller.nim:148]: aaah makes sense. My bad I didn't catch that

File: src/app_service/service/community/service.nim (hunk 7 above)
Comment (Khushboo-dev-cpp) [reply src/app_service/service/community/service.nim:257]: I agree, I see a lot of responses and events for communities especially not optimised. it will be visible in my next PR for updating on channel addition removal from admins side. Or maybe I knowledge is incomplete. Willl do :)
