### PR TITLE
fix(images): sending screenshots by changing the regex to detect base64

### LINKED ISSUE #18624: Sending screenshot in 1-on-1 chat doesn't work
# Bug Report

## Steps to reproduce
1. open a 1-on-1 conversation
2. make a screenshot 
3. paste it in the input bar and type some text
4. hit enter/send

#### Expected behavior
the message with the pasted screenshot it sent

#### Actual behavior
the message with the screenshot disappeared and the message input field in this particular 1-on-1 DM is blocked 

Image

### Additional Information
the message input field in the other 1-on-1 conversations work fine (i.e. let you input data there)
- 
- Status desktop version: v2.35 RC4
- Operating System: Windows 10

### PR DESCRIPTION
**Pull request by jrainville**
### What does the PR do

Fixes #18624

The URI given for base64 images changed when we upgraded to QT6. Hopefully this new Regex is more permissive and shouldn't break on new changes

### Affected areas

Utils function

### Architecture compliance

- [x] I am familiar with the [application architecture](/docs/architecture.md) and agreed good practices.
My PR is consistent with this document: [QML Architecture Guidelines](/guidelines/QML_ARCHITECTURE_GUIDE.md)

### Screencapture of the functionality

[sendng-screenshots.webm](https://github.com/user-attachments/assets/6c76a73d-70f1-4064-a796-f83c8a9c4a50)

### Impact on end user

Fixes the issue

### How to test

- Send screenshots or copied images (CTRL+V)
- 
### Risk 

Low

### CODE REVIEW

**Review by caybro — APPROVED** [review]
LGTM

File: src/app/global/utils.nim [hunk 1]
```diff
@@ -158,4 +158,4 @@ QtObject:
       result = (conversion.startsWith0x(value) and conversion.isHexFormat(value) and len(value) == 132) or self.isCompressedPubKey(value)
 
   proc isBase64DataUrl*(str: string): bool =
-    return str.match(re2"^data:.*;base64,")
+    return str.match(re2"(?i)^data:[^,]*;base64,.*$")
```
Comment (dlipicar) [inline src/app/global/utils.nim]: AI suggested checking the character set as well
`([A-Za-z0-9+/=]+)`

**Review by dlipicar — APPROVED** [review]

File: src/app/global/utils.nim [hunk 2]
```diff
@@ -158,4 +158,4 @@ QtObject:
       result = (conversion.startsWith0x(value) and conversion.isHexFormat(value) and len(value) == 132) or self.isCompressedPubKey(value)
 
   proc isBase64DataUrl*(str: string): bool =
-    return str.match(re2"^data:.*;base64,")
+    return str.match(re2"(?i)^data:[A-Za-z0-9+/=]+;base64,[A-Za-z0-9+/=]+$")
```
Comment (dlipicar) [inline src/app/global/utils.nim]: oops, I think the character set check is only meant for what comes after `base64`,  not for the media type that comes after `data` (which could be something like `x-icon`)
