### PR TITLE
fix(@wallet): estimate gas fail when not enough fund

### LINKED ISSUE #5267: The error notification about insufficient funds looks incorrect
# Bug Report

## Steps to reproduce
1. Launch the app
2. Sign in with a user that has a 1-1 chat
3. Get a request in 1-1 chat for a transaction with a big amount of ETH or SNT
4. Click "Accept and send"
5. Click "Confirm", click near "Network fee"

#### Expected behavior
The error notification looks good
#### Actual behavior
The error  notification doesn't look good
image
image

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/commit/591a5bdf34cb2ad161e6cb4e59ecaf6c039abb2e
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

### PR DESCRIPTION
**Pull request by alaibe**
fixes #5267

### CODE REVIEW

File: src/app/modules/main/wallet_section/transactions/view.nim [hunk 1]
```diff
@@ -110,7 +110,6 @@ QtObject:
 
   proc estimateGas*(self: View, from_addr: string, to: string, assetAddress: string, value: string, data: string): string {.slot.} =
     result = self.delegate.estimateGas(from_addr, to, assetAddress, value, data)
-    result = self.delegate.estimateGas(from_addr, to, assetAddress, value, data)
```
Comment (jrainville) [inline src/app/modules/main/wallet_section/transactions/view.nim:113]: I smell a rebase issue here 👃 😆

**Review by jrainville — APPROVED** [review]

**Review by Khushboo-dev-cpp — APPROVED** [review]

**Review by anastasiyaig — APPROVED** [review]

**Comment by anastasiyaig** [comment]
https://ethstatus.testrail.net/index.php?/cases/view/702163
