### PR TITLE
fix(@desktop/communities): Community chat colors stays up to date

### LINKED ISSUE #2826: Communities don't seem to propagate their color properly
One thing I've notice when working on #2805 was that community colors (the ones used in the letter icon) aren't probably available at all times.

For example, initially when starting the app and switching to a community view, the community's channel icons are all in a default color (some blue in latest `master` at the time of creating this issue, but `black` when tested in #2806 ), except for the currently active channel. 

When changing channels, the newly selected one **then** shows its proper color. 

So in other words, it looks like one has to interact with the UI to receive the community color.
The issue is also visible in the top bar component, especially in PR (#2824).

Looks like we're missing some signal emission somewhere.

### PR DESCRIPTION
**Pull request by alaibe**
fixes #2826

When fetching communities, the chat attached to it are not complete.
In this commit, we ensure that everytime we fetch a community, we update
its chat with the chat being loaded which contains all the data we need
to properly display a chat

@jrainville what do you think of this strategy?

### CODE REVIEW

File: src/app/chat/views/communities.nim [hunk 1]
```diff
@@ -72,24 +83,30 @@ QtObject:
       self.activeCommunity.setCommunityItem(self.joinedCommunityList.getCommunityById(communityId))
       self.activeCommunity.triggerMemberUpdate()
 
+  proc populateChats(self: CommunitiesView, communities: seq[Community]): seq[Community] =
+    var i = 0
+    result = @[]
+    while (i<communities.len):
+      var community = communities[i]
```
Comment (jrainville) [inline src/app/chat/views/communities.nim:90]: Why not use a `for`?
```nim
for community in communities:
```

**Review by jrainville — COMMENTED** [review]
Looks good, there is one missing piece I think though.

File: src/app/chat/views/communities.nim (hunk 1 above)
Comment (alaibe) [reply src/app/chat/views/communities.nim:93]: Because the community I need is a var (mutable). However when doing the for loop, the community is immutable.

Is there a way to achieve similar things with a for loop?

File: src/app/chat/views/communities.nim [hunk 2]
```diff
@@ -72,24 +83,30 @@ QtObject:
...
-      if (chat.id == newChat.id):
-        # canPost and categoryId are not available in the newChat so we need to check what we had before
-        newChat.canPost = community.chats[i].canPost
-        newChat.categoryId = community.chats[i].categoryId
-        newChat.mentionsCount = community.chats[i].mentionsCount
-        community.chats[i] = newChat
-        found = true
-      i = i + 1
-    if (not found):
-      community.chats.add(newChat)
```
[the remark this answers is not in the document]
Comment (alaibe) [reply src/app/chat/views/communities.nim:91]: Good catch. I added this line back

File: src/app/chat/views/communities.nim (hunk 1 above)
Comment (jrainville) [reply src/app/chat/views/communities.nim:93]: Hmm, I thought is was mutable. Maybe `for var community in communities`? I'll check the docs

Comment (richard-ramos) [reply src/app/chat/views/communities.nim:93]:
```
for community in communities.mitems:
```

Comment (alaibe) [reply src/app/chat/views/communities.nim]: Thanks @richard-ramos @jrainville it works!!! I just had to declare the sequence mutable manually in order to call this function now

**Review by jrainville — APPROVED** [review]

**Review by iurimatias — CHANGES_REQUESTED** [review]
when attempting to build this branch (and after a rebase) I get this error:

```
src/app/chat/views/communities.nim(35, 1) template/generic instantiation of `QtObject` from here
src/app/chat/views/communities.nim(91, 44) Error: undeclared field: 'values'
```

**Comment by alaibe** [comment]
@iurimatias a previous commit removed an import, that was the source of the error, I reinstate the import and it now compile ;)
(Also rebased with master)

**Comment by iurimatias** [comment]
alright this one works and fixes the issue
