### PR TITLE
fix(InviteBubble): adapt invite bubble depending on access level

### LINKED ISSUE #2399: if a community is approval only then the community dialog should have a request button
steps

1. go to communities and select a community that needs invitation

result: greyed out button saying "You need to be invited"
expected result: button to request

### PR DESCRIPTION
**Pull request by jrainville**
Branched on top of https://github.com/status-im/status-desktop/pull/2469

Makes the invitation bubble show the right button and click handlers depending on the type of community

Same steps to reproduce as in https://github.com/status-im/status-desktop/pull/2469

Kindof fixes #2399

### CODE REVIEW

File: src/app/chat/views/communities.nim [hunk 1]
```diff
@@ -342,6 +345,12 @@ QtObject:
       return "Error declining request to join the community"
     return ""
 
+  proc requestCommunityInfo*(self: CommunitiesView, communityId: string) {.slot.} =
+    try:
+      self.status.chat.requestCommunityInfo(communityId)
+    except Exception as e:
+      error "Error fetching community info", msg = e.msg
```
Comment (richard-ramos) [inline src/app/chat/views/communities.nim:352]: should the UI display an error?

Comment (jrainville) [reply src/app/chat/views/communities.nim:352]: I'm not sure where we'd show it. The fetching is very much "in the background". Maybe we'd need some kind of "error center" where those kinds of errors are logged?
