### PR TITLE
fix(crash): fix crash about community permissions

### LINKED ISSUE #11996: Random crashes on 0.14.0 RC1
# Bug Report

## Description

Hard to know what's going on for real. It just crashes randomly.

It happened to me 3 times in a row when the app was loading on login. Then one time later when it was doing nothing.

My guess is that we receive a signal and we don't handle it correctly and then it crashes.

This is what the logs look like most of the time:

```
INF 2023-08-23 10:31:42.596-04:00 received                                   topics="signals-manager" tid=250780 file=messages.nim:70 signal=messages.new messageID=0x2a66ce015d32936fcc799acbccb055a416c08bd0afeda28946864336e6f7bf65
INF 2023-08-23 10:31:42.596-04:00 received                                   topics="signals-manager" tid=250780 file=messages.nim:70 signal=messages.new messageID=0x83549c70da0b5f9a9795a67368e0390cf66282af36b7d915f94874f9794421da
ERR 2023-08-23 10:31:42.597-04:00 requested community doesn't exists         topics="community-service" tid=250780 file=service.nim:721 communityId=0x04b2a87e119964bf1b338a80f5aecf8f09aa6b246172c0951bdee0ca8ef1f402e5b90eeeb48d9539ec69886ecadb070cb1e81ccc7588a2b93968b172f832745ef5
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault (core dumped)
```

## Steps to reproduce

Unknown.

All I know is that this is my release account, so it has a lot of communities, including the Status community (the control node still uses 0.13)

#### Expected behavior

No crash

#### Actual behavior

Random crashes

### Additional Information

- Status desktop version: 0.14..0 RC1
- Operating System: Ubuntu 20

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #11996

I was able to fix this by having a repro state on my release DB. I think in release mode, there was a race condition about permissions being checked too fast and creating the crash.

With these changes, I no longer experience the crash, though some of the crashes seemed very random, so further testing will be needed with a real build.

The changes I did here include:
- Stop checking for permissions as much
  - We had verification-itis. We would call the function to check permissions in like 4 different places, so we'd check way too often
  - The one i removed was that when creating the chat section, we'd call it on creation, then also on setting the chat active
  - I kept only the one on set active
- I made sure that we only check permissions for members. Privileged users always satisfy the permissions, so no need to check channel or join perms
- This one is probably the main culprit: I removed the CommunitySettingPanel being loaded if you are **not** a privileged user
  - A normal member will never see the settings panel, but somehow, we still loaded the panel, so all the models were loaded
  - commenting that model would remove the crash, so I think this is the actual fix

### CODE REVIEW

File: src/app_service/service/community/dto/community.nim [hunk 1]
```diff
@@ -566,4 +566,16 @@ proc getCommunityChats*(self: CommunityDto, chatsIds: seq[string]): seq[ChatDto]
...
+proc isOwner*(self: CommunityDto): bool =
+  return self.memberRole == MemberRole.Owner
+
+proc isTokenMaster*(self: CommunityDto): bool =
+  return self.memberRole == MemberRole.TokenMaster
+
+proc isAdmin*(self: CommunityDto): bool =
+  return self.memberRole == MemberRole.Admin
+
+proc isPrivilegeduser*(self: CommunityDto): bool =
```
Comment (caybro) [inline src/app_service/service/community/dto/community.nim:580]:
```suggestion
proc isPrivilegedUser*(self: CommunityDto): bool =
```

**Review by caybro — APPROVED** [review]

**Review by dlipicar — APPROVED** [review]

**Review by borismelnik — APPROVED** [review]

**Review by endulab — APPROVED** [review]

**Review by MishkaRogachev — APPROVED** [review]

**Comment by dlipicar** [comment]
BTW, tested this with my old DB that was crashing every time, I'm now able to login :D

**Comment by jrainville** [comment]
> BTW, tested this with my old DB that was crashing every time, I'm now able to login :D

Nice, yeah it fixed the perma crash issue, but it still crashes on signals sadly. I think I'll still merge this and continue investigating. I already have a lead
