### PR TITLE
fix(ac): stop opening AC when it was the last section opened

### LINKED ISSUE #18788: [AC - Milestone 2] Fix Notifications section being persisted incorrectly across restarts
Currently, the app restores the last opened section after restart, including `Notifications`.
This behavior is not correct. The expected logic is:

- If the last section was `Profile` or `Activity Center`, default to `Wallet` instead.
- Otherwise, restore the last opened section normally.

Update the section persistence logic to respect this rule.

### PR DESCRIPTION
**Pull request by jrainville**
### What does the PR do

Fixes #18788

Opens the wallet section is the last section was the AC

### Affected areas

Main module

### Architecture compliance

- [x] I am familiar with the [application architecture](/docs/architecture.md) and agreed good practices.
My PR is consistent with this document: [QML Architecture Guidelines](/guidelines/QML_ARCHITECTURE_GUIDE.md)

### Screencapture of the functionality

[persisted-ac.webm](https://github.com/user-attachments/assets/72348ac4-b736-4f5e-9a97-7838d89efed1)

### How to test

- close the app when on the AC. Reopen

### Risk 

Low

### CODE REVIEW

File: src/app/modules/main/module.nim [hunk 1]
```diff
@@ -889,8 +889,8 @@ method load*[T](
   #  activeSection = homePageSectionItem
 
   # Set active section on app start
-  # If section is empty or profile wait until chats are loaded
-  if not activeSection.isEmpty() and activeSection.sectionType != SectionType.ProfileSettings:
```
Comment (jrainville) [inline src/app/modules/main/module.nim:893]: This was duplicated logic. We already guard against going to the profile section above

**Review by caybro — APPROVED** [review]
LGTM
