### PR TITLE
Fix context menus not updating when blocking/unblocking or when getting a CR

### LINKED ISSUE #16948: “Block user” remains in context menu after block
# Bug Report

## Description

After blocking a user it's expected that the context menu for that use updates to remove that option.

Image
Image

## Steps to reproduce

- Block user
- Check context menu for user in members list of community

#### Expected behavior

Block user option is removed

#### Actual behavior

Block user option is still available.

### Additional Information

- Status desktop version: 2.32 RC4
- Operating System: Mac

### PR DESCRIPTION
**Pull request by jrainville**
### What does the PR do

Fixes #16948 and #16952

The problem was that we just didn't pass `isBlocked` to the `Item`. So either it never worked or we broke it during the refactors.

We also didn't have updates when the events were called in the main module.

Same thing for the `contactRequest`

### Affected areas

Member list in the admin panel and on the right bar of a community.

### Screenshot of functionality (including design for comparison)

Block/unblock:

[block-unblock.webm](https://github.com/user-attachments/assets/51aafa9f-d786-47a3-a937-de3eac29983d)

CR:

[contact-request-context-menu.webm](https://github.com/user-attachments/assets/77595a82-debf-4e28-be5e-0089148cf8b8)

### Impact on end user

Fixes the issue of missing updates

### How to test

- Block and unblock a user and check the different member lists
- Send a contact request to the user and check the member lists

### Risk 

Tick **one**:
- [x] Low risk: 2 devs MUST perform testing as specified above and attach their results as comments to this PR **before** merging.
- [ ] High risk: QA team MUST perform additional testing in the specified affected areas **before** merging.

Worst case, the issue still happens

### CODE REVIEW

File: src/app/modules/shared_models/section_item.nim [hunk 1]
```diff
@@ -338,30 +338,6 @@ proc hasMember*(self: SectionItem, pubkey: string): bool =
...
-    name,
-    ensName,
-    isEnsVerified,
-    nickname,
-    alias,
-    image,
-    isContact,
-    trustStatus,
-  )
-
```
Comment (jrainville) [inline src/app/modules/shared_models/section_item.nim:364]: This was never used

**Review by caybro — COMMENTED** [review]
Code LGTM

> The problem was that we just didn't pass isBlocked to the Item. So either it never worked or we broke it during the refactors.

But can't find this place in the diff here :)

**Comment by jrainville** [comment]
> Code LGTM
> 
> > The problem was that we just didn't pass isBlocked to the Item. So either it never worked or we broke it during the refactors.
> 
> But can't find this place in the diff here :)

Here https://github.com/status-im/status-desktop/pull/16978/files#diff-7638828ebe375b5677d6a6832e1d28dce5ac5551923d8995eba39c9dc272d59fR154
and
here https://github.com/status-im/status-desktop/pull/16978/files#diff-4bed854dbe31f65c7442333fb41ea04c6f79c8b1d1129449eebc6f9bbadbca0eR1897

**Review by osmaczko — APPROVED** [review]

**Review by caybro — APPROVED** [review]

**Comment by jrainville** [comment]
@iurimatias you have been selected as the tester
```
There were 5 items in your list. Here they are in random order:

iurimatias
micieslak
alexjba
osmaczko
caybro
```
