### PR TITLE
fix(pairing): profile img not updating when the paired device changes it

### LINKED ISSUE #17731: Profile photo does not sync after it changes on mobile
# Bug Report

## Description

* When a user has a desktop client and mobile client synced together, and updates their profile photo on the mobile client, the desktop client does not automatically update the profile photo.
  * It seems the desktop client correctly handle updating the profile name and bio, but the profile image does seem to re-render after it's been updated from the mobile client (which is synced to the desktop client).

## Steps to reproduce

- Open the Status Desktop and Mobile apps
- Create a profile on Status Desktop
- On Status Mobile, choose to recover or sync a profile instead of creating a new profile
- Once the mobile client is synced with the desktop client, navigate to the profile settings in both apps
- On the mobile client, update the profile photo to a new/different image
- Observe the desktop client for syncing the changes of the profile photo

#### Expected behavior

- The profile photo on the desktop client should update after it syncs the profile photo changes from the mobile client.

#### Actual behavior

- Currently, the profile photo on the desktop client does not update after the synced mobile client updates the profile photo.

#### Screen capture for reference

https://github.com/user-attachments/assets/66d2a92c-3e46-475b-bbd5-de2220b9dcfa

### PR DESCRIPTION
**Pull request by jrainville**
### What does the PR do

Fixes #17731

We just didn't listen to the property change from the signal.

### Affected areas

Signal listening

### Architecture compliance

- [x] I am familiar with the application architecture and agreed good practices.
My PR is consistent with this document: [Status Desktop Architecture Guide](https://github.com/status-im/status-desktop/blob/master/CONTRIBUTING.md)

### Screenshot of functionality

[profile-change.webm](https://github.com/user-attachments/assets/7ace2798-b14b-4643-a6a5-8f47e59937aa)

### Impact on end user

Fixes the issue (no longer need to restart the app)

### How to test

1. Pair your desktop app with a mobile one (though another desktop would do the same)
2. Update the profile pic on the new one
3. it updates now

### Risk 

Worst case the bug isn't fixed

Tick **one**:
- [x] Low risk: 2 devs MUST perform testing as specified above and attach their results as comments to this PR **before** merging.
- [ ] High risk: QA team MUST perform additional testing in the specified affected areas **before** merging.

### CODE REVIEW

File: src/app_service/service/accounts/service.nim [hunk 1]
```diff
@@ -102,11 +102,6 @@ QtObject:
   proc getKeyStoreDir*(self: Service): string =
     return self.keyStoreDir
 
-  proc connectToFetchingFromWakuEvents*(self: Service) =
-    self.events.on(SignalType.WakuBackedUpProfile.event) do(e: Args):
-      var receivedData = WakuBackedUpProfileSignal(e)
-      self.updateLoggedInAccount(receivedData.backedUpProfile.displayName, receivedData.backedUpProfile.images)
-
```
Comment (jrainville) [inline src/app_service/service/accounts/service.nim:109]: dead code

File: ui/app/mainui/Popups.qml [hunk 2]
```diff
@@ -612,20 +612,15 @@ QtObject {
...
+                    if (!callback) {
+                        console.error("ImageCropWorkflow: no callback provided")
                         return
                     }
-
-                    rootStore.profileSectionStore.profileStore.uploadImage(image,
-                                                  cropRect.x.toFixed(),
-                                                  cropRect.y.toFixed(),
-                                                  (cropRect.x + cropRect.width).toFixed(),
-                                                  (cropRect.y + cropRect.height).toFixed());
```
Comment (jrainville) [inline ui/app/mainui/Popups.qml:628]: More dead code. `uploadImage`  doesn't exist in the store anymore

File: ui/imports/shared/controls/chat/ProfileHeader.qml [hunk 3]
```diff
@@ -151,10 +151,10 @@ Item {
                     if (!!root.icon)
                         Global.openMenu(editImageMenuComponent, this)
                     else
-                        Global.openChangeProfilePicPopup(tempIcon);
+                        Global.openChangeProfilePicPopup(setTempIcon);
```
Comment (jrainville) [inline ui/imports/shared/controls/chat/ProfileHeader.qml:154]: Just a rename because the code was confusing (I was searching for the call back and turns out `tempIcon` is a function)

**Review by jrainville — COMMENTED** [review]
I also did a little bit of cleaning up of things I found while investigating

File: ui/app/mainui/Popups.qml (hunk 2 above)
Comment (caybro) [reply ui/app/mainui/Popups.qml:628]: Hmm... how and where is the image stored to a file then?

**Review by alexjba — APPROVED** [review]

**Review by caybro — APPROVED** [review]
