### PR TITLE
feat: hook reactions in read only channel and fix issues

### LINKED ISSUE #13523: [Channel Permissions] Hide reactions from community users that don't have the permission to add reactions
### Description

[Design](https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba⎜Desktop---Communities?type=design&node-id=21010-478156&mode=design&t=gRqFN5zR8RAo4uZF-0)
When a new channel is created and permissions are added, there is an option to allow community members with view only permission to add reactions.

This means the reactions should only be visible to the members with the following permissions:
1. View and post permission
2. View and add reaction permission

Screenshot 2024-02-12 at 16 26 08

TODO:
- [x] Integrate the backend flows in `nim` (https://github.com/status-im/status-desktop/issues/13292)

- [x] Remove this commented flag that's hiding the option
https://github.com/status-im/status-desktop/blob/master/ui/app/AppLayouts/Communities/views/PermissionsView.qml#L132

- [x] Implement `setViewOnlyCanAddReaction`
https://github.com/status-im/status-desktop/blob/master/ui/imports/shared/stores/PermissionsStore.qml#L20

- [x] Provide the `ViewOnlyCanAddReaction` value in the store and connect it to the `CreateChannelPopup.viewOnlyCanAddReaction`

- [x] Update the MessageView.d.addReactionAllowed with the backend value for the user
https://github.com/status-im/status-desktop/blob/master/ui/imports/shared/views/chat/MessageView.qml#L264

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #13523

Status-go PR: https://github.com/status-im/status-go/pull/4900

This hooks the feature that let's users react in a view only channel, but only if the setting is enabled by admins.

It also fixes a couple small issues, 2 of them in status-go.

Known issues:
- It's very small, but the context menu doesn't look very good. That's because I had to temper with the QMl myself and there is no design or component right now for just emojis. Let me know if I'm wrong. Otherwise, it can be fixed in another issue/PR

[reactions.webm](https://github.com/status-im/status-desktop/assets/11926403/6a7ea6cc-f063-4a1e-a171-3193bac9c5fd)

### CODE REVIEW

File: src/app_service/service/chat/dto/chat.nim [hunk 1]
```diff
@@ -416,3 +423,12 @@ proc communityChannelUuid*(self: ChatDto): string =
   if self.communityId == "":
     return ""
   return self.id[self.communityId.len .. ^1]
+
+proc updateMissingFields*(chatToUpdate: var ChatDto, oldChat: ChatDto) =
```
Comment (jrainville) [inline src/app_service/service/chat/dto/chat.nim:427]: I moved this here because it is needed by the chat service too, so now both community and chat services can use it.

File: src/app_service/service/chat/service.nim [hunk 2]
```diff
@@ -165,13 +165,16 @@ QtObject:
...
-
+            var updatedChat = chatDto
             # Handling members update for non-community chats
             let isCommunityChat = chatDto.chatType == ChatType.CommunityChat
+            let oldChat = self.chats[chatDto.id]
             if not isCommunityChat and self.chats.hasKey(chatDto.id) and self.chats[chatDto.id].members != chatDto.members:
               self.events.emit(SIGNAL_CHAT_MEMBERS_CHANGED, ChatMembersChangedArgs(chatId: chatDto.id, members: chatDto.members))
-            self.updateOrAddChat(chatDto)
+            if isCommunityChat:
+              updatedChat.updateMissingFields(oldChat)
```
Comment (jrainville) [inline src/app_service/service/chat/service.nim:175]: This was needed, because otherwise we lost the community fields like `viewersCanPostReactions` (they reseted to `false`)

File: ui/imports/shared/stores/PermissionsStore.qml [hunk 3]
```diff
@@ -17,10 +17,6 @@ QtObject {
     readonly property var permissionsModel:
         chatCommunitySectionModuleInst.permissionsModel
 
-    function setViewOnlyCanAddReaction(chatId, checked) {
-        //TODO: backend implementation
-    }
```
Comment (jrainville) [inline ui/imports/shared/stores/PermissionsStore.qml:22]: I removed those because that field isn't updated independently, it's updated using the EditChat API

File: ui/imports/shared/views/chat/ChatContextMenuView.qml [hunk 4]
```diff
@@ -41,8 +42,6 @@ StatusMenu {
     signal leaveChat(string chatId)
     signal updateGroupChatDetails(string chatId, string groupName, string groupColor, string groupImage)
 
-    signal createCommunityChannel(string chatId, string newName, string newDescription, string newEmoji, string newColor)
-    signal editCommunityChannel(string chatId, string newName, string newDescription, string newEmoji, string newColor, string newCategory)
```
Comment (jrainville) [inline ui/imports/shared/views/chat/ChatContextMenuView.qml:45]: Those were not used :scissors:

File: ui/imports/shared/views/chat/MessageView.qml
Comment (jrainville) [inline ui/imports/shared/views/chat/MessageView.qml:1]: I had to do a couple changes in this file and QML so that the context menu with just Emojis appeared. It's not perfect visually, but I didn't want to waste too much time on it. I think we should open another issue after that to polish the UI

**Review by jrainville — COMMENTED** [review]
I added some comments to explain some of the code changes

File: src/app_service/service/community/service.nim [hunk 5]
```diff
@@ -641,10 +634,20 @@ QtObject:
               )
             )
 
-          # Handle name/description changes
-          if chat.name != prevChat.name or chat.description != prevChat.description or chat.color != prevChat.color or chat.emoji != prevChat.emoji:
-            var updatedChat = findChatById(chat.id, updatedChats)
-            updatedChat.updateMissingFields(chat)
+          if chat.name != prevChat.name or chat.description != prevChat.description or chat.color != prevChat.color or
+              chat.emoji != prevChat.emoji or chat.viewersCanPostReactions != prevChat.viewersCanPostReactions:
+            var updatedChat = chat
```
Comment (jrainville) [inline src/app_service/service/community/service.nim:639]: Note here that I'm no longer using `updatedChats`, but the `chat` directly here, because `updatedChats` was missing a LOT of the fields, and not just community fields. It was also missing its ID and communityID.

I don't think it should cause a lot of problems to use `chat` directly. I tested editing the channel in multiple ways and they all worked.

**Review by alexjba — COMMENTED** [review]
Screenshot 2024-03-11 at 21 33 08

The emojis are no longer available on hover for group chats.
Looks good to me otherwise.

**Comment by jrainville** [comment]
> The emojis are no longer available on hover for group chats. Looks good to me otherwise.

Nice find. I fixed that in status-go.

I also fixed a crash I introduced.

**Comment by jrainville** [comment]
The status-go PR is now merged. I rebased and updated the vendor. 

@alexjba @igor-sirotin you can review :D

File: src/app/modules/main/chat_section/item.nim [hunk 6]
```diff
@@ -35,6 +35,9 @@ type
     loaderActive: bool
     locked: bool
     requiresPermissions: bool
+    canPostMessages: bool
+    canPostReactions: bool
```
Comment (igor-sirotin) [inline src/app/modules/main/chat_section/item.nim:39]: I wonder if this partially duplicates this:
https://github.com/status-im/status-desktop/blob/3ef21897fd70a49bb9bbc5fbc94b1012383e45ae/src/app/modules/main/chat_section/item.nim#L39-L40

It's in https://github.com/status-im/status-desktop/pull/13876

File: src/app_service/service/community/service.nim [hunk 7]
```diff
@@ -641,10 +634,20 @@ QtObject:
...
+
+            # TODO improve this in https://github.com/status-im/status-desktop/issues/12595
+            # Currently, status-go only sends canPostReactions on app start (getChannelGroups)
+            # so here, we need to imply it. If viewersCanPostReactions is true, then everyone can post reactions
+            # admins can also always post reactions
+            if chat.viewersCanPostReactions == true or
+                (chat.viewersCanPostReactions == false and community.memberRole != MemberRole.None):
+              updatedChat.canPostReactions = true
+            elif chat.viewersCanPostReactions == false and community.memberRole == MemberRole.None:
+              updatedChat.canPostReactions = false
```
Comment (igor-sirotin) [inline src/app_service/service/community/service.nim:649]:
```suggestion
            if chat.viewersCanPostReactions or
                (!chat.viewersCanPostReactions and community.memberRole != MemberRole.None):
              updatedChat.canPostReactions = true
            elif !chat.viewersCanPostReactions and community.memberRole == MemberRole.None:
              updatedChat.canPostReactions = false
```

File: ui/imports/shared/views/chat/MessageView.qml [hunk 8]
```diff
@@ -910,7 +910,7 @@ Loader {
 
                 quickActions: [
                     Loader {
-                        active: d.addReactionAllowed && delegate.hovered && !delegate.hideQuickActions
+                        active: d.addReactionAllowed && delegate.hovered
```
Comment (igor-sirotin) [inline ui/imports/shared/views/chat/MessageView.qml:913]: hmm, why don't we want to keep `&& !delegate.hideQuickActions`? 🤔

File: ui/imports/shared/views/chat/MessageContextMenuView.qml [hunk 9]
```diff
@@ -23,6 +23,7 @@ StatusMenu {
     property string myPublicKey: ""
     property bool amIChatAdmin: false
     property bool disabledForChat: false
+    property bool showOnlyEmojiReactions: false
```
Comment (igor-sirotin) [inline ui/imports/shared/views/chat/MessageContextMenuView.qml:26]: "show only" means that as soon as we set this to `true`, no other options will appear.
But that wouldn't be true when `disabledForChat` is false.

```suggestion
    property bool forceEnableEmojiReactions: false
```

**Review by igor-sirotin — APPROVED** [review]

**Comment by igor-sirotin** [comment]
Thank for this, looks cool!

File: src/app/modules/main/chat_section/item.nim (hunk 6 above)
Comment (jrainville) [reply src/app/modules/main/chat_section/item.nim:39]: Hmm, good question. I guess `canPostMessages` is the equivalent of  `viewAndPostPermissionsSatisfied`.

The `canPostReactions` is necessary for my PR and it's definitely different.

I added the `canPostMessages` because it was given by status-go, but we don't use it for now, so maybe it's worth removing to avoid confusion? cc @endulab

File: ui/imports/shared/views/chat/MessageView.qml (hunk 8 above)
Comment (jrainville) [reply ui/imports/shared/views/chat/MessageView.qml:913]: I didn't want to tamper too much with the QML code because it's not my jurisdiction, but here it's because we want to still show the Emoji reacitons when doing a right-click on a message in a read-only channel.

The code is not really made for that, so that's why it's a bit weird in places.

File: src/app_service/service/community/service.nim (hunk 7 above)
Comment (jrainville) [reply src/app_service/service/community/service.nim:649]: Yeah, I used those explicit conditions when developing because trying to get the right conditions was a pain so it was easier to understand for me, but then I forgot to simplify haha.

BTW, it's `not` instead of `!` in Nim :wink:

File: ui/imports/shared/views/chat/MessageView.qml (hunk 8 above)
Comment (igor-sirotin) [reply ui/imports/shared/views/chat/MessageView.qml:913]: Looks like it's important to keep here.
Guessing from  the definition:
```qml
readonly property bool hideQuickActions: root.isChatBlocked ||
                  root.placeholderMessage ||
                  root.isInPinnedPopup ||
                  root.editModeOn ||
                  !root.rootStore.mainModuleInst.activeSection.joined
```

we should hide the _and disable the loaders_ in a few cases. 
`isInPinnedPopup` is also covered by `addReactionAllowed`. But all other cases doesn't seem to be covered.

I understand that `isChatBlocked` doesn't consider `canPostReactions` at all. 
So we should probably review the set of properties here so that it fit our needs.

**Review by alexjba — APPROVED** [review]
Nice work!
