### PR TITLE
fix(curated_communities): support curated.communities.update signal

### LINKED ISSUE #12207: Spam about unknown curated.communities.update signal
# Bug Report

## Description

This happens on new accounts. It seems because it retries the curated dapp fetch

image

I think supporting the signal will help. Maybe increasing the timeout too.

## Steps to reproduce

1. open a new account
2. wait a bit
3. see the spam

#### Expected behavior

No spam

#### Actual behavior

Spam

### Additional Information

- Status desktop version: master

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #12207

Adds support for the "unknown signal". This removes the spam, as we just do something with it now.

I also upped the timer for unknown communities to 1 minute instead of 3 seconds. https://github.com/status-im/status-go/pull/4046#pullrequestreview-1633952634

### CODE REVIEW

File: src/app/core/signals/remote_signals/community.nim [hunk 1]
```diff
@@ -8,6 +8,10 @@ import signal_type
 type CommunitySignal* = ref object of Signal
   community*: CommunityDto
 
+type CuratedCommunitieSignal* = ref object of Signal
```
Comment (caybro) [inline src/app/core/signals/remote_signals/community.nim:11]: Typo there:
```suggestion
type CuratedCommunitiesSignal* = ref object of Signal
```

**Review by MishkaRogachev — APPROVED** [review]

**Review by osmaczko — APPROVED** [review]

**Review by caybro — APPROVED** [review]
