### PR TITLE
fix profile pic change and move it to new architecture

### LINKED ISSUE #3997: [refactoring/base_01] changing profile picture is not working
go to my profile and edit profile picture, upload a new profile picture. nothing happens

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #3997

### CODE REVIEW

File: src/app/modules/main/profile_section/profile/view.nim [hunk 1]
```diff
@@ -37,3 +40,29 @@ QtObject:
...
+
+    try:
+      # TODO add crop tool for the image
+      let identityImage = self.delegate.storeIdentityImage(self.model.address, image, aX, aY, bX, bY)
+      # TODO use only one type
+      let identityImageConverted = item.IdentityImage(
+        thumbnail: identityImage.thumbnail,
+        large: identityImage.thumbnail
+      )
+      self.model.setIdentityImage(identityImageConverted)
```
Comment (alaibe) [inline src/app/modules/main/profile_section/profile/view.nim:59]: still a few todos there are they still valid/

**Review by alaibe — APPROVED** [review]

File: src/app/modules/main/profile_section/profile/view.nim (hunk 1 above)
Comment (jrainville) [reply src/app/modules/main/profile_section/profile/view.nim:59]: I think so yes, though low priority

**Comment by richard-ramos** [comment]
Also fixes  https://github.com/status-im/status-desktop/issues/3822
