### PR TITLE
fix(community): community tokens disappear when minting of a new token is finished

### LINKED ISSUE #15076: Owner token not available in community management tab after restart
# Bug Report

## Description

After app restart, community "forgets" about owner token.

## Steps to reproduce

1. Mint owner token
2. Restart the app
3. Go to community management Tokens tab

https://github.com/status-im/status-desktop/assets/33099791/808366ef-2801-4a3f-a253-9787a3a56519

#### Expected behavior

Minted owner and master-token are visible.

#### Actual behavior

No tokens are visible. 

### Additional Information

- Status desktop version: a3c9012f4ac959e7a3fef21268c550c55f7d332a (master)
- Operating System: Fedora

### PR DESCRIPTION
**Pull request by friofry**
fixes #15076

### What does the PR do
When a new token is minted and `SIGNAL_COMMUNITIES_UPDATE` is emitted, we recreate the `SectionItem` with the updated `CommunityDto`.
After this, `SectionItem.communityTokens` is empty and will be retrieved asynchronously via `getCommunityTokensDetailsAsync`.
In this PR, old `communityTokens` are kept until `onCommunityTokensDetailsLoaded` updates the tokens.

### Affected areas
Communities

### Screenshot of functionality (including design for comparison)

https://github.com/status-im/status-desktop/assets/1083341/11d44e03-849e-4adf-9819-f5c8bec52e7a

https://github.com/status-im/status-desktop/assets/1083341/739bd549-d703-4869-b971-63e8d45986ca

### CODE REVIEW

File: src/app/modules/main/module.nim [hunk 1]
```diff
@@ -333,6 +333,12 @@ proc createCommunitySectionItem[T](self: Module[T], communityDetails: CommunityD
     # We will update the model later when we finish loading the accounts
     self.controller.asyncGetRevealedAccountsForAllMembers(communityDetails.id)
 
+    # If there tokens are already in the model, we should keep the existing community tokens, until
+    # getCommunityTokensDetailsAsync will trigger onCommunityTokensDetailsLoaded
```
Comment (friofry) [inline src/app/modules/main/module.nim:337]: Alternatively, I can call `createTokenItemImproved` inplace because we already have a CommunityTokenDto. But I'm not sure if this is possible without communityTokenJsonItems.

File: src/app/modules/main/module.nim [hunk 2]
```diff
@@ -333,6 +333,12 @@ proc createCommunitySectionItem[T](self: Module[T], communityDetails: CommunityD
     # We will update the model later when we finish loading the accounts
     self.controller.asyncGetRevealedAccountsForAllMembers(communityDetails.id)
 
+    # If there tokens are already in the model, we should keep the existing community tokens, until
```
Comment (jrainville) [inline src/app/modules/main/module.nim:336]:
```suggestion
    # If there are tokens already in the model, we should keep the existing community tokens, until
```

**Review by jrainville — APPROVED** [review]

File: src/app/modules/main/module.nim [hunk 3]
```diff
@@ -333,6 +333,12 @@ proc createCommunitySectionItem[T](self: Module[T], communityDetails: CommunityD
...
+    # getCommunityTokensDetailsAsync will trigger onCommunityTokensDetailsLoaded
+    let existingCommunity = self.view.model().getItemById(communityDetails.id)
```
Comment (MishkaRogachev) [inline src/app/modules/main/module.nim:338]: is ti possible that `existingCommunity` in nil here?

**Review by MishkaRogachev — APPROVED** [review]

File: src/app/modules/main/module.nim (hunk 3 above)
Comment (friofry) [reply src/app/modules/main/module.nim:338]: Yes, good point! Fixed
(it's not nil because getItemById returns by value, so by default it creates an empty community with an empty tokenlist)

**Review by endulab — APPROVED** [review]
