### PR TITLE
fix: group member list

### LINKED ISSUE #3051: groups are not displaying user list on the sidebar
The user list feature is working in communities and public channels, but doesn't seem to be working on groups, in the screenshot below, the group has 3 members, but the sidebar is showing only 1

### PR DESCRIPTION
**Pull request by richard-ramos**
Fixes #3051

### CODE REVIEW

File: src/app/chat/event_handling.nim [hunk 1]
```diff
@@ -37,7 +37,7 @@ proc handleChatEvents(self: ChatController) =
     self.view.hideLoadingIndicator()
     self.view.updateUsernames(evArgs.contacts)
     self.view.updateChats(evArgs.chats)
-    self.view.pushMessages(evArgs.messages)
+    self.view.pushMessages(evArgs.messages, evArgs.chats)
```
Comment (alaibe) [inline src/app/chat/event_handling.nim:40]: Maybe, we should use another API than pushMessages to update the member list?
What about pushMembers?

**Review by jrainville — COMMENTED** [review]
Looks good, but maybe just change the use of `pushMessages`

File: src/app/chat/views/user_list.nim [hunk 2]
```diff
@@ -70,6 +72,58 @@ QtObject:
...
+      for m in members:
+        if m.id == userPublicKey: 
+          found = true
+          break
+      if not found:
+        toDelete.add(userPublicKey)
+
+    # Removing deleted members
+    if toDelete.len > 0:
+      self.beginResetModel()
```
Comment (pinebit) [inline src/app/chat/views/user_list.nim:121]: wondering why not https://doc.qt.io/qt-5/qabstractitemmodel.html#beginRemoveRows?

**Review by pinebit — APPROVED** [review]

**Review by jrainville — APPROVED** [review]
