### PR TITLE
Fix(Contacts): fix weird behaviour in some contacts flows edge cases

### LINKED ISSUE #10400: Outgoing pending CR notification does not show valid contact details
Screenshot 2023-04-24 at 12 07 29
Initial outgoing pending contact request notification does not show valid contact details, only public key is available

### LINKED ISSUE #10500: Contacts: After declining, new request is still shown as pending after being accepted
# Bug Report

## Description

Split from and dependant on https://github.com/status-im/status-desktop/pull/10336

1. Alice sends a contact request to Bob
2. Bob declines the contact request from Alice
3. Bob sends a contact request to Alice
4. Alice approves the contact request
5. Bob is still shown that the contact request is pending until Bob sends a message

https://user-images.githubusercontent.com/50769329/235460467-b2200cf8-9b9f-43c7-ab58-6f7a1704ac9b.mp4

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/aarch64/job/package/job/PR-10336/20/
- Operating System: Mac

### PR DESCRIPTION
**Pull request by MishkaRogachev**
Close #10500

### What does the PR do

1. Fix displaying CR messages in the chat
2. Relay on actual status-go state for contacts flows 

### Affected areas

Contacts, Chat, Activity Center

### Screenshot of functionality (including design for comparison)

Screenshot 2023-05-11 at 20 53 27

Screenshot 2023-05-11 at 20 53 47

Screenshot 2023-05-11 at 20 49 02

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

File: src/app_service/service/contacts/service.nim [hunk 1]
```diff
@@ -407,25 +408,37 @@ QtObject:
...
+
+  proc sendContactRequest*(self: Service, publicKey: string, message: string) =
+    # Prefetch contact to avoid race condition with AC notification
+    discard self.getContactById(publicKey)
+
+    try:
       let response = status_contacts.sendContactRequest(publicKey, message)
       if(not response.error.isNil):
         let msg = response.error.message
         error "error sending contact request", msg
```
Comment (igor-sirotin) [inline src/app_service/service/contacts/service.nim:438]: Its possible to make it oneliner:
```nim
error "error sending contact request", msg = response.error.message
```

**Review by igor-sirotin — APPROVED** [review]

**Review by igor-sirotin — APPROVED** [review]
