### PR TITLE
[CHERRY-PICK] fix(AppearanceView): Rename padding factor to layout spacing

### LINKED ISSUE #19315: [Settings --> Appearance] rename Padding factor to Layout Spacing and add subtitle to explain this feature
Let's rename Padding factor to Layout Spacing and add subtitle, "Adjust how compact or spacious the layout looks." to explain this feature

Image

### PR DESCRIPTION
**Pull request by noeliaSD**
### What does the PR do

Closes #19315
Backport of https://github.com/status-im/status-desktop/pull/19317

- Renames Padding Factor to Layout Spacing to better reflect its purpose.
- Adds a descriptive subtitle to clarify what this setting controls and improve overall UX clarity.

### CODE REVIEW

File: ui/i18n/qml_base_lokalise_en.ts [hunk 1]
```diff
@@ -2357,8 +2357,8 @@
       <source>%n issue(s)</source>
       <comment>AppMain</comment>
       <translation>
-        <numerusform></numerusform>
-        <numerusform></numerusform>
+        <numerusform>%n issue</numerusform>
+        <numerusform>%n issues</numerusform>
```
Comment (caybro) [inline ui/i18n/qml_base_lokalise_en.ts]: This file (base) should be empty; drop those translations

Comment (noeliaSD) [reply ui/i18n/qml_base_lokalise_en.ts]: Removed `qml_base_lokalise_en.ts` related changes on this PR
