### PR TITLE
fix(chat): add signal to display new messages received

### LINKED ISSUE #4370: Messages are not received in real time when in a public chat

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #4370

Adds the signal for new messages received

It seems like other signals like reactions and pins might not be there yet as well, but they can be added later since they aren't as needed

### CODE REVIEW

File: src/app/modules/main/chat_section/chat_content/messages/controller.nim [hunk 1]
```diff
@@ -52,6 +52,12 @@ method init*(self: Controller) =
       return
     self.delegate.newMessagesLoaded(args.messages, args.reactions, args.pinnedMessages)
 
+  self.events.on(SignalType.Message.event) do(e: Args):
```
Comment (saledjenic) [inline src/app/modules/main/chat_section/chat_content/messages/controller.nim:55]: @jrainville since `SignalType.Message.event` is a global signal, coming from `status-go` directly, it shouldn't be handled in modules, but in appropriate service and from there appropriate signal should be sent which one or many modules may be connected to. 

For a reference please check `proc doConnect(self: Service) =` from the contact service (`statusUpdates` and `contacts` properties from the `MessageSignal` are handled there) and apply in this PR something similar. Actually you just need to move this connection to the message service and emit a new signal from there which will be handled here.

**Review by saledjenic — CHANGES_REQUESTED** [review]
@jrainville all good here, just move connection to the right place according to the comment below, cause we want to avoid breaking some rules we are trying to establish here.

**Comment by jrainville** [comment]
@saledjenic fixed and rebased

**Review by saledjenic — APPROVED** [review]
