### PR TITLE
fix(@desktop/general): app/os notifications

### LINKED ISSUE #4409: notifications aren't being triggered
# Bug Report

## Description

No notifications are seen regardless of the settings in this branch

### PR DESCRIPTION
**Pull request by saledjenic**
Corresponding `dotherside` PR:
- https://github.com/status-im/dotherside/pull/57

Corresponding `nimqml` PR:
- https://github.com/status-im/nimqml/pull/37

Fixes #4409

What's done:
- sound volume is stored as `int` now instead of `float` how it was, the reason why I updated that is that dealing on both Nim and qml sides with property which is stored in settings file like `float` results in an inconsistent values shared among those 2 sides, that won't be like that when we move to c++, so if there is a need we can get back to float then again
- contacts requests participates in calculating count badge for `Chat` section
- added new mechanism for adding notification in a more general way. `NotificationManager` class introduced, it takes into consideration all the settings which may be set in the `Settings->Notification` page. There is a private `processNotification` proc which keeps the logic, it determines whether a notification need to be displayed or not, what notification to display, whether to display `App` or `OS` notification, what level of anonymous to apply, whether to play sound or not and so...
- Signal `SIGNAL_DISPLAY_APP_NOTIFICATION` is added, once we have UI for stacked notification in the bottom right corner, they will listen to that signal in order to be displayed.
- Signal `SIGNAL_OS_NOTIFICATION_CLICKED` is added, it notifies the app that user has clicked certain OS notification and some actions are taken in that case:
  - if `NewMessage` OS notification is clicked, you will be pointed to appropriate section/chat/message and that message will be highlighted
  - if `NewMention` OS notification is clicked, you will be pointed to appropriate section/chat/message and that message will be highlighted
  - if `NewContactRequest` OS notification is clicked, you will be pointed to a contact request popup, so you can easily accept/reject new contact request
  - if `JoinCommunityRequest` OS notification is clicked, you will be pointed to a community membership requests popup of appropriate community, so you can easily accept/reject one into your private community
  - if `MyRequestToJoinCommunityAccepted` OS notification is clicked, you will be pointed to a appropriate community
  - if `MyRequestToJoinCommunityRejected` OS notification is clicked, nothing happens since there is no community to point you to

For the last 2 cases the rest is done, but adding notification is not completely done since unfurling shared community in a bubble message where we can request access from to join certain community doesn't work, and I wasn't able to check/test that in this PR. What need to be done in regards of that is to emit from appropriate places the following 2 signals:
```
singletonInstance.globalEvents.myRequestToJoinCommunityHasBeenAcccepted("Joining Community",
  fmt "You have been accepted into the {community.name}", community.id)
singletonInstance.globalEvents.myRequestToJoinCommunityHasBeenRejected("Joining Community",
  fmt "Your request to join the {community.name} community was declined", community.id)
```

One issue I see here, but not only here, but on other places where we have some text as well, is that we should find a way how to deal with translations on the Nim side.

### CODE REVIEW

File: src/app/core/notifications/notifications_manager.nim [hunk 1]
```diff
@@ -0,0 +1,170 @@
...
+
+    # Check anonymous level
+    if(singletonInstance.localAccountSensitiveSettings.getNotificationMessagePreviewSetting() == PREVIEW_ANONYMOUS):
+      finalTitle = "Status"
+      finalMessage = "You have a new message"
+    elif(singletonInstance.localAccountSensitiveSettings.getNotificationMessagePreviewSetting() == PREVIEW_NAME_ONLY):
+      finalMessage = "You have a new message"
+        
+    # Check whether to display APP or OS notification
+    if(singletonInstance.localAccountSensitiveSettings.getUseOSNotifications()):
```
Comment (jrainville) [inline src/app/core/notifications/notifications_manager.nim:157]: We only use OS notifications now. What we've seen with John is that we use OS notifications when the app is minimized, and we use "toast" notifications when the app is visible.

The old `useOSNotifications` setting can be deleted.

In summary, this condition can be changed to `if (app is minimized)` and you can delete the `useOSNotifications` setting and check box in the settings

File: src/app/global/app_signals.nim [hunk 2]
```diff
@@ -9,3 +9,16 @@ type
     sectionType*: SectionType
 
 const TOGGLE_SECTION* = "toggleSection"
+## Emmiting this signal will turn on section/s with passed `sectionType` if that section type is
+## turned off, or turn it off in case that section type is turned on.
```
Comment (jrainville) [inline src/app/global/app_signals.nim:13]: nit: putting the comment above the line is more standard to the way we do it usually

File: src/app/global/app_signals.nim [hunk 3]
```diff
@@ -9,3 +9,16 @@ type
...
+type 
+  ActiveSectionChatArgs* = ref object of Args
+    sectionId*: string
+    chatId*: string
+    messageId*: string
+
+const SIGNAL_MAKE_SECTION_CHAT_ACTIVE* = "makeSectionChatActive"
+## Emmiting this signal will switch the app to passed `sectionId`, after that if `chatId` is set
+## it will make that chat an active one and at the end if `messageId` is set it will point to
+## that message.
```
Comment (jrainville) [inline src/app/global/app_signals.nim:24]: nit: same here

File: src/app/modules/main/chat_section/chat_content/messages/controller.nim [hunk 4]
```diff
@@ -8,6 +8,7 @@ import ../../../../../../app_service/service/chat/service as chat_service
 import ../../../../../../app_service/service/message/service as message_service
 import ../../../../../../app_service/service/mailservers/service as mailservers_service
 import ../../../../../../app_service/service/eth/utils as eth_utils
+import ../../../../../global/app_signals
```
Comment (jrainville) [inline src/app/modules/main/chat_section/chat_content/messages/controller.nim:11]: Is this import used?

File: src/app/modules/main/chat_section/module.nim [hunk 5]
```diff
@@ -577,23 +589,41 @@ method onContactUnblocked*(self: Module, publicKey: string) =
...
+  let myPK = singletonInstance.userProfile.getPubKey()
+  for m in messages:
+    let contactDetails = self.controller.getContactDetails(m.`from`)
+    let renderedMessageText = self.controller.getRenderedText(m.parsedText)
+    let plainText = singletonInstance.utils.plainText(renderedMessageText)
+    if(m.isUserWithPkMentioned(myPK)):
+      singletonInstance.globalEvents.showMentionMessageNotification(contactDetails.displayName, plainText, 
+      self.controller.getMySectionId(), chatId, m.id)
+    else:
+      singletonInstance.globalEvents.showNormalMessageNotification(contactDetails.displayName, plainText,
```
Comment (jrainville) [inline src/app/modules/main/chat_section/module.nim:625]: `showMentionMessageNotification` and `showMentionMessageNotification` and really similar, maybe we can merge them and just add a flag `isMention`?

File: src/app/core/main.nim [hunk 6]
```diff
@@ -4,28 +4,29 @@ import
...
   signalsManager*: SignalsManager
+  notificationsManager*: NotificationsManager
 
 proc newStatusFoundation*(fleetConfig: string): StatusFoundation =
   result = StatusFoundation()
   result.events = createEventEmitter()
   result.fleetConfiguration = newFleetConfiguration(fleetConfig)
   result.threadpool = newThreadPool()
   result.signalsManager = newSignalsManager(result.events)
+  result.notificationsManager = newNotificationsManager(result.events)
```
Comment (jrainville) [inline src/app/core/main.nim:26]: Is this done before or after login? I'm asking because you removed the `onLoggedIn` code I had put in the service. 

If it is done before login, I've had some race conditions on Windows where the setup would be done too soon. I'll test it later to see if it still happens with your PR.

**Review by jrainville — CHANGES_REQUESTED** [review]
Good job.

Nothing I commented is super top priority, but I wanted to test this a bit and also get some answers before this is merged, so requesting changes is the best way.

**Comment by jrainville** [comment]
@saledjenic I just did a quick test on Windows. So far, I haven't experienced the race condition, so maybe it's good now.

Otherwise, the comment I made above about the app being minimized still stands and actually, the way you implemented it right now is "broken". What I mean is that currently, I **only** receive OS notifications when the app is visible, which is the opposite of the wanted behaviour. It's very annoying yo have a Windows pop up appear on new messages when you're already on the app 😆

File: src/app/core/notifications/details.nim [hunk 7]
```diff
@@ -0,0 +1,41 @@
+{.used.}
+
+import json
+
+type
+  NotificationType* {.pure.} = enum
```
[the remark this answers is not in the document]
Comment (saledjenic) [reply src/app/core/notifications/details.nim:6]: @jrainville we shouldn't have "unknown" type of notification, since we're sending only notification we are aware about.

File: src/app/core/notifications/notifications_manager.nim [hunk 8]
```diff
@@ -0,0 +1,170 @@
...
+
+  proc processNotification(self: NotificationsManager, title: string, message: string, details: NotificationDetails)
+
+  proc setup(self: NotificationsManager, events: EventEmitter) =
+    self.QObject.setup
+    self.events = events
+    self.osNotification = newStatusOSNotification()
+    self.soundManager = newStatusSoundManager()
+
+    signalConnect(self.osNotification, "notificationClicked(QString)", self, "onOSNotificationClicked(QString)", 2)
```
[the remark this answers is not in the document]
Comment (saledjenic) [reply src/app/core/notifications/notifications_manager.nim:52]: @jrainville  it comes from the `NimQml` and that `signalConnect` is actually a real `Qt::connection` so connecting 2 `QObject`s.

> Could our own events bus have worked?

For what I used here this is the approach, I used Qt signal/slot mechanism for this.

> My only concern is having to put slot functions in string can cause issues no?

No, that's what `signalConnect` expected, take a look into `NimQml`.

File: src/app/core/notifications/notifications_manager.nim [hunk 9]
```diff
@@ -0,0 +1,170 @@
...
+
+  proc showOSNotification(self: NotificationsManager, title: string, message: string, identifier: string) =
+    ## This method will add new notification to the OS Notification center. Param
+    ## "identifier" is used to uniquely define notification bubble.    
+    self.osNotification.showNotification(title, message, identifier)
+
+  proc onOSNotificationClicked(self: NotificationsManager, identifier: string) {.slot.} =
+    ## This slot is called once user clicks OS notificaiton bubble, "identifier"
+    ## contains data which uniquely define that notification.
+    debug "OS notification clicked", identifier=identifier
```
[the remark this answers is not in the document]
Comment (saledjenic) [reply src/app/core/notifications/notifications_manager.nim:82]: @jrainville I added that here deliberately, cause it is useful for tracking. No need for `trace` cause we're here when OS notification bubble is clicked and this slot is executed once we received signal sent from the c++ side from `dotherside`.

File: src/app/core/notifications/notifications_manager.nim (hunk 1 above)
Comment (saledjenic) [reply src/app/core/notifications/notifications_manager.nim:157]: @jrainville let's keep it like it is now, cause this state maps what we have at this moment in Settings->Notifications tab, once we get new requirements we will updated this. But primarily is to have at least what we had.

File: src/app/global/app_signals.nim (hunk 2 above)
Comment (saledjenic) [reply src/app/global/app_signals.nim:13]: @jrainville I somehow agree and that's the way how is recommended in c++, but in nim all comments I've seen (but for procs/methods) were written beneath the declaration, and I was leaded by that logic, but in general as you say?

File: src/app/modules/main/chat_section/module.nim (hunk 5 above)
Comment (saledjenic) [reply src/app/modules/main/chat_section/module.nim:625]: @jrainville that's other way to proceed and use `type` param for example to differ them, but I did it this way because of handling in `NoitificationManager` class. The effect at the end should be the same, but this way we don't need to include file where enum type is defined cause I wouldn't like to add some magic numbers like 1, 2, 3 for types.

File: ui/app/AppLayouts/Chat/views/ChatColumnView.qml [hunk 10]
```diff
@@ -336,72 +325,6 @@ Item {
...
-//                    } else {
-//                        //% "You have a new message"
-//                        message = qsTrId("you-have-a-new-message")
-//                    }
-
-//                    currentlyHasANotification = true
-
-//                    if (Qt.platform.os === "linux") {
-//                        // Linux Notifications are not implemented in Nim/C++ yet
-//                        return systemTray.showMessage(name, message, systemTray.icon.source, 4000)
```
[the remark this answers is not in the document]
Comment (saledjenic) [reply ui/app/AppLayouts/Chat/views/ChatColumnView.qml:388]: @jrainville using system tray and handling that manually in a native code is a bit tricky since it should be a single system tray per app.

File: src/app/core/notifications/notifications_manager.nim (hunk 8 above)
[the remark this answers is not in the document]
Comment (jrainville) [reply src/app/core/notifications/notifications_manager.nim:52]: > No, that's what signalConnect expected, take a look into NimQml

Sorry my question wasn't clear enough. I meant could it cause issues in the case where the slot gets renamed or adds a new parameter? If the string that points to that slot isn't uptated, would it fail to compile or would it crash on execution? If it's a compilation error, then that's fine, since we can correct it.

File: src/app/core/notifications/notifications_manager.nim (hunk 1 above)
Comment (jrainville) [reply src/app/core/notifications/notifications_manager.nim:157]: I wrote about this below, but we should really change it now. The OS notifications are not that useful in the state you made, because the app needs to be opened already and it's very annoying to receive OS notifications when you're already in the app.
Deleting the old code can be done later, but the check on app minimized would be good now.

File: src/app/core/notifications/notifications_manager.nim (hunk 8 above)
[the remark this answers is not in the document]
Comment (saledjenic) [reply src/app/core/notifications/notifications_manager.nim:52]: @jrainville whatever change one does there and if signal and slot do not match in their list of params or if signal/slot names are missed we will get that in a log as `QObject::connect` info with description of a real error (but the app will be compilable).

[the remark this answers is not in the document]
Comment (jrainville) [reply src/app/core/notifications/notifications_manager.nim:52]: Ah ok, as long as it doesn't crash, it's not too bad.

File: src/app/core/notifications/notifications_manager.nim [hunk 11]
```diff
@@ -0,0 +1,183 @@
...
+    ## This method determines whether a notification need to be displayed or not, what notification to display, whether
+    ## to display App or OS notification, what level of anonymous to apply, whether to play sound or not and so...
+
+    # I am not 100% sure about this.
+    # According to this:
+    # https://github.com/status-im/status-desktop/pull/4789#discussion_r805028513
+    # The app should use OS notification only in case it is not the active app or it's minimized at the moment 
+    # we're processing an event.
+    if(singletonInstance.localAccountSensitiveSettings.getUseOSNotifications() and 
+      app_isActive(singletonInstance.engine)):
```
Comment (jrainville) [inline src/app/core/notifications/notifications_manager.nim:142]: This condition can be moved to line 170, since we want to use OS notifications in the case the app is not at the front.
In other cases, we use local notifications (Toast).
The `useOSNotifications` is gonna be removed as well, since it was a legacy privacy feature that is no longer needed.

File: src/app/modules/main/module.nim [hunk 12]
```diff
@@ -662,3 +663,21 @@ method mnemonicBackedUp*[T](self: Module[T]) =
...
+  elif(details.notificationType == NotificationType.MyRequestToJoinCommunityAccepted):
+    self.controller.switchTo(details.sectionId, "", "")
+  elif(details.notificationType == NotificationType.MyRequestToJoinCommunityRejected):
+    info "There is no particular action clicking on a notification informing you about rejection to join community"
+
+method newCommunityMembershipRequestReceived*[T](self: Module[T], membershipRequest: CommunityMembershipRequestDto) =
+  let (contactName, _, _) = self.controller.getContactNameAndImage(membershipRequest.publicKey)
+  let community =  self.controller.getCommunityById(membershipRequest.communityId)
+  singletonInstance.globalEvents.newCommunityMembershipRequestNotification("New membership request",
+  fmt "{contactName} asks to join {community.name}", community.id)
```
Comment (jrainville) [inline src/app/modules/main/module.nim:683]: Would there be a way for QML to handle the text, since we can't translate those here?

File: src/app/core/notifications/notifications_manager.nim (hunk 11 above)
Comment (saledjenic) [reply src/app/core/notifications/notifications_manager.nim:142]: @jrainville I added it deliberately here, cause that way we're avoiding a lot of unnecessary checks if we're gonna return from this proc anyway. So patter do it sooner than later. So I wouldn't change this if you agree.

> The useOSNotifications is gonna be removed as well, since it was a legacy privacy feature that is no longer needed.

Yes, I agree, but cannot prepare code now for something what is yet to come. So we will change that when the time comes.

File: src/app/modules/main/module.nim (hunk 12 above)
Comment (saledjenic) [reply src/app/modules/main/module.nim:683]: @jrainville yes, that's something I mentioned in the first comment here. We should find a way how to handle that, but this is not the only place where we have some "text" on the nim side. So would be good to have a ticket for handling that, and sort that out everywhere anyhow (actually finding a solution) and once we completely move to c++ there will be lot easier.

**Review by jrainville — APPROVED** [review]

**Review by borismelnik — APPROVED** [review]
