### PR TITLE
fix(community/section): fix new community order in the sections

### LINKED ISSUE #4566: [base_bc] created community appears under Settings (gear) icon
### Description

Screenshot 2022-01-25 at 17 24 58

Community icon appears under Gear icon, which is incorrect.

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #4566

The problem was that when no community exists, there were no community section in the model, so the new section was added last.
There might be a follow up StatusQ fix to make the StatusAppNavBar a bit smarter or order better in a later case were we want the communities always second, but this fix works.

### CODE REVIEW

File: src/app/modules/main/module.nim [hunk 1]
```diff
@@ -534,7 +537,11 @@ method communityJoined*[T](
   self.communitySectionsModule[community.id].load(events, settingsService, contactsService, chatService, communityService, messageService, gifService)
 
   let communitySectionItem = self.createCommunityItem(community)
-  self.view.addItem(communitySectionItem)
+  if (firstCommunityJoined):
+    # If there are no other communities, add the first community after the Chat section in the model so that the order is respected
+    self.view.model().addItem(communitySectionItem, self.view.model().getItemIndex(conf.CHAT_SECTION_ID) + 1)
+  else:
+    self.view.model().addItem(communitySectionItem)
```
Comment (PascalPrecht) [inline src/app/modules/main/module.nim:544]: I'm not too familiar with the model creation for this part.. How exactly is ensured that the **next** community item (after the first one) is then also put in the correct position?
The correct position being: After the first/previous community item, but before the wallet/browser/settings item?

**Review by PascalPrecht — COMMENTED** [review]
@jrainville Not sure I'm in the position to approve this PR because of too many unknowns (from my side). There's a question I left that would be cool to be addressed.

Otherwise, @saledjenic I'm not sure from the top of my head what your changes were to `StatusAppNavBar` component in `StatusQ`. But prior to `base_bc`, or as of latest `master`, the component has dedicated "sections" for where community items should go.

Not entirely sure if this was removed, if yes, then maybe it's worth reintroducing such functionality?

File: src/app/modules/main/module.nim (hunk 1 above)
Comment (saledjenic) [reply src/app/modules/main/module.nim:544]: @PascalPrecht thanks for mention here. I've checked this so... 

> I'm not too familiar with the model creation for this part.. How exactly is ensured that the next community item (after the first one) is then also put in the correct position?

`StatusAppNavBar` component which is a part of `StatusQ` knows about 2 components (but both of them are actually `StatusNavBarTabButton`, the difference is only that the community button has a context menu) which are used for displaying "regular" and "community" button, and also it knows about `sectionModel` which contains a list of items (buttons) to display:
```
property var sectionModel: []
property Component regularNavBarButton
property Component communityNavBarButton
```
Now `StatusAppNavBarFilterModel` component with `id: navBarModel` (child component of `StatusAppNavBar` component) actually goes through the provided `sectionModel` and adds appropriate "regular" button to the `StatusAppNavBar` and the first time it encounters to the "community" button there is another `StatusAppNavBarFilterModel` with `id: navBarCommunityModel` which filters all communities from the `sectionModel` and display them one after another, and after that `StatusAppNavBarFilterModel` component with `id: navBarModel` continues with the rest of "regular" buttons.

And that's the key why the first and all community after it were added to the end of the list. Placing only the first community at the index 1 in the `sectionModel` regardless what is the index of other communities will be handled properly on the qml side.

File: src/app/modules/main/module.nim [hunk 2]
```diff
@@ -519,6 +519,9 @@ method communityJoined*[T](
   messageService: message_service.Service,
   gifService: gif_service.Service,
 ) =
+  var firstCommunityJoined = false
+  if (self.communitySectionsModule.len == 0):
```
Comment (saledjenic) [inline src/app/modules/main/module.nim:523]: @jrainville since you need this check only in a single place (line 540) you don't need to introduce `firstCommunityJoined` as a new variable, just use this check there.

**Review by saledjenic — APPROVED** [review]
@jrainville looks good. :)

**Review by anastasiyaig — APPROVED** [review]

File: src/app/modules/main/module.nim (hunk 2 above)
Comment (jrainville) [reply src/app/modules/main/module.nim:523]: Ah true, I could have done `if (self.communitySectionsModule.len == 1):` instead. I did it with the variable because I knew `communitySectionsModule` was modified below, but obviously `0 + 1 == 1` 😆
