### PR TITLE
Fixed issue doesn't show nickname on profileview in 1:1 chat

### LINKED ISSUE #1826: Doesn't show existing Nickname on view profile in 1:1 chat view
This contact has nickname, it is shown in `Profile->Contacts`
image

### PR DESCRIPTION
**Pull request by ace-smart**
Fixes #1826

### CODE REVIEW

File: src/app/chat/views/chat_item.nim [hunk 1]
```diff
@@ -64,6 +64,17 @@ QtObject:
   QtProperty[string] name:
     read = name
     notify = contactsUpdated
+
+  proc nickname*(self: ChatItemView): string {.slot.} = 
+    if self.chatItem != nil and self.chatItem.chatType.isOneToOne:
+      if self.status.chat.contacts.hasKey(self.chatItem.id) and self.status.chat.contacts[self.chatItem.id].hasNickname():
+        return self.status.chat.contacts[self.chatItem.id].localNickname
+    else:
+      result = ""
```
Comment (jrainville) [inline src/app/chat/views/chat_item.nim:73]:
```suggestion
    result = ""
```

**Review by jrainville — APPROVED** [review]

File: src/app/chat/views/chat_item.nim (hunk 1 above)
Comment (ace-smart) [reply src/app/chat/views/chat_item.nim]: Done :)
