### PR TITLE
fix(@desktop/chat): Push notification body contains only chat key

### LINKED ISSUE #3347: Push notification body contains only chat key when user is mentioned instead of preferences selected in profile
In profile section there are several options how PNs should be shown:

1. anonymous
2. name only
3. name and message

Screenshot 2021-09-01 at 10 28 02

The settings are not being taken into consideration, so when a desktop user receives a mention in a chat (lets say public chat), the incoming PN contains a chat key of the mentioned user, but not the name or name + text

Screenshot 2021-09-01 at 10 18 21

How to reproduce?

**In notifications settings of desktop app select option 3: name and message** (but the issue is applicable to any of options selected)

1. install an app to desktop
2. install an app to mobile
3. join the same public chat
4. add each other to contacts
5. collapse the desktop app so it is on background
6. from mobile, in the public chat mention a user on desktop
7. receive a push notification

**Expected result:** push notification body contains the text that matches the setting selection, either anonymous, or name only or name and message

**Version:** `Version: 0.1.0-beta.11 , master Build #1294 (31-Aug-2021 19:18:57)`, MacOS Big Sur 11.5.2

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
fix(@desktop/chat): Push notification body contains only chat key when user is mentioned

fixes #3347

### CODE REVIEW

File: src/app/chat/views/messages.nim [hunk 1]
```diff
@@ -101,6 +101,24 @@ QtObject:
 
     return updatedMessage
 
+  proc userNameOrAlias*(self: MessageView, pubKey: string): string {.slot.} =
+    if self.status.chat.contacts.hasKey(pubKey):
+      return status_ens.userNameOrAlias(self.status.chat.contacts[pubKey])
+    generateAlias(pubKey)
+
+  proc replacePubKeysWithMentions(self: MessageView, message: string, contacts: Table[string, Profile]): string =
```
Comment (alaibe) [inline src/app/chat/views/messages.nim:109]: Don't we already have this kind of function somewhere, for example when we render message? That would probably be better to reuse it

File: src/app/chat/views/messages.nim [hunk 2]
```diff
@@ -221,7 +239,7 @@ QtObject:
         let isEdit = msg.editedAt != "0" or msg.contentType == ContentType.Edit
         if not channel.muted and not isEdit and not isGroupSelf and not isMyInvite:
           let isAddedContact = channel.chatType.isOneToOne and self.isAddedContact(channel.id)
-          self.messageNotificationPushed(msg.id, channel.communityId, msg.chatId, escape_html(msg.text), msg.contentType.int, channel.chatType.int, msg.timestamp, msg.identicon, msg.userName, msg.hasMention, isAddedContact, channel.name)
+          self.messageNotificationPushed(msg.id, channel.communityId, msg.chatId, self.replacePubKeysWithMentions(msg.text, self.status.chat.contacts), msg.contentType.int, channel.chatType.int, msg.timestamp, msg.identicon, msg.userName, msg.hasMention, isAddedContact, channel.name)
```
Comment (alaibe) [inline src/app/chat/views/messages.nim:242]: Passing self.status.chat.contacts is not needed to be pass as a params, you can access it directly where you use it?

Also is it working for communities, the reason for my question is that I am not sure that all members of a communities are contacts

File: src/app/chat/views/messages.nim [hunk 3]
```diff
@@ -101,6 +101,24 @@ QtObject:
 
     return updatedMessage
 
+  proc userNameOrAlias*(self: MessageView, pubKey: string): string {.slot.} =
```
Comment (alaibe) [inline src/app/chat/views/messages.nim:104]: this function already exists in mutliple place, could we keep only one? At least do not add another one ;)

Comment (Khushboo-dev-cpp) [reply src/app/chat/views/messages.nim:104]: Yes already done. Realised after raising the review, I forgot to use it

Comment (Khushboo-dev-cpp) [reply src/app/chat/views/messages.nim:104]: Actually let me see if I can put it in one place too :)

File: src/app/chat/views/messages.nim (hunk 2 above)
Comment (Khushboo-dev-cpp) [reply src/app/chat/views/messages.nim:242]: code needs to be removed. so if the person is not a contact the alias is returned

File: src/app/chat/views/messages.nim (hunk 3 above)
Comment (Khushboo-dev-cpp) [reply src/app/chat/views/messages.nim]: not doing to right, but I have reused the api from message_format, seemed like the right place for the API to be

File: src/app/chat/views/messages.nim (hunk 2 above)
Comment (alaibe) [reply src/app/chat/views/messages.nim]: see this PR: https://github.com/status-im/status-desktop/pull/3555/files we also replace for non contact. In a community you can mention someone you are not a contact with

Comment (alaibe) [reply src/app/chat/views/messages.nim]: > This is the function we use currently, in case of communities and when the person is not a contact, we generate the alias and show that instead. and for that the self.status.chat.contacts is not needed, we simply use the public key to get the alias


Gotcha thanks for explaining ! ;)

File: src/app/chat/views/messages.nim [hunk 4]
```diff
@@ -221,7 +234,7 @@ QtObject:
         let isEdit = msg.editedAt != "0" or msg.contentType == ContentType.Edit
         if not channel.muted and not isEdit and not isGroupSelf and not isMyInvite:
           let isAddedContact = channel.chatType.isOneToOne and self.isAddedContact(channel.id)
-          self.messageNotificationPushed(msg.id, channel.communityId, msg.chatId, escape_html(msg.text), msg.contentType.int, channel.chatType.int, msg.timestamp, msg.identicon, msg.userName, msg.hasMention, isAddedContact, channel.name)
```
Comment (alaibe) [inline src/app/chat/views/messages.nim:224]: nit: no more escape_html

**Review by alaibe — APPROVED** [review]

File: src/app/chat/views/messages.nim (hunk 4 above)
Comment (Khushboo-dev-cpp) [reply src/app/chat/views/messages.nim:222]: escape_html not defined here and is used elsewhere. hence, didn't touch it
