### PR TITLE
12062 fix token holders

### LINKED ISSUE #12062: Communities: token holders list is not always populated
# Bug Report

## Description

Sometimes (with various frequency) the token holders list is empty. The only way to have it filled with actual holders is to restart the app.

[Kazam_screencast_00024.webm](https://github.com/status-im/status-desktop/assets/20650004/f697810f-7103-478a-b5c7-aa684c383e64)

## Steps to reproduce

1. Create community
2. Mint token
3. Airdrop to address (or member)
4. Rerun the app several times

#### Expected behavior
The token holders list always present holders.

#### Actual behavior
Every few starts the list is empty.

### Additional Information

- Status desktop version: master
- Operating System: Linux

### PR DESCRIPTION
**Pull request by endulab**
Add displaying holders for ERC20 - only community members.
Add json conversions test for some holders structs.

Displaying ERC721 holders worked every time for me. Could not reproduce the problem described in task.

Fix #12062

image

image

### CODE REVIEW

**Comment by MishkaRogachev** [comment]
I can confirm - ERC721 holders is working now

File: src/app_service/service/community_tokens/async_tasks.nim [hunk 1]
```diff
@@ -17,6 +17,15 @@ proc tableToJsonArray[A, B](t: var Table[A, B]): JsonNode =
     })
   return data
 
+proc balanceInfoToTable(jsonNode: JsonNode): Table[string, UInt256] =
+  for pair in jsonNode.pairs():
```
Comment (MishkaRogachev) [inline src/app_service/service/community_tokens/async_tasks.nim:21]: suggestion: can these pair names be more human readable?

File: src/app_service/service/community_tokens/async_tasks.nim [hunk 2]
```diff
@@ -227,20 +236,86 @@ type
 const fetchCollectibleOwnersTaskArg: Task = proc(argEncoded: string) {.gcsafe, nimcall.} =
   let arg = decode[FetchCollectibleOwnersArg](argEncoded)
   try:
-    let response = collectibles.getCollectibleOwnersByContractAddress(arg.chainId, arg.contractAddress)
+    var response = collectibles.getCollectibleOwnersByContractAddress(arg.chainId, arg.contractAddress)
```
Comment (MishkaRogachev) [inline src/app_service/service/community_tokens/async_tasks.nim:239]: Is check `if not response.error.isNil:` missing here?

File: src/app_service/service/community_tokens/async_tasks.nim [hunk 3]
```diff
@@ -227,20 +236,86 @@ type
...
+
+    var owners = fromJson(response.result, CollectibleContractOwnership).owners
+    owners = owners.filter(x => x.address != ZERO_ADDRESS)
+
+    response = communities_backend.getCommunityMembersForWalletAddresses(arg.communityId, arg.chainId)
```
Comment (MishkaRogachev) [inline src/app_service/service/community_tokens/async_tasks.nim:244]: ... and here :)

File: src/app/modules/main/communities/tokens/models/token_owners_model.nim [hunk 4]
```diff
@@ -83,7 +83,7 @@ QtObject:
       of ModelRole.WalletAddress:
         result = newQVariant(item.ownerDetails.address)
       of ModelRole.Amount:
-        result = newQVariant(item.amount)
+        result = newQVariant(item.amount.toString(10))
```
[the remark this answers is not in the document]
Comment (micieslak) [reply src/app/modules/main/communities/tokens/models/token_owners_model.nim:86]: hard to say what is better - plain number (which is very obvious for me in this case and easy to read) or named variable holding that value. How to call that constant, where to store it  - it may be needed in various files so one common would be needed. It entails additional imports... So I would opt for just plain number in this specific place as an exception from general rule of avoiding magic numbers ;)

File: src/backend/backend.nim [hunk 5]
```diff
@@ -306,3 +306,8 @@ rpc(fetchAllCurrencyFormats, "wallet"):
 
 rpc(hasPairedDevices, "accounts"):
   discard
+
+rpc(getBalancesByChain, "wallet"):
+  chainIds: seq[int]
+  addresses: seq[string]
+  tokenAddresses: seq[string]
```
Comment (micieslak) [inline src/backend/backend.nim:313]: new line at the end missing

File: test/nim/collectibles_types_conversions_test.nim [hunk 6]
```diff
@@ -0,0 +1,43 @@
...
+import backend/collectibles_types
+import app_service/service/community_tokens/community_collectible_owner
+include app_service/common/json_utils
+
+suite "collectibles types":
+
+  test "CollectibleOwner json conversion":
+
+    let oldBalance1 = CollectibleBalance(tokenId: stint.u256(23), balance: stint.u256(41))
+    let oldBalance2 = CollectibleBalance(tokenId: stint.u256(24), balance: stint.u256(42))
```
Comment (micieslak) [inline test/nim/collectibles_types_conversions_test.nim:13]: I would add some really big value here from string to check big ints handling as well.

File: ui/app/AppLayouts/Communities/controls/TokenHolderListItem.qml [hunk 7]
```diff
@@ -178,7 +179,7 @@ ItemDelegate {
 
                 TokenHolderNumberCell {
                     Layout.alignment: Qt.AlignRight
-                    text: LocaleUtils.numberToLocaleString(root.amount)
+                    text: LocaleUtils.numberToLocaleString(StatusQUtils.AmountsArithmetic.toNumber(root.amount, root.multiplierIndex))
```
Comment (micieslak) [inline ui/app/AppLayouts/Communities/controls/TokenHolderListItem.qml:182]: I would opt for using `amout` directly here:
```suggestion
                    text: amount
```
to make this component more general and do the formatting in the component that's using it (SortableTokenHoldersList) in this case. And no need to pass `multiplerIndex` then.

**Review by micieslak — APPROVED** [review]
Looks good in general, minor comments only.

File: src/app_service/service/community_tokens/async_tasks.nim (hunk 3 above)
Comment (endulab) [reply src/app_service/service/community_tokens/async_tasks.nim:244]: callPrivateRPC will raise an exception if there is a response error

File: src/app_service/service/community_tokens/async_tasks.nim [hunk 8]
```diff
@@ -227,20 +236,86 @@ type
...
+
+const fetchAssetOwnersTaskArg: Task = proc(argEncoded: string) {.gcsafe, nimcall.} =
+  let arg = decode[FetchAssetOwnersArg](argEncoded)
+  try:
+    let addressesResponse = communities_backend.getCommunityMembersForWalletAddresses(arg.communityId, arg.chainId)
+    var allCommunityMembersAddresses: seq[string] = @[]
+    for address in addressesResponse.result.keys():
+      allCommunityMembersAddresses.add(address)
+
+    let balancesResponse = backend.getBalancesByChain(@[arg.chainId], allCommunityMembersAddresses, @[arg.contractAddress])
```
Comment (MishkaRogachev) [inline src/app_service/service/community_tokens/async_tasks.nim:293]: I also use this endpoint, maybe we can generalise nim parsing of this response? For my the case, 'seq[WalletTokenDto]' should be fine

File: src/app_service/service/community_tokens/async_tasks.nim (hunk 2 above)
Comment (endulab) [reply src/app_service/service/community_tokens/async_tasks.nim:239]: rpc macro inside is using callPrivateRPC which will raise an exception if there is a response error

**Review by MishkaRogachev — APPROVED** [review]
