### PR TITLE
fix(wallet): fix token decimals when displaying activity amounts

### LINKED ISSUE #19653: Activity records are showing wrong amounts
Sending 10 STT results in wrong number of zeroes in activity, same for ETH

TXN example: https://sepolia.etherscan.io//tx/0x822d85807b54e2afff3e9e4b4d3da383380a4692bca22f65865b7f2f035e9294

Status UI: 

Image

### PR DESCRIPTION
**Pull request by friofry**
Transaction amounts in Activity view were displayed as raw values without
applying token decimals (e.g., "10 000 000 000B SNT" instead of "10 SNT").

Since tokens are indexed by tokenKey (format: `chainId-address`), the lookup failed when given a STT symbol. When the token wasn't found, `decimals` defaulted to `0

- Added `getTokenKey` helper to extract tokenKey from Token object
  with fallback to symbol for native tokens
- Added `getConvertedAmount`

https://github.com/user-attachments/assets/d905a69f-07ff-43ec-82b2-3ff666aa39a4

fixes #19653

### CODE REVIEW

File: src/app/modules/main/wallet_section/activity/entry.nim [hunk 1]
```diff
@@ -49,12 +49,17 @@ QtObject:
   proc isInTransactionType(self: ActivityEntry): bool =
     return self.metadata.activityType == backend_activity.ActivityType.Receive or self.metadata.activityType == backend_activity.ActivityType.Mint
 
-  proc extractCurrencyAmount(self: ActivityEntry, currencyService: Service): CurrencyAmount =
-    let usedToken = if self.isInTransactionType(): self.metadata.tokenIn.get() else: self.metadata.tokenOut.get()
-    let tokenKey = common_utils.createTokenKey(usedToken.chainId.int, $usedToken.address.get())
+  proc getTokenKey(token: Option[backend_activity.Token], symbol: Option[string]): string =
```
Comment (saledjenic) [inline src/app/modules/main/wallet_section/activity/entry.nim]: @friofry could we remove the symbol here as well as in the functions below affected by this change? We're referring to a token, guess symbol is not needed at all.

Comment (friofry) [reply src/app/modules/main/wallet_section/activity/entry.nim]: Done
