### PR TITLE
Fix: Crash when handling response without AC notifications

### LINKED ISSUE #12889: Segfault on accepting a contact request
# Bug Report

Application started to crash when receiving contact and community request

## Steps to reproduce

1. Create a new acc
2. Receive a CR
3. Accept it

#### Expected behavior

no segmentation fault

#### Actual behavior

Segmentation fault

### Additional Information

- Status desktop version: latest master
- Operating System: macos

### PR DESCRIPTION
**Pull request by MishkaRogachev**
Close #12889

### What does the PR do

Fixes the crash when accepting a CR and a few more random crashes

### Affected areas

Activity Center

### Screenshot of functionality (including design for comparison)

Screenshot 2023-11-28 at 18 14 25

### CODE REVIEW

**Review by caybro — APPROVED** [review]
LGTM

**Review by igor-sirotin — APPROVED** [review]

File: src/app_service/service/community/service.nim [hunk 1]
```diff
@@ -1669,7 +1669,7 @@ QtObject:
 
       let rpcResponse = Json.decode($rpcResponseObj["response"], RpcResponse[JsonNode])
       self.events.emit(SIGNAL_PARSE_RAW_ACTIVITY_CENTER_NOTIFICATIONS,
-        RawActivityCenterNotificationsArgs(activityCenterNotifications: rpcResponse.result{"activityCenterNotifications"}))
+        RawActivityCenterNotificationsArgs(activityCenterNotifications: rpcresponse.result["activityCenterNotifications"]))
```
Comment (jrainville) [inline src/app_service/service/community/service.nim:1672]:
```suggestion
        RawActivityCenterNotificationsArgs(activityCenterNotifications: rpcResponse.result["activityCenterNotifications"]))
```

**Review by jrainville — APPROVED** [review]
