### PR TITLE
Refactor AC Store & fix AC notifications count

### LINKED ISSUE #7654: Refactor AC data from chat's RootStore to AC's RootStore
In this issue notifications count calculations should also be fixed

### PR DESCRIPTION
**Pull request by MishkaRogachev**
Close #7654

### What does the PR do

Fix and generalise AC notifications couning 

### Affected areas

All (!)

### Screenshot of functionality (including design for comparison)

Screenshot 2022-10-26 at 19 51 44

### CODE REVIEW

**Comment by MishkaRogachev** [comment]
Reviewers! THis PR temporary based on https://github.com/status-im/status-desktop/pull/7771. Just review this commit, it will be merged to master

File: src/app/modules/main/activity_center/item.nim [hunk 1]
```diff
@@ -111,4 +113,15 @@ proc messageItem*(self: Item): MessageItem =
   return self.messageItem
 
 proc repliedMessageItem*(self: Item): MessageItem =
-  return self.repliedMessageItem
\ No newline at end of file
+  return self.repliedMessageItem
+
+# TODO: this logic should be moved to status-go
```
Comment (MishkaRogachev) [inline src/app/modules/main/activity_center/item.nim:118]: https://github.com/status-im/status-desktop/issues/8074

**Review by jrainville — APPROVED** [review]

**Review by saledjenic — APPROVED** [review]

**Review by elina2015 — APPROVED** [review]
Tested and approved
