### PR TITLE
fix launching multiple instances of status desktop including on windo…

### LINKED ISSUE #15493: Login failed. Please re-enter your password and try again error shown when syncing devices on Windows
# Bug Report

## Description

Login failed. Please re-enter your password and try again error shown when syncing devices on Windows

image

## Steps to reproduce

1. launch 2 instances on windows (i do it like this: `./Status.exe --datadir=~data/pr2 --LOG_LEVEL=DEBUG` in power shell for 2 app instances repsectfully with separate data folders)
2. get sync code from 1 instance
3. paste this code to second instance

#### Expected behavior

Devices are synced. User is able to login to both

#### Actual behavior

**Device 1:**

```
DBG 2024-07-08 14:43:11.921+03:00 local pairing event                        topics="signals-manager" tid=6412 file=pairing.nim:25 type=EventConnectionSuccess action=ActionPairingAccount error= event="{\"type\":\"localPairing\",\"event\":{\"type\":\"connection-success\",\"action\":2}}"
WRN 2024-07-08 14:43:11.924+03:00 qt warning                                 topics="qt" tid=6412 text="QML RowLayout: Binding loop detected for property \"width\"" file=qrc:/StatusQ/Controls/StatusBaseButton.qml:147 category=default
WRN 2024-07-08 14:43:11.924+03:00 qt warning                                 topics="qt" tid=6412 text="QML StatusButton: Binding loop detected for property \"implicitWidth\"" file=qrc:/app/AppLayouts/Profile/popups/SetupSyncingPopup.qml:239 category=default
DBG 2024-07-08 14:43:12.509+03:00 local pairing event                        topics="signals-manager" tid=6412 file=pairing.nim:25 type=EventTransferSuccess action=ActionPairingAccount error= event="{\"type\":\"localPairing\",\"event\":{\"type\":\"transfer-success\",\"action\":2}}"
DBG 2024-07-08 14:43:13.125+03:00 local pairing event                        topics="signals-manager" tid=6412 file=pairing.nim:25 type=EventConnectionSuccess action=ActionSyncDevice error= event="{\"type\":\"localPairing\",\"event\":{\"type\":\"connection-success\",\"action\":3}}"
DBG 2024-07-08 14:43:13.133+03:00 local pairing event                        topics="signals-manager" tid=6412 file=pairing.nim:25 type=EventTransferSuccess action=ActionSyncDevice error= event="{\"type\":\"localPairing\",\"event\":{\"type\":\"transfer-success\",\"action\":3}}"
DBG 2024-07-08 14:43:16.064+03:00 local pairing event                        topics="signals-manager" tid=6412 file=pairing.nim:25 type=EventConnectionSuccess action=ActionPairingInstallation error= event="{\"type\":\"localPairing\",\"event\":{\"type\":\"connection-success\",\"action\":4}}"
DBG 2024-07-08 14:43:16.065+03:00 local pairing event                        topics="signals-manager" tid=6412 file=pairing.nim:25 type=EventTransferSuccess action=ActionPairingInstallation error= event="{\"type\":\"localPairing\",\"event\":{\"type\":\"transfer-success\",\"action\":4}}"
DBG 2024-07-08 14:43:16.066+03:00 local pairing event                        topics="signals-manager" tid=6412 file=pairing.nim:25 type=EventReceivedInstallation action=ActionPairingInstallation error= event="{\"type\":\"localPairing\",\"event\":{\"type\":\"received-installation\",\"action\":4,\"data\":{\"identity\":\"0x04bde6bb78bdae93d800e80645ad5ed3ab7610eb5f3827b7d676edb72ab1bd0fd985e9479b0793379c9d480e0f7092f86cb239758219c914c73a5c815ffff420d3\",\"id\":\"09657b3d-b010-4177-b959-bfd761994cac\",\"version\":1,\"enabled\":true,\"timestamp\":1720449796088,\"metadata\":{\"name\":\"DESKTOP EPDIBBT \",\"deviceType\":\"windows\",\"fcmToken\":\"\"}}}}"
DBG 2024-07-08 14:43:16.067+03:00 local pairing event                        topics="signals-manager" tid=6412 file=pairing.nim:25 type=EventProcessSuccess action=ActionPairingInstallation error= event="{\"type\":\"localPairing\",\"event\":{\"type\":\"process-success\",\"action\":4}}"
WRN 2024-07-08 14:43:16.069+03:00 qt warning                                 topics="qt" tid=6412 text="QML RowLayout: Binding loop detected for property \"width\"" file=qrc:/StatusQ/Controls/StatusBaseButton.qml:147 category=default
WRN 2024-07-08 14:43:16.069+03:00 qt warning                                 topics="qt" tid=6412 text="QML StatusButton: Binding loop detected for property \"implicitWidth\"" file=qrc:/app/AppLayouts/Profile/popups/SetupSyncingPopup.qml:239 category=default
DBG 2024-07-08 14:43:39.606+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=6412 file=core.nim:27 rpc_method=wakuext_slowdownArchivesImport
WRN 2024-07-08 14:43:49.019+03:00 qt warning                                 topics="qt" tid=6412 text="Retrying to obtain clipboard." file=:0 category=qt.qpa.mime
INF 2024-07-08 14:43:54.425+03:00 shutting down...                           topics="status-app" tid=6412 file=nim_status_client.nim:221
INF 2024-07-08 14:43:54.425+03:00 logging out...                             topics="app-controller" tid=6412 file=app_controller.nim:295
WRN 2024-07-08 14:43:54.613+03:00 qt warning                                 topics="qt" tid=6412 text="TypeError: Cannot call method 'indexOf' of undefined" file=qrc:/app/mainui/Popups.qml:112 category=default
```

**Device 2:**
```
ERR 2024-07-08 14:43:17.998+03:00 error:                                     topics="accounts-service" tid=18028 file=service.nim:411 procName=verifyDatabasePassword errDesription="failed to set `journal_mode` pragma: file is not a database"
DBG 2024-07-08 14:43:17.998+03:00 account logged in                          topics="accounts-service" tid=18028 file=service.nim:437
WRN 2024-07-08 14:43:18.889+03:00 Error decoding signal                      topics="signals-manager" tid=18028 file=signals_manager.nim:49 err="Unknown signal received: mediaserver.started"
ERR 2024-07-08 14:43:19.048+03:00 node.crashed                               topics="signals-manager" tid=18028 file=signals_manager.nim:58 error="{\"type\":\"node.crashed\",\"event\":{\"error\":\"listen tcp 0.0.0.0:8545: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.\"}}"
ERR 2024-07-08 14:43:19.048+03:00 node.login                                 topics="signals-manager" tid=18028 file=signals_manager.nim:54 error="failed to start node: listen tcp 0.0.0.0:8545: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
DBG 2024-07-08 14:43:19.049+03:00 app state changed                          tid=18028 file=view.nim:122 state=StartupState
ERR 2024-07-08 14:43:19.049+03:00 login error                                topics="app-controller" tid=18028 file=module.nim:406 methodName=onNodeLogin errDesription="failed to start node: listen tcp 0.0.0.0:8545: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
DBG 2024-07-08 14:43:37.744+03:00 qt message                                 topics="qt" tid=18028 text="TODO: restart flow..." file=qrc:/app/AppLayouts/Onboarding/OnboardingLayout.qml:214 category=qml
INF 2024-07-08 14:43:39.608+03:00 shutting down...                           topics="status-app" tid=18028 file=nim_status_client.nim:221
INF 2024-07-08 14:43:39.608+03:00 logging out...  
```

### Additional Information

App logs:

[device1.log](https://github.com/user-attachments/files/16130856/app_20240708_143907.log)

[device2.log](https://github.com/user-attachments/files/16130829/app_20240708_143947.log)

- Status desktop version: latest master from Jul 8
- Operating System: Windows

### PR DESCRIPTION
**Pull request by kounkou**
### Description

fixes #15493

### What does the PR do

In previous [PR](https://github.com/status-im/status-desktop/pull/15168/files), the function to check if a port is busy was effective on Linux but failed to perform intended action on Windows altogether.

### Affected areas

- Starting another Status-desktop instance

### Impact on end user

- User can launch > 1 instance(s) of Status-desktop

### How to test

- Launch > 1 instance(s) of status-desktop and login in the application on Linux, MacOS, and Windows

### Tests performed

1- Launched 2 instances of status-desktop
2- Used Postman to test the websocket connection

Screenshot 2024-07-10 135814

### Risk 

- [x] Low risk: 2 devs MUST perform testing as specified above and attach their results as comments to this PR **before** merging.
- [ ] High risk: QA team MUST perform additional testing in the specified affected areas **before** merging.

### CODE REVIEW

File: src/app_service/common/net_utils.nim [hunk 1]
```diff
@@ -2,12 +2,12 @@ import net
...
+  defer: socket.close()
+
   try:
-    sock = newSocket()
-    sock.setSockOpt(OptReuseAddr, true)
-    sock.bindAddr(port)
-    sock.close()
-    return false
+    socket.connect("localhost", port)
+    result = true
```
Comment (jrainville) [inline src/app_service/common/net_utils.nim:11]: Isn't this reversed? Shouldn't it return `false` if it managed to connect?

Comment (kounkou) [reply src/app_service/common/net_utils.nim:11]: The logic is somewhat reversed here. If we connect it means something was listening on that port, hence the server is busy. And the other case can be deduced.
I'm still performing some tests... But it works.
In our case this logic holds since client (browser plugin) would connect to the port therefore it's sound.

**Comment by MishkaRogachev** [comment]
Tested 2 instances on Mac -  works fine

File: src/app_service/common/net_utils.nim (hunk 1 above)
Comment (jrainville) [reply src/app_service/common/net_utils.nim:11]: aah ok, yeah it's the opposite logic as before.

**Review by jrainville — APPROVED** [review]

**Comment by kounkou** [comment]
Pinged @Seitseman today to have a look.

**Review by Seitseman — APPROVED** [review]
LGTM
