### PR TITLE
fix(search): fix searching for hidden chats

### LINKED ISSUE #14961: User who does not have permissions to see hidden channel can search for it and see channel and messages for a moment
# Bug Report

## Description
User who does not have permissions to see hidden channel can search for it and see channel and messages for some seconds.

## Steps to reproduce
Log in with a user who has joined a community that has at least 1 hidden channel and this user does not have permission to view it. 
CTRL + F to search and type in the name of the hidden channel, example from the video shows "admin-only" channel
Click on the result to view the channel

#### Expected behavior
Results should not show channels that are hidden from this user.
Even if the channel is shown on the search result list, channel should not show its messages

#### Actual behavior
User who has no permissions to view a hidden channel can search for it and access for a glimpse this channel, even seeing the messages sent.
In the screen recording, on the left side I'm showing the user without permissions, and on the right, I'm showing the community owner user.
https://github.com/status-im/status-desktop/assets/68916150/f2c4c663-3694-479c-8f73-3bea3ff20155

### Additional Information
May be related to https://github.com/status-im/status-desktop/issues/14586

- Status desktop version: 2.29.0-rc4
- Operating System: Mac OS Sonoma 14.5

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #14961

[hidden-channels-search.webm](https://github.com/status-im/status-desktop/assets/11926403/5d037219-2a4e-4afe-b42d-0b108c95129e)

### CODE REVIEW

**Review by kounkou — APPROVED** [review]
Nice

File: src/app/modules/main/app_search/module.nim [hunk 1]
```diff
@@ -68,6 +68,9 @@ method getModuleAsVariant*(self: Module): QVariant =
 
 proc getChatSubItems(self: Module, chats: seq[ChatDto]): seq[location_menu_sub_item.SubItem] =
   for chatDto in chats:
+    if chatDto.isHiddenChat:
```
Comment (caybro) [inline src/app/modules/main/app_search/module.nim:71]: Maybe I'm once again confused by the NIM syntax but... this looks like you're calling a property but you only defined a function/proc in the DTO

**Review by endulab — APPROVED** [review]

File: src/app/modules/main/app_search/module.nim (hunk 1 above)
Comment (jrainville) [reply src/app/modules/main/app_search/module.nim:71]: Yeah, in Nim `()` is optional. So it does look like a property. I like it personally. It also saved 2 big characters :joy:
