### PR TITLE
fix(backup): fix Android backups by using SAF

### LINKED ISSUE #19082: [Android] Cannot change path for local backup
# Bug Report

## Description

Tapping `Browse` will trigger the folder selection popup and this one seems to work well. But the app is not updated with the new folder provided by the folder picker. Tapping `Backup now` is shown as successful, but the data in the app private folder.

### PR DESCRIPTION
**Pull request by jrainville**
### What does the PR do

Fixes #19082

status-go PR: https://github.com/status-im/status-go/pull/7066

**Disclaimer**: Almost all of the C++ and Java code was written by AI. Since I have close to zero knowledge of Android code, I had to use AI to help me. I feel like it did a good job and I tested on both Android and Linux and everything seems to work, but please review attentively to catch any bad code :pray: 

To fix the issue, we need to use the Storage Access Framework (SAF), meaning that Go cannot just write to disk. It needs to first write to the sandbox, then using native code, we can move that file from the sandbox to the allowed file.

This makes the backup work as expected.

The one thing missing is that the auto-backup will be done in the sandbox. I'll add another issue to send a signal on auto-backup so that the client can process it and use the SAF to save the file.

### Affected areas

- New SAF helper files. For now only used for the Backup, but they can be reused for any other file writes we need to do outside of the sandbox.
- devices/general service
- url utils to add a helper function that displays Android paths nicely (replaces `file:///data/data/app.status.mobile/files/content:/com.android.externalstorage.documents/tree/primary%3ADocuments%2Fpatate\` with `Internal Storage/Documents/backup`)

### Architecture compliance

- [x] I am familiar with the [application architecture](/docs/architecture.md) and agreed good practices.
My PR is consistent with this document: [QML Architecture Guidelines](/guidelines/QML_ARCHITECTURE_GUIDE.md)

### Screencapture of the functionality

Android backup:

[backup-android.webm](https://github.com/user-attachments/assets/6a458adc-b85d-4929-b276-26cc8f69860b)

Linux backup (showing it still works as expected):

[linux-bkp.webm](https://github.com/user-attachments/assets/5aa0b495-488a-413e-8bb3-f982dce37ae5)

### Impact on end user

Fixes the issue on Android

### How to test

- Ben on Android and go to backup settings. Choose a folder and press Backup now

### Risk 

Medium. It adds new C++ and Java files that I didn't write myself. They shouldn't be used in any other context than on Android, but should be thoroughly reviewed just in case.

### CODE REVIEW

File: src/app/android/safutils.nim [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+      free(cast[pointer](cstr))
+
+  proc safWriteBytesToUri*(documentUri: string, data: openArray[byte]): bool =
+    if data.len == 0:
+      return false
+    return statusq_saf_writeBytesToUri(documentUri.cstring, unsafeAddr data[0], cint(data.len))
+
+  proc safOpenWritableFd*(documentUri: string): int =
+    return int(statusq_saf_openWritableFd(documentUri.cstring))
+
```
Comment (alexjba) [inline src/app/android/safutils.nim]: Is this used anywhere?

File: src/app/android/safutils.nim [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+  proc statusq_saf_createFileInTree*(treeUri, mime, displayName: cstring): cstring {.cdecl, importc: "statusq_saf_createFileInTree".}
+  proc statusq_saf_writeBytesToUri*(documentUri: cstring, data: pointer, length: cint): bool {.cdecl, importc: "statusq_saf_writeBytesToUri".}
+  proc statusq_saf_openWritableFd*(documentUri: cstring): cint {.cdecl, importc: "statusq_saf_openWritableFd".}
+  proc statusq_saf_copyFromPathToTree*(srcPath, treeUri, mime, displayName: cstring): cstring {.cdecl, importc: "statusq_saf_copyFromPathToTree".}
+  {.pop.}
+
+  proc safTakePersistablePermission*(treeUri: string) =
+    statusq_saf_takePersistablePermission(treeUri.cstring)
+
+  proc safCreateFileInTree*(treeUri, mime, displayName: string): string =
```
Comment (alexjba) [inline src/app/android/safutils.nim]: unused?

File: src/app/android/safutils.nim [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+    let cstr = statusq_saf_createFileInTree(treeUri.cstring, mime.cstring, displayName.cstring)
+    if cstr.isNil:
+      return ""
+    # Copy into Nim string, then free the C allocation
+    result = $cast[cstring](cstr)
+    when declared(free):
+      free(cast[pointer](cstr))
+
+  proc safWriteBytesToUri*(documentUri: string, data: openArray[byte]): bool =
```
Comment (alexjba) [inline src/app/android/safutils.nim]: unused?

File: src/app_service/service/settings/service.nim [hunk 4]
```diff
@@ -1103,7 +1105,13 @@ QtObject:
     if self.settings.backupPath == value:
       return
     try:
-      let formattedPath = singletonInstance.utils.fromPathUri(value)
+      var formattedPath = value
```
Comment (alexjba) [inline src/app_service/service/settings/service.nim:1095]: Do we need the same on `write` to make sure it succeeds ? Not 100%, but I think the permissions could change. On my device for example the app permissions are dropped if I don't use the app for some time.

File: src/app/android/safutils.nim [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+
+  proc safOpenWritableFd*(documentUri: string): int =
+    return int(statusq_saf_openWritableFd(documentUri.cstring))
+
+  proc safCopyFromPathToTree*(srcPath, treeUri, mime, displayName: string): string =
+    let cstr = statusq_saf_copyFromPathToTree(srcPath.cstring, treeUri.cstring, mime.cstring, displayName.cstring)
+    if cstr.isNil:
+      return ""
+    result = $cast[cstring](cstr)
+    when declared(free):
```
Comment (alexjba) [inline src/app/android/safutils.nim]: I think it should be always declared. And if it's not declared then it's a problem and it might be better for the lib that allocates to provide a `free` as well.

File: ui/StatusQ/src/urlutils.cpp [hunk 6]
```diff
@@ -118,3 +120,99 @@ QUrl UrlUtils::urlFromUserInput(const QString &input) const
...
+            const QString docId = QUrl::fromPercentEncoding(docIdEnc.toUtf8()); // e.g. "primary:Documents/patate"
+
+            const int colon = docId.indexOf(':');
+            const QString volume = colon >= 0 ? docId.left(colon) : QString();
+            QString relPath = colon >= 0 ? docId.mid(colon + 1) : docId;
+            while (relPath.startsWith('/')) relPath.remove(0, 1);
+
+            QString volLabel;
+            if (volume.compare(QLatin1String("primary"), Qt::CaseInsensitive) == 0)
+                volLabel = QLatin1String("Internal storage");
```
Comment (caybro) [inline ui/StatusQ/src/urlutils.cpp]: These should ideally get localized, as we show them to the user, so:


```suggestion
                volLabel = tr("Internal storage");
```

Same for below

File: ui/StatusQ/src/safutils_android.cpp [hunk 7]
```diff
@@ -0,0 +1,189 @@
...
+    );
+    const QString s = jResult.isValid() ? jResult.toString() : QString();
+    if (s.isEmpty())
+        return nullptr;
+    QByteArray utf8 = s.toUtf8();
+    char* out = static_cast<char*>(std::malloc(static_cast<size_t>(utf8.size()) + 1));
+    if (!out)
+        return nullptr;
+    std::memcpy(out, utf8.constData(), static_cast<size_t>(utf8.size()));
+    out[utf8.size()] = '\0';
```
Comment (caybro) [inline ui/StatusQ/src/safutils_android.cpp]: A more convenient way is sth like:
```cpp
 QString tmp = "test";
 QByteArray text = tmp.toUtf8();
 char *data = new char[text.size() + 1];
 strcpy(data, text.data());
 return data; // <--  needs to be freed with `delete [] data;`
```

File: ui/StatusQ/src/safutils_android.cpp [hunk 8]
```diff
@@ -0,0 +1,189 @@
...
+    const auto jMime = jString(mime ? mime : "application/octet-stream");
+    const auto jName = jString(displayName ? displayName : "backup.bkp");
+
+    QJniObject ctx = getAndroidContext();
+    QJniObject jResult = QJniObject::callStaticObjectMethod(
+        "app/status/mobile/SafHelper",
+        "copyFromPathToTree",
+        "(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;",
+        ctx.object(), jSrc.object<jstring>(), jTree.object<jstring>(), jMime.object<jstring>(), jName.object<jstring>()
+    );
```
Comment (caybro) [inline ui/StatusQ/src/safutils_android.cpp:61]: I think there's an easier way to call static Java methods now: https://doc.qt.io/qt-6/qjniobject.html#callStaticMethod

Sth like (not tested :)

```cpp
QJniObject jResult = QJniObject::callStaticObjectMethod<SafHelper, jstring>("copyFromPathToTree", ctx.object(), jSrc, jTree, jMime, jName)
```

File: ui/StatusQ/src/urlutils.cpp [hunk 9]
```diff
@@ -118,3 +120,99 @@ QUrl UrlUtils::urlFromUserInput(const QString &input) const
...
+                volLabel = QLatin1String("Storage");
+
+            return relPath.isEmpty() ? volLabel : volLabel + QLatin1Char('/') + relPath;
+        }
+
+        // Fallback to Java helper if present
+        const char* c = statusq_saf_getReadableTreePath(content.toUtf8().constData());
+        if (c) {
+            QString s = QString::fromUtf8(c);
+            std::free((void*)c);
```
Comment (caybro) [inline ui/StatusQ/src/urlutils.cpp]:
```suggestion
            delete [] c;
```

File: ui/StatusQ/src/urlutils.cpp [hunk 10]
```diff
@@ -118,3 +120,99 @@ QUrl UrlUtils::urlFromUserInput(const QString &input) const
...
+                volLabel = QLatin1String("SD card");
+            else
+                volLabel = QLatin1String("Storage");
+            return relPath.isEmpty() ? volLabel : volLabel + QLatin1Char('/') + relPath;
+        }
+
+        const char* c = statusq_saf_getReadableTreePath(path.toUtf8().constData());
+        if (c) {
+            QString s = QString::fromUtf8(c);
+            std::free((void*)c);
```
Comment (caybro) [inline ui/StatusQ/src/urlutils.cpp]:
```suggestion
            delete [] c;
```

File: ui/StatusQ/src/safutils_android.cpp (hunk 7 above)
Comment (caybro) [reply ui/StatusQ/src/safutils_android.cpp]: (and above, anywhere where you play around with `malloc` and `memcpy` :)

**Review by caybro — COMMENTED** [review]
Just some suggestions, mostly for the C++ code, otherwise looks good 💪

File: ui/StatusQ/src/safutils_android.cpp (hunk 8 above)
Comment (caybro) [reply ui/StatusQ/src/safutils_android.cpp:61]: Ie. the signature and other boring stuff should get deduced at compile time

File: src/app_service/service/settings/service.nim (hunk 4 above)
Comment (jrainville) [reply src/app_service/service/settings/service.nim:1095]: Ah I didn't know. I can add the same line on the write just in case!

File: src/app/android/safutils.nim (hunk 5 above)
Comment (jrainville) [reply src/app/android/safutils.nim]: I get the following compile error without it :shrug: 

```
/home/jonathan/dev/status-desktop2/src/app/android/safutils.nim(23, 5) Error: undeclared identifier: 'free'
```

File: ui/StatusQ/src/safutils_android.cpp (hunk 7 above)
Comment (jrainville) [reply ui/StatusQ/src/safutils_android.cpp]: Cool it works! What do you mean by "needs to be freed with `delete [] data;`" though? In the calling function, I need to free the returned value once I'm done with it?

Comment (caybro) [reply ui/StatusQ/src/safutils_android.cpp]: Nope, on the usage side, see below

File: ui/StatusQ/src/urlutils.cpp (hunk 9 above)
Comment (caybro) [reply ui/StatusQ/src/urlutils.cpp]: Here

File: src/app/android/safutils.nim (hunk 5 above)
Comment (jrainville) [reply src/app/android/safutils.nim]: Ok, so I replaced it with `dos_chararray_delete` instead. Seems like `free` just didn't exist so we would have had a small leak

File: ui/StatusQ/src/safutils_android.cpp (hunk 8 above)
Comment (jrainville) [reply ui/StatusQ/src/safutils_android.cpp:61]: It didn't work, even with some help from the AI. I'll leave it as is for now. Maybe we can recheck another time

File: src/app/android/safutils.nim (hunk 5 above)
Comment (alexjba) [reply src/app/android/safutils.nim]: You’ll probably need the c import

‘ proc free(p: pointer) {.importc, header: "<stdlib.h>".}’

Comment (jrainville) [reply src/app/android/safutils.nim]: Cool it works! Thanks, I'll remove the change in nimqml then

**Review by micieslak — APPROVED** [review]
Tested, works fine. C++ code looks "raw", like Cpp98 code, quite hard to readd. But nothing really suspicious detected.
