### PR TITLE
fix: correct member list for new community channels

### LINKED ISSUE #14442: Members list is empty on new channel
# Bug Report

## Description

user 1: Create open community
user 2: View community without joining it
user 1: Add new channel
user 2: View new channel without joining community

Members list is populated when viewing other channels but not when viewing the new one.

#### Expected behavior

Members list to be populated for new channel

### Additional Information

- Status desktop version: 2.28.1 RC1
- Operating System: Mac

### PR DESCRIPTION
**Pull request by MishkaRogachev**
Close #14442
Waits https://github.com/status-im/status-go/pull/5190

### What does the PR do

Temporary workaround for showing members for a new channels (and in a few more rare cases)
Should be refactored in https://github.com/status-im/status-desktop/issues/14219

### Affected areas

Chats, Communities

### Screenshot of functionality

https://github.com/status-im/status-desktop/assets/2522130/dfac425a-afed-49ca-b5a5-bbe2ceff12bb

### CODE REVIEW

File: src/app/modules/main/chat_section/chat_content/users/controller.nim [hunk 1]
```diff
@@ -124,8 +124,12 @@ proc getChat*(self: Controller): ChatDto =
...
     let myCommunity = self.getMyCommunity()
-    return myCommunity.getCommunityChat(self.chatId).members
-  else:
+    # TODO: when a new channel is added, chat may arrive earlier and we have no up to date community yet
+    # see log here: https://github.com/status-im/status-desktop/issues/14442#issuecomment-2120756598
+    # should be resolved in https://github.com/status-im/status-desktop/issues/14219
+    let members = myCommunity.getCommunityChat(self.chatId).members
+    if members.len > 0:
+      return members
     return self.chatService.getChatById(self.chatId).members
```
Comment (jrainville) [inline src/app/modules/main/chat_section/chat_content/users/controller.nim:133]: In theory, since you changed status-go to return the members in the "normal" chat, I think the code above to get from the community is no longer useful, but I think it's safer to wait for the refactor just in case.

**Review by jrainville — APPROVED** [review]

File: src/app/modules/main/chat_section/chat_content/users/controller.nim (hunk 1 above)
Comment (MishkaRogachev) [reply src/app/modules/main/chat_section/chat_content/users/controller.nim:133]: It should be ok for new chats, but old ones will be empty until new `CommunityDescription` arrives
