### PR TITLE
(desktop/fix) Fix missing crown after ownership transfer

### LINKED ISSUE #13218: There is no crown for the new community owner after the community transfership
# Bug Report

## Description

There is no crown for the new community owner after the community transfership

## Steps to reproduce

1. Create a community and mint owner token
2. Transfer ownership token
3. Finalize the ownership transfer
4. Check if the user marked in the members list as a community owner (via crown)

#### Expected behavior

The crown is displayed near the new owner of the community

#### Actual behavior

No crown near the new owner of the community

image

- Status desktop version: latest master
- Operating System: macos

### PR DESCRIPTION
**Pull request by kounkou**
### Description

This PR solves the missing crown problem after an ownership transfer

fixes #13218 https://github.com/status-im/status-desktop/issues/13218

### What does the PR do

The PR triggers the update of the memberRole property in the user model to be able to update the presence of a crown on a member.

### Affected areas

- Chat

### Screenshot of functionality (including design for comparison)

[solution-missing-crown.webm](https://github.com/status-im/status-desktop/assets/2589171/45da74b1-eb35-431f-8f93-fc8febb1dc90)

### CODE REVIEW

File: src/app_service/service/community/service.nim [hunk 1]
```diff
@@ -519,6 +519,13 @@ QtObject:
     # checking length is sufficient - communityTokensMetadata list can only extend
     return communityTokens.len != prevCommunityTokens.len
 
+  proc updateMemberRole(self: Service, community, prevCommunity: CommunityDto) =
```
Comment (kounkou) [inline src/app_service/service/community/service.nim:522]: This procedure looks like O(M * N) a priori, where M is the number of chats and N is the number of members, however, I estimated that the actual time complexity is less that O(M * N) because when the signal is caught inside the controller, we do apply a filtering based on the chat. This makes the algorithm be ~O(N)

**Comment by kounkou** [comment]
After updating current development branch with latest, I can't Finalize Ownership transfer flow. I am seeing a endless loading icon.

Screenshot from 2024-02-15 21-55-59

File: src/app_service/service/community/service.nim [hunk 2]
```diff
@@ -519,6 +519,13 @@ QtObject:
...
+    if community.memberRole != prevCommunity.memberRole:
```
Comment (endulab) [inline src/app_service/service/community/service.nim:523]: Unfortunately, you can't compare memberRole like this. This would work only if YOU lost or received ownership. Because this parameter tells what is your member role in the community. But if you want to catch that some other member lost or received owner role then you need to compare who is the owner in _community_ and in _prev_.
If the owner is different then you need to update both: old owner and new owner.

**Review by endulab — CHANGES_REQUESTED** [review]

File: src/app_service/service/community/service.nim (hunk 2 above)
Comment (kounkou) [reply src/app_service/service/community/service.nim:523]: > Unfortunately, you can't compare memberRole like this. This would work only if YOU lost or received ownership. Because this parameter tells what is your member role in the community. But if you want to catch that some other member lost or received owner role then you need to compare who is the owner in _community_ and in _prev_.
> 
> If the owner is different then you need to update both: old owner and new owner.

Hi there, thanks for your comment @endulab 

> This would work only if YOU lost or received ownership.

This is my intent here. Because the same code is used on emit and reception, this code will be triggered only if the current client lost or gained ownership. I am handling the other cases separately.

Comment (endulab) [reply src/app_service/service/community/service.nim:523]: Why separately? Isn't it the same algorithm?

Comment (kounkou) [reply src/app_service/service/community/service.nim:523]: You are right, this should be handled at the same place. Let me have a look at this.

File: src/app_service/service/community/service.nim [hunk 3]
```diff
@@ -519,6 +519,16 @@ QtObject:
     # checking length is sufficient - communityTokensMetadata list can only extend
     return communityTokens.len != prevCommunityTokens.len
 
+  proc findOwner(members: seq[ChatMember]): ChatMember =
```
Comment (MishkaRogachev) [inline src/app_service/service/community/service.nim:522]: maybe it's better to add this function as method to `CommunityDto`?

**Review by MishkaRogachev — APPROVED** [review]
Nice work!

File: src/app_service/service/community/service.nim [hunk 4]
```diff
@@ -533,6 +543,13 @@ QtObject:
 
       let prev_community = self.communities[community.id]
```
[the remark this answers is not in the document]
Comment (kounkou) [reply src/app_service/service/community/service.nim:544]: I have refactored the names in the `handleCommunityUpdates` function, need to continue effort as cc work on other functions too.

**Review by endulab — APPROVED** [review]
