### PR TITLE
fix(chat_section): reset activeItem when the last channel is removed

### LINKED ISSUE #6536: The public chat doesn't look good after leaving a chat
# Bug Report

## Steps to reproduce
1. Sign in and join some public chat
2. Leave the chat and join the same or another one
3. Join one more public chat

#### Expected behavior
1. The name of the public chat is shown in the Secondary Nav menu
2. Another joined chat is shown in the Secondary Nav menu
#### Actual behavior
1. The name of the public chat is not shown in the Secondary Nav menu
2. Another joined chats are not shown in the Secondary Nav menu

https://user-images.githubusercontent.com/14942081/179870204-5c7b9f2b-d6e8-4a36-82c7-8936e1055db9.mov

image
### Additional Information
- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2347/
- Operating System: macOS Monterey

### PR DESCRIPTION
**Pull request by jrainville**
### What does the PR do

Fixes #6536

This doesn't fix the exact issue stated in the ticket, because I couldn't reproduce the same symptom, but I did have a problem with the same step.

My problem was that when leaving a channel and then rejoining the same one, the right panel (messages) would stay empty.

The reason was that when we leave a channel, we usually change the active item to the first channel in the list, but if there is no other channel, because we left the last channel, the active item stays the same. ie if you left `#test` as the last channel you ever had, the active item `id` would stay as `#test`, so when rejoining `#test`, the activeChannel props wouldn't update, since the ID is the same.

### CODE REVIEW

**Comment by jrainville** [comment]
This is an issue that usually I would let a dev test, but since @elina2015 you were having a different symptom, I'll let you test to see if this PR fixes your issue as well.

**Review by elina2015 — APPROVED** [review]
Tested and approved

File: src/app/modules/main/chat_section/controller.nim [hunk 1]
```diff
@@ -252,7 +252,9 @@ proc setActiveItemSubItem*(self: Controller, itemId: string, subItemId: string)
   self.activeItemId = itemId
   self.activeSubItemId = subItemId
 
-  self.messageService.asyncLoadInitialMessagesForChat(self.getActiveChatId())
+  let chatId = self.getActiveChatId()
+  if chatId == "":
+    self.messageService.asyncLoadInitialMessagesForChat(chatId)
```
Comment (osmaczko) [inline src/app/modules/main/chat_section/controller.nim:257]: :eyes: this logic looks super suspicious -> "when chat id is empty load messages for it"

Comment (jrainville) [reply src/app/modules/main/chat_section/controller.nim:257]: :facepalm:

Comment (jrainville) [reply src/app/modules/main/chat_section/controller.nim]: Fixed

**Review by osmaczko — APPROVED** [review]

**Comment by jrainville** [comment]
@saledjenic or @igor-sirotin could you give a quick review please
