### PR TITLE
fix(Wallet): Try extending the string lifetime until `Json.decode` finishes

### LINKED ISSUE #17398: Wallet: infinite loading of assets even using proxy
https://github.com/user-attachments/assets/9bf4b7cd-921d-463e-a926-37c938fcce1a

The issue is not going away until i restart the app. I saw a lot of console warning as well

```
DBG 2025-02-26 09:42:14.985Z [threadpool task thread] initiating task   topics="task-threadpool" tid=152038260 file=threadpool.nim:60 messageType=BuildTokensTaskArg:ObjectType threadid=152038260 task="{\"$type\":\"BuildTokensTaskArg:ObjectType\",\"accounts\":[\"0xe47885025e986b4296ef7617d612bf743a5ac68b\"],\"storeResult\":true,\"vptr\":105553156833248,\"slot\":\"onAllTokensBuilt\"}"
DBG 2025-02-26 09:42:14.985Z NewBE_callPrivateRPC                       topics="rpc" tid=152038260 file=core.nim:27 rpc_method=wallet_fetchOrGetCachedWalletBalances
WRN 2025-02-26 09:42:15.035Z qt warning                                 topics="qt" tid=152038212 text="TypeError: Cannot call method 'replace' of undefined" file=qrc:/StatusQ/Core/Utils/Utils.qml:280 category=default
WRN 2025-02-26 09:42:15.035Z qt warning                                 topics="qt" tid=152038212 text="Unable to assign [undefined] to QString" file=qrc:/app/AppLayouts/Wallet/views/AssetsDetailView.qml:106 category=default
WRN 2025-02-26 09:42:15.035Z qt warning                                 topics="qt" tid=152038212 text="SyntaxError: JSON.parse: Parse error" file=qrc:/imports/shared/stores/CommunityTokensStore.qml:17 category=default
WRN 2025-02-26 09:42:15.035Z qt warning                                 topics="qt" tid=152038212 text="TypeError: Cannot call method 'getMySectionId' of undefined" file=qrc:/app/AppLayouts/Chat/stores/RootStore.qml:651 category=default
WRN 2025-02-26 09:42:15.035Z qt warning                                 topics="qt" tid=152038212 text="TypeError: Cannot read property 'permissionsCheckOngoing' of undefined" file=qrc:/app/AppLayouts/Chat/stores/RootStore.qml:175 category=default
WRN 2025-02-26 09:42:15.035Z qt warning                                 topics="qt" tid=152038212 text="TypeError: Cannot read property 'loadingHistoryMessagesInProgress' of undefined" file=qrc:/app/AppLayouts/Chat/stores/RootStore.qml:169 category=default
WRN 2025-02-26 09:42:15.036Z qt warning                                 topics="qt" tid=152038212 text="TypeError: Cannot read property 'contactRequestsModel' of undefined" file=qrc:/app/AppLayouts/Chat/stores/RootStore.qml:167 category=default
WRN 2025-02-26 09:42:15.036Z qt warning                                 topics="qt" tid=152038212 text="TypeError: Cannot read property 'overviewChartData' of undefined" file=qrc:/app/AppLayouts/Chat/stores/RootStore.qml:152 category=default
WRN 2025-02-26 09:42:15.036Z qt warning                                 topics="qt" tid=152038212 text="Unable to assign [undefined] to int" file=qrc:/app/AppLayouts/Chat/stores/RootStore.qml:145 category=default
WRN 2025-02-26 09:42:15.036Z qt warning                                 topics="qt" tid=152038212 text="TypeError: Cannot read property 'allChannelsAreHiddenBecauseNotPermitted' of undefined" file=qrc:/app/AppLayouts/Chat/stores/RootStore.qml:142 category=default
WRN 2025-02-26 09:42:15.036Z qt warning                                 topics="qt" tid=152038212 text="TypeError: Cannot read property 'model' of undefined" file=qrc:/app/AppLayouts/Chat/stores/RootStore.qml:39 category=default
WRN 2025-02-26 09:42:15.036Z qt warning                                 topics="qt" tid=152038212 text="TypeError: Cannot read property 'allTokenRequirementsMet' of undefined" file=qrc:/imports/shared/stores/PermissionsStore.qml:100 category=default
WRN 2025-02-26 09:42:15.036Z qt warning                                 topics="qt" tid=152038212 text="Unable to assign [undefined] to QAbstractItemModel*" file=qrc:/imports/shared/stores/PermissionsStore.qml:84 category=default
WRN 2025-02-26 09:42:15.036Z qt warning                                 topics="qt" tid=152038212 text="Unable to assign [undefined] to QAbstractItemModel*" file=qrc:/imports/shared/stores/PermissionsStore.qml:65 category=default
WRN 2025-02-26 09:42:15.036Z qt warning                                 topics="qt" tid=152038212 text="Unable to assign [undefined] to QAbstractItemModel*" file=qrc:/imports/shared/stores/PermissionsStore.qml:45 category=default
WRN 2025-02-26 09:42:15.036Z qt warning                                 topics="qt" tid=152038212 text="Unable to assign [undefined] to QAbstractItemModel*" file=qrc:/imports/shared/stores/PermissionsStore.qml:26 category=default
WRN 2025-02-26 09:42:15.036Z qt warning                                 topics="qt" tid=152038212 text="TypeError: Cannot read property 'permissionsModel' of undefined" file=qrc:/imports/shared/stores/PermissionsStore.qml:18 category=default
WRN 2025-02-26 09:42:15.036Z qt warning                                 topics="qt" tid=152038212 text="TypeError: Cannot read property 'activeItem' of undefined" file=qrc:/app/AppLayouts/Chat/stores/RootStore.qml:162 category=default
WRN 2025-02-26 09:42:15.036Z qt warning                                 topics="qt" tid=152038212 text="Unable to assign [undefined] to bool" file=qrc:/app/AppLayouts/Profile/stores/ProfileStore.qml:34 category=default
WRN 2025-02-26 09:42:15.036Z qt warning                                 topics="qt" tid=152038212 text="Unable to assign [undefined] to QString" file=qrc:/app/AppLayouts/Profile/stores/ProfileStore.qml:30 category=default
WRN 2025-02-26 09:42:15.036Z qt warning                                 topics="qt" tid=152038212 text="TypeError: Cannot read property 'areTestNetworksEnabled' of null" file=qrc:/app/AppLayouts/Wallet/stores/RootStore.qml:65 category=default
WRN 2025-02-26 09:42:15.036Z qt warning                                 topics="qt" tid=152038212 text="TypeError: Cannot read property 'allNetworks' of null" file=qrc:/app/AppLayouts/Wallet/stores/TokensStore.qml:55 category=default
```

### PR DESCRIPTION
**Pull request by alexjba**
### What does the PR do

Presumably closes #17398 

### Affected areas

Wallet tokens

### CODE REVIEW

File: src/app_service/service/token/service.nim [hunk 1]
```diff
@@ -282,7 +282,9 @@ QtObject:
       if tokensResult.isNil or tokensResult.kind == JNull:
         raise newException(Exception, "Error in response of getting supported tokens list")
 
-      let tokenList =  Json.decode($tokensResult, TokenListDto, allowUnknownFields = true)
+      let tokenResultStr = $tokensResult
```
Comment (dlipicar) [inline src/app_service/service/token/service.nim:285]: please add a comment explaining what this is supposed to do so nobody removes it by mistake

**Review by dlipicar — APPROVED** [review]

**Review by alaibe — APPROVED** [review]

**Review by saledjenic — APPROVED** [review]
