### PR TITLE
fix(@desktop/communities): Fix computing balances for different chain…

### LINKED ISSUE #10308: Fix computing balance for different chains during deployment

### PR DESCRIPTION
**Pull request by endulab**
Fix computing balances for different chains during deployment.

Balances are computed correctly now.

Fix #10308

### Screenshot of functionality (including design for comparison)

image

### CODE REVIEW

File: src/app_service/service/community_tokens/service.nim [hunk 1]
```diff
@@ -252,13 +252,14 @@ QtObject:
 
   proc onSuggestedFees*(self:Service, response: string) {.slot.} =
     let responseJson = response.parseJson()
+    const ethSymbol = "ETH"
```
Comment (jrainville) [inline src/app_service/service/community_tokens/service.nim:255]: You can even move that at the top of this file. We can reuse it a lot.

**Review by jrainville — APPROVED** [review]
LGTM

**Review by noeliaSD — APPROVED** [review]
