### PR TITLE
fix(@desktop): Fix crash when opening change status dialog

### LINKED ISSUE #6415: Crash when opening ChangeStatus dialog
The crash was provided by merging 2 related prs:

- https://github.com/status-im/status-desktop/pull/6058
- https://github.com/status-im/status-desktop/pull/6341

### PR DESCRIPTION
**Pull request by endulab**
Fixes #6415

### What does the PR do

Fixes crash when opening change user status dialog

### Screenshot of functionality (including design for comparison)

image

### CODE REVIEW

File: src/app/modules/main/module.nim [hunk 1]
```diff
@@ -736,7 +734,7 @@ method resolvedENS*[T](self: Module[T], publicKey: string, address: string, uuid
 
 method contactsStatusUpdated*[T](self: Module[T], statusUpdates: seq[StatusUpdateDto]) =
   for s in statusUpdates:
-    let status = OnlineStatus(s.statusType.int)
```
Comment (endulab) [inline src/app/modules/main/module.nim:739]: This conversion crashed because of incompatible types.

**Comment by endulab** [comment]
@borismelnik can you please test it ?

**Review by osmaczko — APPROVED** [review]

**Review by PascalPrecht — APPROVED** [review]
Changes LGTM

**Review by saledjenic — APPROVED** [review]
