### PR TITLE
fix(contacts): remove isContact, use isMutualContact or isAdded indead

### LINKED ISSUE #6220: Sending a contact request immediatly adds mutual contact icon to their profile in the memberlist
# Bug Report

## Steps to reproduce

1. join a community with some members
2. click on a member that is not a mutual contact, and send a contact request

result: a mutual contact icon is immediately added next to their name
expected result: only after they accept the mutual contact request should the icon be added next to their name

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #6220

Fixes the issue with the mutual contact icon showing when just added.
It also does a huge cleanup of the codebase to remove isContact and replace it with either isAdded, when we care only about if we added, or isMutualContact if we want the contact to be mutual
Also fixes an issue with the MessageContextMenu not reflecting the added state correctly.

Asking for QA testing on this one, since it touches contacts all over the app. I made sure to double check my changes to make sure to use isAdded and isMutualContact appropriately, but the reason why I did this change is because `isContact` was used in both contexts, so it was confusing.
Anyway, all that to say, make sure the contact list, states and other interactions still work as expected.

### CODE REVIEW

File: src/app/modules/shared_models/user_item.nim [hunk 1]
```diff
@@ -32,7 +32,7 @@ type
     colorId: int
     colorHash: string
     onlineStatus: OnlineStatus
-    isContact: bool
+    isMutualContact: bool
```
Comment (osmaczko) [inline src/app/modules/shared_models/user_item.nim:35]:
```suggestion
    isContact: bool
```

File: src/app/modules/shared_models/user_model.nim [hunk 2]
```diff
@@ -12,7 +12,7 @@ type
     ColorId
     ColorHash
     OnlineStatus
-    IsContact
+    IsMutualContact
```
Comment (osmaczko) [inline src/app/modules/shared_models/user_model.nim:15]:
```suggestion
    IsContact
```

File: ui/app/AppLayouts/Chat/panels/ChatRequestMessagePanel.qml [hunk 3]
```diff
@@ -12,7 +12,7 @@ Item {
     width: parent.width
     height: childrenRect.height
 
-    property bool isContact
+    property bool isContactAdded
```
Comment (osmaczko) [inline ui/app/AppLayouts/Chat/panels/ChatRequestMessagePanel.qml:15]:
```suggestion
    property bool isUserAdded
```

File: ui/app/AppLayouts/Chat/views/ChatColumnView.qml [hunk 4]
```diff
@@ -55,7 +55,7 @@ Item {
     property Timer timer: Timer { }
     property var userList
     property var contactDetails: Utils.getContactDetailsAsJson(root.activeChatId)
-    property bool isContact: root.contactDetails.isContact
+    property bool isContactAdded: root.contactDetails.isAdded
```
Comment (osmaczko) [inline ui/app/AppLayouts/Chat/views/ChatColumnView.qml:58]:
```suggestion
    property bool isUserAdded: root.userDetails.isAdded
```

File: ui/app/AppLayouts/Chat/views/ChatView.qml [hunk 5]
```diff
@@ -177,7 +177,7 @@ StatusAppThreePanelLayout {
         confirmationText: qsTr("Are you sure you want to remove this contact?")
         onConfirmButtonClicked: {
             let pk = chatColumn.contactToRemove
-            if (Utils.getContactDetailsAsJson(pk).isContact) {
+            if (Utils.getContactDetailsAsJson(pk).isAdded) {
```
Comment (osmaczko) [inline ui/app/AppLayouts/Chat/views/ChatView.qml:180]:
```suggestion
            if (Utils.getUserDetailsAsJson(pk).isAdded) {
```
we should probably create a separate task to fix status-desktup codebase naming in regards to contact vs user

**Review by osmaczko — CHANGES_REQUESTED** [review]
Thanks for fixing that :+1: 

Please change all occurrences of `isMutualContact` back to `isContact` (democracy here :D)

**Comment by osmaczko** [comment]
> @osmaczko updated. 

Great, thank you.

> getContactDetailsAsJson and contactDetails will be updated in another PR. The number of changes here is already pretty high..

Of course, I haven't expected anything else! -> "[we should probably create a separate task to fix status-desktup codebase naming in regards to contact vs user](https://github.com/status-im/status-desktop/pull/6375#discussion_r915640976)"

**Review by elina2015 — APPROVED** [review]

**Review by noeliaSD — APPROVED** [review]
