### PR TITLE
fix(@wallet): switch account being slow

### LINKED ISSUE #7430: Wallet -> Main screen: switching between accounts is visibly slow
### Description

1. open wallet
2. add any new account (generate new one)
3. switch between accounts

As result, the switching is super slow, so it is visible

https://user-images.githubusercontent.com/82375995/191006021-c3a3df4f-968a-40e8-8fb4-22433d9ebcc9.mov

### PR DESCRIPTION
**Pull request by alaibe**
Now when switching account all remote call are non blocking

fixes #7430

### CODE REVIEW

**Review by stefandunca — APPROVED** [review]

File: src/app_service/service/collectible/service.nim [hunk 1]
```diff
@@ -1,47 +1,77 @@
...
+    result.QObject.setup
+    result.events = events
+    result.threadpool = threadpool
+    result.networkService = networkService
+
+  proc init*(self: Service) =
+    discard
+
+  proc onGetCollections*(self: Service, response: string) {.slot.} =
+    let responseObj = response.parseJson
```
Comment (saledjenic) [inline src/app_service/service/collectible/service.nim:51]: @alaibe this is an operation which may fail (in case of any incorrectly structured json) and crash the app, please add try/catch block for it.
Especially cause from the line `15` from `async_tasks.nim` you're returning an empty string which will throw an error in `parseJson` function for sure.

**Review by saledjenic — CHANGES_REQUESTED** [review]

File: src/app_service/service/collectible/service.nim (hunk 1 above)
Comment (saledjenic) [reply src/app_service/service/collectible/service.nim:51]: @alaibe here is a short and quick example, showing that: https://play.nim-lang.org/#ix=4fWQ

**Review by saledjenic — APPROVED** [review]
