### PR TITLE
Fix: Mobile MVP UI and feature fixes

### LINKED ISSUE #19050: AppMain: Node section is not visible in the primary (left) navbar
### Description

Image

I was able to activate it only via the Homepage

### PR DESCRIPTION
**Pull request by caybro**
### What does the PR do

This PR polishes the Mobile MVP experience across onboarding, account creation, navbar context menus, wallet settings, and Android file access. It also includes small Storybook and i18n housekeeping updates.

Here is a revised description of the pull request, with references to the issues fixed by each commit:

- **AppMain: Restore the forgotten Node section** Fixes #19050
- **Set `production` variant as default for mobile builds**: Updated the mobile Makefile to set the `production` variant by default, aligning it with the desktop variant. This change impacts logging and enables development features in the app ([Commit](https://github.com/status-im/status-desktop/commit/41311414b7230bd45be271031eb0d115cd08dc55)).
- **Use `nproc` in MAKEFLAGS for CI**: Replaced hardcoded usage of 4 CPU cores with `nproc` to dynamically determine available cores ([Commit](https://github.com/status-im/status-desktop/commit/7696408ddf5f0827f3fd70992c2e1e0a12d09b19)).
- **Fix file access on Android for tablets**: Adjusted permissions and file-saving paths to improve file access support on Android tablets. Fixes [#18076](https://github.com/status-im/status-desktop/issues/18076) and Fixes [#19053](https://github.com/status-im/status-desktop/issues/19053) ([Commit](https://github.com/status-im/status-desktop/commit/0deb35448fda6f5d0195798b9ddee21650812dfc)).
- **Adjust Beta tag padding in Wallet settings**: Fixed padding issues for the Beta tag in Wallet settings. Iterates on [#19068](https://github.com/status-im/status-desktop/issues/19068) ([Commit](https://github.com/status-im/status-desktop/commit/132da8e473b685b92a55811d80e7eea7f99891b9)).
- **Ensure Send button appears for Payments in Chat Input**: Updated StatusChatInput to display the Send button for Payments. Fixes [#19049](https://github.com/status-im/status-desktop/issues/19049) ([Commit](https://github.com/status-im/status-desktop/commit/5a8537065953daac9134f9dbf274271d4e7c752e)).
- **Fix layout issues in Advanced Settings view**: Corrected layout issues and adjusted the StatusSettingsLineButton component for mobile. Fixes [#19072](https://github.com/status-im/status-desktop/issues/19072) ([Commit](https://github.com/status-im/status-desktop/commit/116da8f1cd3b01a56a27ee074f8eb3af4fcda117)).
- **Simplify popup menu handling in Navbar**: Refactored context menu code to simplify handling of the Mute submenu and other interactions. Fixes [#19070](https://github.com/status-im/status-desktop/issues/19070) ([Commit](https://github.com/status-im/status-desktop/commit/e4293fdd6d5fd27b4cb2edaf3551f6ef0f590fe6)).
- **Fix token list display in Wallet Settings**: Resolved issues where the token list showed zero tokens and removed unused signals. Fixes [#19071](https://github.com/status-im/status-desktop/issues/19071) ([Commit](https://github.com/status-im/status-desktop/commit/6c506ce9de48a5d593c9bd0500e45874ee75d472)).
- **Fix tooltip rendering in StatusToolTip**: Adjusted size calculations and removed hardcoded metrics for better tooltip rendering. Fixes [#19059](https://github.com/status-im/status-desktop/issues/19059) ([Commit](https://github.com/status-im/status-desktop/commit/1485fc51b2047cd8ba506c8beeba96ffdcd94d6d)).
- **Reduce memory usage in Home Screen**: Replaced Glow effect with RectangularShadow for a faster and less resource-intensive rendering. Fixes [#19086](https://github.com/status-im/status-desktop/issues/19086) ([Commit](https://github.com/status-im/status-desktop/commit/50797925fea5a90f3bbb248e0a7006d7da877d6f)).
- **Fix layout for Login Screen profile selector**: Updated the LoginScreen to avoid using a bottom sheet for profile selection ([Commit](https://github.com/status-im/status-desktop/commit/6a269c5c75181b69ccaccefd0e32078303ceb2f5)).
- **Add bottom margin for Onboarding SafeArea**: Resolved issues by adding a bottom margin to the Onboarding SafeArea. Fixes [#19074](https://github.com/status-im/status-desktop/issues/19074) ([Commit](https://github.com/status-im/status-desktop/commit/9765fb6492a4d9c247bcedca93998b2b0b7c825d)).
- **Ignore generated files for i18n and update TS**: Excluded TS files within build directories ([Commit](https://github.com/status-im/status-desktop/commit/2f211a1f45de0fe567f7f2cefc40ab00a549fbe2)).
- **Update macOS minimum version for Storybook**: Raised the minimum macOS version to 14.0 ([Commit](https://github.com/status-im/status-desktop/commit/4b465c5793f422ba1e701d80908cf6814b819cb1)).

This PR introduces a series of fixes and improvements across different features, optimizing performance, usability, and developer experience. Each commit addresses specific issues or introduces enhancements as detailed above.

- Needs https://github.com/status-im/dotherside/pull/100
- Needs https://github.com/status-im/nimqml/pull/68

### Affected areas

App

### Architecture compliance

- [x] I am familiar with the [application architecture](/docs/architecture.md) and agreed good practices.
My PR is consistent with this document: [QML Architecture Guidelines](/guidelines/QML_ARCHITECTURE_GUIDE.md)

### Screencapture of the functionality

Profile image saved:
image

Sending an image in chat:
image

About (`production` logo):
image

Advanced section (fixed layout, disabled Browser/Debug parts):
image

Home screen (new hover/glow effect):
image

Token list (fixed popup header; icon/name/count/timestamp):
image

Node section restored:
image

Cascading submenu fixed:
image

Send button enabled for transactions:
image

Wallet beta tag alignment fixed:
image

### Impact on end user

Stuff works

### How to test

TBD

### Risk 

low

### CODE REVIEW

File: mobile/scripts/buildNimStatusClient.sh [hunk 1]
```diff
@@ -58,6 +58,7 @@ env $FEATURE_FLAGS ./vendor/nimbus-build-system/scripts/env.sh nim c "${PLATFORM
     --cpu:"$CARCH" \
     --noMain:on \
     -d:release \
+    -d:production \
```
Comment (caybro) [inline mobile/scripts/buildNimStatusClient.sh:61]: Not sure it's the correct place but we were missing this in the mobile build @alexjba

Comment (alexjba) [reply mobile/scripts/buildNimStatusClient.sh:61]: It is!

File: ui/i18n/qml_base_lokalise_en.ts [hunk 2]
```diff
@@ -10908,6 +10916,11 @@
       <comment>KeycardEnterPinPage</comment>
       <translation>PIN correct</translation>
     </message>
+    <message>
+      <source>Keycard blocked</source>
+      <comment>KeycardEnterPinPage</comment>
+      <translation>Keycard blocked</translation>
```
Comment (caybro) [inline ui/i18n/qml_base_lokalise_en.ts:10958]: The string is clearly there:
https://github.com/status-im/status-desktop/blob/59bb23eef4ffec42601a439cdc6ddfd0433d1a82/ui/app/AppLayouts/Onboarding/pages/KeycardEnterPinPage.qml#L126-L129

Yet I'm getting ui-tests failure here; looks like a bug in Qt's `lupdate` which got fixed in Qt 6.10.0 which I'm running locally 😢

Comment (caybro) [reply ui/i18n/qml_base_lokalise_en.ts:10958]: Ah, it's inside the backticks... maybe that's the bug which got fixed; older versions seem to ignore such strings

File: mobile/android/qt6/AndroidManifest.xml [hunk 3]
```diff
@@ -13,19 +13,19 @@
     <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
     <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
     <uses-permission android:name="android.permission.VIBRATE" />
+    <uses-permission android:name="android.permission.USE_BIOMETRIC" />
+
+    <!-- features -->
+    <uses-feature android:name="android.hardware.camera" android:required="false" />
```
Comment (caybro) [inline mobile/android/qt6/AndroidManifest.xml:17]: CHECKME

File: ci/Jenkinsfile.tests-ui [hunk 4]
```diff
@@ -70,8 +70,10 @@ pipeline {
 
     stage('Check Translations') {
       steps {
-        script {
-          checkTranslations()
+        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
```
Comment (caybro) [inline ci/Jenkinsfile.tests-ui:73]: I made the TS file check optional; there's a Qt bug which doesn't catch `qsTr()` calls inside JS backticks

CC @siddarthkay @markoburcul

Comment (caybro) [reply ci/Jenkinsfile.tests-ui:73]: Like here: https://github.com/status-im/status-desktop/blob/59bb23eef4ffec42601a439cdc6ddfd0433d1a82/ui/app/AppLayouts/Onboarding/pages/KeycardEnterPinPage.qml#L126-L129

File: src/app/modules/main/profile_section/advanced/module.nim [hunk 5]
```diff
@@ -63,7 +63,7 @@ method onFleetSet*(self: Module) =
   quit(QuitSuccess) # quits the app TODO: change this to logout instead when supported
 
 method getLogDir*(self: Module): string =
-  return url_fromLocalFile(constants.LOGDIR)
```
Comment (caybro) [inline src/app/modules/main/profile_section/advanced/module.nim:66]: `fromLocalFile` would give wrong result on Android

File: src/app_service/service/chat/service.nim [hunk 6]
```diff
@@ -428,7 +427,6 @@ QtObject:
         slot: "onAsyncSendImagesDone",
         chatId: chatId,
         imagePathsJson: imagePathsJson,
-        tempDir: TMPDIR.replace("\\", "\\\\"), # Escape backslashes so that the JSON sent is valid (Windows issue)
```
Comment (caybro) [inline src/app_service/service/chat/service.nim:431]: `TMPDIR` doesn't work on Android

File: ui/app/AppLayouts/HomePage/delegates/HomePageGridItem.qml [hunk 7]
```diff
@@ -43,9 +43,12 @@ AbstractButton {
 
     signal pinRequested
 
-    layer.enabled: true
-    layer.effect: Glow {
```
Comment (caybro) [inline ui/app/AppLayouts/HomePage/delegates/HomePageGridItem.qml:47]: `Glow` effect removed @alexjba

File: ui/app/AppLayouts/Profile/views/wallet/MainView.qml [hunk 8]
```diff
@@ -150,7 +150,7 @@ Column {
             id: accountOrderBetaTag
             anchors.verticalCenter: parent.verticalCenter
             anchors.left: parent.left
-            anchors.leftMargin: accountOrderItem.statusListItemTitle.width + Theme.bigPadding
+            anchors.leftMargin: accountOrderItem.statusListItemTitle.width + parent.leftPadding + Theme.bigPadding
```
Comment (caybro) [inline ui/app/AppLayouts/Profile/views/wallet/MainView.qml:153]: Beta tag padding fixed

File: ui/app/AppLayouts/Profile/views/AdvancedView.qml [hunk 9]
```diff
@@ -125,9 +137,11 @@ SettingsContentBase {
             }
 
             StatusSettingsLineButton {
+                visible: root.isBrowserEnabled // feature flag
```
Comment (caybro) [inline ui/app/AppLayouts/Profile/views/AdvancedView.qml:140]: Browser disabled on mobile

File: ui/app/mainui/AppMain.qml [hunk 10]
```diff
@@ -1234,6 +1234,11 @@ Item {
                         value: Constants.appSection.browser
                         enabled: d.isBrowserEnabled
                     }
+                    ValueFilter {
```
Comment (caybro) [inline ui/app/mainui/AppMain.qml:1242]: Node section restored

File: ui/i18n/CMakeLists.txt [hunk 11]
```diff
@@ -13,6 +13,7 @@ file(GLOB_RECURSE
     COLLECTED_SOURCE_FILES
     ${CMAKE_SOURCE_DIR}/../*.qml
 )
+list(FILTER COLLECTED_SOURCE_FILES EXCLUDE REGEX "${CMAKE_SOURCE_DIR}/../StatusQ/build/.*" )
```
Comment (caybro) [inline ui/i18n/CMakeLists.txt:16]: Ignore `qsTr()` from build dirs

File: ui/imports/shared/status/StatusChatInput.qml [hunk 12]
```diff
@@ -1440,7 +1440,7 @@ Rectangle {
                                 implicitWidth: 32
                                 icon.name: "send"
                                 type: StatusQ.StatusFlatRoundButton.Type.Tertiary
-                                visible: messageInputField.length > 0 || control.fileUrlsAndSources.length > 0
+                                visible: messageInputField.length > 0 || control.fileUrlsAndSources.length > 0 || !!control.paymentRequestModel
```
Comment (caybro) [inline ui/imports/shared/status/StatusChatInput.qml]: Send button enabled for Pay requests; however the message doesn't get sent because it has no text; this looks like a bug in either NIM or status-go @jrainville

File: ui/StatusQ/src/StatusQ/Controls/StatusNavBarTabButton.qml [hunk 13]
```diff
@@ -62,36 +62,14 @@ StatusIconTabButton {
...
     }
 
-    Loader {
-        id: popupMenuSlot
-        sourceComponent: statusNavBarTabButton.popupMenu
-        active: false
-        onLoaded: {
-            popupMenuSlot.item.closeHandler = function () {
-                statusNavBarTabButton.highlighted = false
-                popupMenuSlot.active = false
```
Comment (caybro) [inline ui/StatusQ/src/StatusQ/Controls/StatusNavBarTabButton.qml:92]: This would close the submenu if not using cascaded menus, e.g on Android; each menu/submenu is a toplevel one

File: ui/StatusQ/src/StatusQ/Popups/Dialog/StatusFileDialog.qml [hunk 14]
```diff
@@ -18,7 +18,7 @@ QObject {
     property alias currentFolder: dlg.currentFolder
 
     property string picturesShortcut: Utils.isIOS ? "assets-library://" :
-                            StandardPaths.writableLocation(StandardPaths.PicturesLocation)
+                            StandardPaths.standardLocations(StandardPaths.PicturesLocation)[0]
```
Comment (caybro) [inline ui/StatusQ/src/StatusQ/Popups/Dialog/StatusFileDialog.qml]: Don't need a writable dir for reading files (images)

File: ui/StatusQ/src/systemutilsinternal.cpp [hunk 15]
```diff
@@ -1,23 +1,21 @@
-#ifdef Q_OS_ANDROID
-#include <QJniObject>
-#include <QtCore/qnativeinterface.h>
-#endif
```
Comment (caybro) [inline ui/StatusQ/src/systemutilsinternal.cpp:4]: Duplicate include

File: ui/app/AppLayouts/Profile/views/wallet/MainView.qml (hunk 8 above)
Comment (micieslak) [reply ui/app/AppLayouts/Profile/views/wallet/MainView.qml:153]: Looks a bit hacky to be honest. On narrow screen it looks ok but on wider one the space seems to be too wide. Something with this calculation must be wrong if bigpadding is not enough and stuff was overlapping. It should not overlap even with 0 margin.

Comment (caybro) [reply ui/app/AppLayouts/Profile/views/wallet/MainView.qml:153]: Ah, I think I know why, the StatusList item has this hardcoded:
```qml
    property real leftPadding: 16
    property real rightPadding: 16
```
which doesn't scale properly on hires displays; the extra `Theme.bigPadding` will probably not be needed then

**Comment by caybro** [comment]
> Nice work! Although I have a few findings while testing
> 
> > Ensure Send button appears for Payments in Chat Input: Updated StatusChatInput to display the Send button for Payments. Fixes #19049 ([Commit](https://github.com/status-im/status-desktop/commit/5a8537065953daac9134f9dbf274271d4e7c752e)).
> 
> The send button will show up when adding a payment request. But it does nothing. Cannot send the message

Yeah I mentioned that in the comments; there's a separate bug somewhere in NIM/status-go in that it won't let the user send the message w/o text

> 
> > Simplify popup menu handling in Navbar: Refactored context menu code to simplify handling of the Mute submenu and other interactions. Fixes #19070 ([Commit](https://github.com/status-im/status-desktop/commit/e4293fdd6d5fd27b4cb2edaf3551f6ef0f590fe6)).
> 
> I can use the submenu. But once the submenu is clicked there will be some menu leftovers on the screen
> 
> See the video

I'm not getting that... and frankly looks like a Qt redraw bug :(

>  Screen_Recording_20251027_092236_Status.mp4 
> > Fix file access on Android for tablets: Adjusted permissions and file-saving paths to improve file access support on Android tablets. Fixes #18076 and Fixes #19053 ([Commit](https://github.com/status-im/status-desktop/commit/0deb35448fda6f5d0195798b9ddee21650812dfc)).
> 
> The image save and upload needs a little bit of work
> 
> 1. Save doesn't work for me. Maybe we should use a simpler approach where `save` would just > save the file in Downloads
> 
> Video
> 
>  Screen_Recording_20251027_091456_Files.mp4 

Yup, separate code flow which I only discovered later; I can fix in a separate task/PR

> 2. Not sure if it's a nitpick or a must, but I would expect the image upload to open the android image selector or a fully fledged file selector. Similar to Discord or any other app. As opposed to the limited file selector with an image filter.
> 
> Discord vs Status - no idea how to find my images to send in Status
> 
> https://photos.app.goo.gl/E3Bi46DFYvH19ESG8

Yeah... I still haven't managed to persuade the file selector to go into an "image picker" mode :(

> 3. For some reason there's a regression on IOS alone. When selecting the wrong file format I'm not getting the error popup. It's just silence. Works fine on the latest TestFlight app.

OK, I'll look into that
