### PR TITLE
fix(@desktop/chat): endless search when user has no chats or communities

### LINKED ISSUE #6427: The loader is shown infinitely in the Chat search if user didn't join any chats
# Bug Report

## Steps to reproduce
1. Sign up and click on the 'Search' field in the Chat tab
2. Click on the block 'In'
3. Click 'Anywhere'
4. Enter some search text like 'hey' and hit Enter
#### Expected behavior
The correct text is shown about no results found:
image

#### Actual behavior
The loader is shown infinitely:
image

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2316/
- Operating System: macOS Monterey M1

### PR DESCRIPTION
**Pull request by micieslak**
### What does the PR do

fixes #6427

- additional check added to the controller, if there is no chats or communities to search skip async search and return empty result
- go backend returns null when no messages found. It was causing error message - response validation fixed.
- some error messages added  for consistency

### Affected areas

app search controller, message service

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

Screenshot 2022-07-19 17:07:26

### CODE REVIEW

File: src/app_service/service/message/service.nim [hunk 1]
```diff
@@ -526,8 +526,8 @@ QtObject:
       self.finishAsyncSearchMessagesWithError(chatId, "search messages response doesn't contain messages array")
       return
 
-    if (messagesArray.kind != JArray):
-      self.finishAsyncSearchMessagesWithError(chatId, "expected messages json array is not of JArray type")
+    if (messagesArray.kind != JArray and messagesArray.kind != JNull):
```
Comment (jrainville) [inline src/app_service/service/message/service.nim:529]: Should this be ` or messagesArray.kind == JNull` instead? 
Actually, I'm not sure why the original check didn't work, if the return was null, the `JArray` check should have caught it?

Comment (saledjenic) [reply src/app_service/service/message/service.nim:529]: @micieslak you can also handle this in `async_task.nim`, task `asyncSearchMessagesInChatTask`, if result is null, you can set there `"messages":[]"`, but definitely condition `if (messagesArray.kind != JArray)` proceeds further only if `messagesArray` is array, so `and messagesArray.kind != JNull` is redundant (if something is `JNull` it is not `JArrray`).

**Review by saledjenic — CHANGES_REQUESTED** [review]

File: src/app_service/service/message/service.nim (hunk 1 above)
Comment (micieslak) [reply src/app_service/service/message/service.nim:529]: Originally, when the type was different then JArray, finish...WithError was called. So it happened for JNull as well, which imo should be treated as a valid kind when we have no messages. Now both JArray and JNull are considered valid kinds.

> but definitely condition if (messagesArray.kind != JArray) proceeds further only if messagesArray is array, so and messagesArray.kind != JNull is redundant (if something is JNull it is not JArrray)

We have != so it proceeds only if messagesArray is NOT JArray, right?

I can fix it in "async_task.nim" as you suggested as well, I initially fixed it there but then moved here :)

**Review by saledjenic — APPROVED** [review]

File: src/app_service/service/message/service.nim (hunk 1 above)
Comment (micieslak) [reply src/app_service/service/message/service.nim]: The problems with fixing it in `asyncSearchMessagesInChatTask` are as follows:
- we would have to assume that response obtained from go backend contains `"messages"` field and replace with [] if it's null. But only in `onAsyncSearchMessages` we validate if this field exists.
- (minor) the same check should be repeated in `asyncSearchMessagesInChatsAndCommunitiesTask`

So I would prefer to keep the response unmodified in `asyncSearchMessagesInChatTask` and `asyncSearchMessagesInChatsAndCommunitiesTask` and validate exclusively in `onAsyncSearchMessages`.

I tweaked the condition a bit for better readability.

@saledjenic, @jrainville, what do you think?

File: src/app_service/service/message/service.nim [hunk 2]
```diff
@@ -526,8 +526,8 @@ QtObject:
       self.finishAsyncSearchMessagesWithError(chatId, "search messages response doesn't contain messages array")
       return
 
-    if (messagesArray.kind != JArray):
-      self.finishAsyncSearchMessagesWithError(chatId, "expected messages json array is not of JArray type")
+    if (messagesArray.kind notin {JArray, JNull}):
```
Comment (jrainville) [inline src/app_service/service/message/service.nim:529]: I still don't get why you check for `JNull`. If it is `JNull`, that means that it's **not** a `JArray`, then we go in the condition and exit with `finishAsyncSearchMessagesWithError`. If it **is** `JNull`, we want to exit right?

**Review by elina2015 — APPROVED** [review]
Tested and approved

File: src/app_service/service/message/service.nim (hunk 1 above)
Comment (micieslak) [reply src/app_service/service/message/service.nim]: @saledjenic  `if response.result.kind != JNull` will be always true. We would have to check if `response["messages"]` exists and then replace with an empty array if null, what becomes slightly more complicated and needs to be repeated in `asyncSearchMessagesInChatsAndCommunitiesTask`. So I would opt for current solution which seems to be simpler, I hope.

File: src/app_service/service/message/service.nim (hunk 2 above)
Comment (jrainville) [reply src/app_service/service/message/service.nim:529]: Aaah ok, I didn't know that doing `getElems` on JNull was fine. Thanks for the info.

**Review by jrainville — APPROVED** [review]
