### PR TITLE
fix(@desktop/wallet): Handle empty activity list exception

### LINKED ISSUE #11354: Wallet -> Watch-only accounts: adding second watch only account crashes the app
### Description

1. open status
2. open wallet
3. add `0xF38D2CD3C6Ad02dD6f8B68E0A7b2f959819954b6` as watch only
4. select the account and open activity view
5. add `0x92D883ed38dEb10DF7C525bB2A7F04d7A00F5C5a ` as watch only

As result, the app is crashing when adding second w/o account:

```
Warning: "There are still \"2\" items in the process of being created at engine destruction." (:0, )
Traceback (most recent call last)
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/nim_status_client.nim(193) nim_status_client
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/nim_status_client.nim(167) mainProc
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/core/main.nim(29) delete
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/core/signals/signals_manager.nim(23) delete
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimqml/src/nimqml/private/qobject.nim(64) delete
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### LINKED ISSUE #11381: Activity going back
# Bug Report

Going back to activity while not being on activity screen
image

### PR DESCRIPTION
**Pull request by Cuteivist**
fixes #11354
fixes #11381

### What does the PR do

* Fixes crash because of unhandled exception
* Fixes activity back button visible when moving out of wallet view and going back to it

### Affected areas

Wallet UI
Wallet backend

### CODE REVIEW

**Review by alaibe — APPROVED** [review]

File: src/app/modules/main/wallet_section/activity/controller.nim [hunk 1]
```diff
@@ -208,9 +208,12 @@ QtObject:
...
       error "error fetching activity entries: ", res.errorCode
       return
-
-    let entries = self.backendToPresentation(res.activities)
-    self.model.setEntries(entries, res.offset, res.hasMore)
+    
+    try: 
+      let entries = self.backendToPresentation(res.activities)
+      self.model.setEntries(entries, res.offset, res.hasMore)
+    except Exception as e:
```
Comment (stefandunca) [inline src/app/modules/main/wallet_section/activity/controller.nim:215]: Better remove the exceptions in the function and transform them into errors. Ultimately, they did their job of signalling the issue but it took a lot of work to track. So I will only use Nim exceptions once we properly support reporting the stack trace. Errors logs are a better solution, even if they get lost in our noisy output.

**Review by stefandunca — APPROVED** [review]
