### PR TITLE
Fix adding custom tokens

### LINKED ISSUE #4040: can't add custom token
Screenshot 2021-11-04 at 12 44 13

1. open status
2. enable wallet
3. click assets -> add custom token
4. in the address put this details: https://etherscan.io/address/0xeEf5E2d8255E973d587217f9509B416b41CA5870#code
5. check console

```
INF 2021-11-09 10:48:15.593+03:00 getPinnedMailserver                        topics="mailserver-interaction" tid=2124555 file=settings.nim:100 fleet=eth.prod result=
qrc:/app/AppLayouts/Wallet/popups/AddCustomTokenModal.qml:60: TypeError: Property 'getTokenDetails' of object Model(0x7f9a9447c600) is not a function
```

```
qrc:/app/AppLayouts/Wallet/popups/AddCustomTokenModal.qml:60: TypeError: Property 'getTokenDetails' of object Model(0x7f9d65ce87a0) is not a function
```

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #4040 for real this time

### CODE REVIEW

File: src/app_service/service/token/service.nim [hunk 1]
```diff
@@ -26,96 +38,122 @@ type
...
-        x.isVisible = activeTokenSymbols.contains(x.symbol)
-        return x
+  proc delete*(self: Service) =
+    self.QObject.delete
+
+  proc newService*(
+    events: EventEmitter,
+    threadpool: ThreadPool,
+    settingService: setting_service.Service,
+    settingsService: settings_service.Service
```
Comment (alaibe) [inline src/app_service/service/token/service.nim:56]: oops!! :)

File: src/app/modules/main/wallet_section/module.nim [hunk 2]
```diff
@@ -40,7 +40,7 @@ type
 proc newModule*[T](
   delegate: T,
   events: EventEmitter,
-  tokenService: token_service.ServiceInterface,
```
Comment (alaibe) [inline src/app/modules/main/wallet_section/module.nim:43]: we don t do interface anymore?

**Review by alaibe — APPROVED** [review]

**Comment by anastasiyaig** [comment]
the initial issue is fixed, thanks @jrainville 

Screenshot 2021-11-10 at 10 17 51

File: src/app/modules/main/wallet_section/module.nim (hunk 2 above)
Comment (jrainville) [reply src/app/modules/main/wallet_section/module.nim:43]: It's in the case of an async service, aka a service which has one or more async functions, it can't inherit from the Interface, it needs to inherit from QObject

File: ui/app/AppLayouts/Wallet/popups/AddCustomTokenModal.qml [hunk 3]
```diff
@@ -57,7 +57,7 @@ ModalPopup {
     }
 
     property var getTokenDetails: Backpressure.debounce(popup, 500, function (tokenAddress){
-        RootStore.customTokenList.getTokenDetails(tokenAddress)
+        RootStore.walletTokensModule.getTokenDetails(tokenAddress)
```
Comment (PascalPrecht) [inline ui/app/AppLayouts/Wallet/popups/AddCustomTokenModal.qml:60]: I might be wrong but I'm not sure if we want to explose entire modules on the store..

Comment (PascalPrecht) [reply ui/app/AppLayouts/Wallet/popups/AddCustomTokenModal.qml:60]: Nevermind, seeing that this is just a sub section. Maybe we should call this differently then?

Just thinking out loud.

**Review by PascalPrecht — APPROVED** [review]
