### PR TITLE
fix(@desktop/notifications): revamp notifications settings & behaviour

### LINKED ISSUE #4902: revamp notifications settings & behaviour
figma: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=973%3A105649

before starting development on this task, the spec on https://github.com/status-im/feature-specs/pull/33 needs to be updated based on the new design and using a tool such as https://www.archimatetool.com/ to create a diagram

### PR DESCRIPTION
**Pull request by saledjenic**
At the moment we are not able to display notification in case of:
- `AcceptedContactRequest` - if sent contact request is accepted
- `MyRequestToJoinCommunityRejected` - if my request to join private community is rejected
- `IdentityVerificationRequest` - if identity verification is requested from me

Fixes #4902

### CODE REVIEW

File: src/app/core/notifications/notifications_manager.nim [hunk 1]
```diff
@@ -13,6 +13,7 @@ logScope:
 const NOTIFICATION_SOUND = "qrc:/imports/assets/audio/notification.wav"
 
 # Signals which may be emitted by this class:
+const SIGNAL_ADD_NOTIFICATION_TO_ACTIVITY_CENTER* = "addNotificationToActivityCenter"
```
Comment (saledjenic) [inline src/app/core/notifications/notifications_manager.nim:16]: According to [new message notification diagram](https://drive.google.com/file/d/1L_9c2CMObcDcSuhVUu97s9-_26gtutES/view) and [other actions diagram](https://drive.google.com/file/d/1KmG7lJDJIx6R_HJWeFvMYT2wk32RoTJQ/view) we should add notification to the Activity Center. Because of that `SIGNAL_ADD_NOTIFICATION_TO_ACTIVITY_CENTER` is introduced here and it's emitted whenever we need to add new notification to the Activity Center (so in theory we just need to connect to it in the activity center module and that's it). 

But that part is not done here, because that would add notifications correctly, according to the logic described in diagrams, but only while the app is running, after app restart we won't have them since `status-go` part doesn't know about those notifications (that way they may be added only on the UI side). 

So we need to discuss here what and how should we handle this? 
1. Whether to update `status-go` in a way that the desktop app calls some method from the `status-go` to update DB in order to have the same list of notifications in the activity center after app restart (in this case the app will be source of truth and determine whether to display a notification or not, and if yes, use `status-go` endpoint just to store it in the DB)? 
2. Or maybe to apply the same logic, as we currently have in `NotificationsManager` class, on the side of `status-go` and let `status-go` notifies the app about activity center notifications.

File: src/app/core/notifications/notifications_manager.nim [hunk 2]
```diff
@@ -13,6 +13,7 @@ logScope:
...
 const SIGNAL_DISPLAY_APP_NOTIFICATION* = "displayAppNotification"
```
Comment (saledjenic) [inline src/app/core/notifications/notifications_manager.nim:17]: Similar as above, according to [new message notification diagram](https://drive.google.com/file/d/1L_9c2CMObcDcSuhVUu97s9-_26gtutES/view) and [other actions diagram](https://drive.google.com/file/d/1KmG7lJDJIx6R_HJWeFvMYT2wk32RoTJQ/view) we should display ephemeral app notification in some cases, that's the reason why we have `SIGNAL_DISPLAY_APP_NOTIFICATION ` signal, which is emitted whenever we need to display ephemeral notification, so all we need to do is just to connect to this signal and display it.

This part is not done here cause we don't have yet ephemeral notifications developed.
We will handle this through the new issue.

**Review by borismelnik — APPROVED** [review]

**Comment by saledjenic** [comment]
Issues logged [here](https://docs.google.com/document/d/1Nd7YQOYVPR-KMz5qdU1AIGpL7vwBAZs-efifnZ0IkO8/edit) related to the notification settings are fixed.

Errors fixed within this PR were caused by switching to the channel groups and referring to public key of logged in user as id of the Chat section instead of usage of an empty string as how it was before.

What is fixed:
- The sound bar is only operable in the first 10% of the slider, it doesn't function as expected
- Rename to Notification & Sound instead of Notification
- The chat shows - “All Messages Quiet” when other messages is set to “Send Alerts”
- Clicking on OS notification doesn't take you to the message

File: ui/app/AppLayouts/Profile/popups/ExemptionNotificationsModal.qml [hunk 3]
```diff
@@ -0,0 +1,159 @@
...
+    header.title: qsTr("%1 exemption").arg(root.item.name)
+    header.image.source: root.item.image
+    header.icon: StatusIconSettings {
+        // Once we introduce StatusSmartIdenticon in popup header, we should use the folowing
+//        color: root.item.type === Constants.settingsSection.exemptions.oneToOneChat?
+//                   Theme.palette.userCustomizationColors[Utils.colorIdForPubkey(root.item.itemId)] :
+//                   root.item.color
+        // until then the following is used
+        background.color: root.item.type === Constants.settingsSection.exemptions.oneToOneChat?
+                              Theme.palette.userCustomizationColors[Utils.colorIdForPubkey(root.item.itemId)] :
```
Comment (jrainville) [inline ui/app/AppLayouts/Profile/popups/ExemptionNotificationsModal.qml:41]: I wonder if the correct color shouldn't be populated by the backend?

File: ui/app/AppLayouts/Profile/popups/ExemptionNotificationsModal.qml [hunk 4]
```diff
@@ -0,0 +1,159 @@
...
+                              root.item.color
+        charactersLen: root.item.type === Constants.settingsSection.exemptions.oneToOneChat? 2 : 1
+        isLetterIdenticon: root.item.image === ""
+        height: isLetterIdenticon ? 40 : 20
+        width: isLetterIdenticon ? 40 : 20
+    }
+
+    QtObject {
+        id: d
```
Comment (jrainville) [inline ui/app/AppLayouts/Profile/popups/ExemptionNotificationsModal.qml:50]: Maybe we could have a more indicative id, like `data` or something?

File: ui/app/AppLayouts/Profile/views/NotificationsView.qml [hunk 5]
```diff
@@ -1,399 +1,576 @@
...
+            label: {
+                if(!model.customized)
+                    return ""
+
+                let l = ""
+                if(model.muteAllMessages)
+                    l += qsTr("Muted")
+                else {
+                    let singleChange = false
+                    let multipleChanges = false
```
Comment (jrainville) [inline ui/app/AppLayouts/Profile/views/NotificationsView.qml:83]: Maybe instead of single and multiple changes, you could use an int called `nbOfChanges` and increment it each time there is a change. That way, in the end, when you detect if there are multiple changes, just check if `nbOfChanges > 1`

File: ui/app/AppLayouts/Profile/views/NotificationsView.qml [hunk 6]
```diff
@@ -1,399 +1,576 @@
...
+                        lineHeight: Constants.settingsSection.infoLineHeight
+                        lineHeightMode: Text.FixedHeight
+                        color: Theme.palette.primaryColor1
+
+                    }
+
+                    StatusBaseText {
+                        Layout.preferredWidth: parent.width
+                        text: qsTr("To receive Status notifications, make sure you've enabled them in" +
+                                   " your computer's settings under <b>System Preferences > Notifications</b>")
```
Comment (jrainville) [inline ui/app/AppLayouts/Profile/views/NotificationsView.qml:216]: Since we might disable RichText by default, it might be safer to add the RichText mode here in case.

File: ui/app/AppLayouts/Profile/views/NotificationsView.qml [hunk 7]
```diff
@@ -1,399 +1,576 @@
...
-                    })
-
-                    mutedChatsModal.open();
+            NotificationAppearancePreviewPanel {
+                Layout.preferredWidth: root.profileContentWidth
+                Layout.leftMargin: Style.current.padding
+                name: qsTr("Name Only")
+                notificationTitle: "Vitalik Buterin"
+                //% "You have a new message"
+                notificationMessage: qsTrId("you-have-a-new-message")
```
Comment (jrainville) [inline ui/app/AppLayouts/Profile/views/NotificationsView.qml:427]: We no longer use qsTrId iirc. You can switch it to a qsTr

File: ui/app/AppLayouts/Profile/views/NotificationsView.qml [hunk 8]
```diff
@@ -1,399 +1,576 @@
...
-
-                    mutedChatsModal.open();
+            NotificationAppearancePreviewPanel {
+                Layout.preferredWidth: root.profileContentWidth
+                Layout.leftMargin: Style.current.padding
+                //% "Anonymous"
+                name: qsTrId("anonymous")
+                notificationTitle: "Status"
+                //% "You have a new message"
+                notificationMessage: qsTrId("you-have-a-new-message")
```
Comment (jrainville) [inline ui/app/AppLayouts/Profile/views/NotificationsView.qml:444]: Same here

**Review by jrainville — COMMENTED** [review]
Very good work. This is huge 😅 

I added a couple of comments, but none of them are big blockers.

It would be good if we could add an issue to move the logic to status-go like the comments I left say.

Nice work

File: src/app/core/notifications/notifications_manager.nim (hunk 1 above)
Comment (saledjenic) [reply src/app/core/notifications/notifications_manager.nim:16]: > I think we should do number 2.

@jrainville yes, that's correct and that's the plan, but since this is a big change, a logic which follows [message notification diagram](https://drive.google.com/file/d/1L_9c2CMObcDcSuhVUu97s9-_26gtutES/view) is firstly applied here.

Also at this moment `SIGNAL_ADD_NOTIFICATION_TO_ACTIVITY_CENTER` signal is not used anywhere, it is added more just to mark the single place in the code when and where from we should add notification to the Activity Center.

We need at least 2 steps more for this ticket:
1. move notification settings which are now stored in the local .ini file to the settings on the status-go side, we already have a ticket for that https://github.com/status-im/status-desktop/issues/5649
2. move logic from the desktop app to the `status-go` that items added to the Activity Center will be properly stored and consistent after app restart and also that the same logic may be shared between mobile and desktop app

File: src/app/core/notifications/notifications_manager.nim [hunk 9]
```diff
@@ -120,70 +133,171 @@ QtObject:
...
-      finalMessage = "You have a new message"
-        
-    # Check whether to display APP or OS notification
-    if(singletonInstance.localAccountSensitiveSettings.getUseOSNotifications()):
-      let identifier = $(details.toJsonNode())
-      debug "Add OS notification", title=finalTitle, message=finalMessage, identifier=identifier
-      self.showOSNotification(finalTitle, finalMessage, identifier)  
+    # In case of contact request
+    if(details.notificationType == NotificationType.NewContactRequest):
+      if(singletonInstance.localAccountSensitiveSettings.getNotifSettingContactRequests() != LSS_VALUE_NOTIF_SEND_TURN_OFF):
```
[the remark this answers is not in the document]
Comment (saledjenic) [reply src/app/core/notifications/notifications_manager.nim:233]: @jrainville yes, I agree, that's the plan (elaborated [here](https://github.com/status-im/status-desktop/pull/5334/files#r866538652)).

File: src/app/modules/main/profile_section/notifications/module.nim [hunk 10]
```diff
@@ -63,23 +106,72 @@ method viewDidLoad*(self: Module) =
...
+  
+  self.view.exemptionsModel().updateExemptions(itemId, muteAllMessages, personalMentions, globalMentions, otherMessages)
+  
+  singletonInstance.localAccountSensitiveSettings.setNotifSettingExemptions($allExemptions)
+
+method onToggleSection*(self: Module, sectionType: SectionType) =
+  if(sectionType != SectionType.Community):
+    return
+
+  if(singletonInstance.localAccountSensitiveSettings.getCommunitiesEnabled()):
```
[the remark this answers is not in the document]
Comment (saledjenic) [reply src/app/modules/main/profile_section/notifications/module.nim:130]: @jrainville I don't see how? Add pseudo code here what's your idea?

Here is an explanation of the current code:
Code here should be applied only for the sections which are type of `SectionType.Community`. So idea is if we receive here anything but the `SectionType.Community` to get back immediately, otherwise we're taking action based on `getCommunitiesEnabled()` and reach `then` or `else` block depends on that condition.

Now if I merge `getCommunitiesEnabled()` to the condition in the line 127 either with `AND` or `OR` that won't be the same condition any more, cause `then` and `else` blocks won't be executed in the same cases as they are executed now.

File: ui/app/AppLayouts/Profile/popups/ExemptionNotificationsModal.qml (hunk 3 above)
Comment (saledjenic) [reply ui/app/AppLayouts/Profile/popups/ExemptionNotificationsModal.qml:41]: @jrainville as I see so far on other places that's defined on the qml side (part of `Theme`), determined by `Theme.palette.userCustomizationColors`.

File: ui/app/AppLayouts/Profile/popups/ExemptionNotificationsModal.qml (hunk 4 above)
Comment (saledjenic) [reply ui/app/AppLayouts/Profile/popups/ExemptionNotificationsModal.qml:50]: @jrainville in all qml components defined by Qt `d` is used as `id` of `QtObject` containing private properties (I think it stands for "details"), so that's the reason for that. Check [here](https://doc.qt.io/archives/qt-4.8/qml-coding-conventions.html#private-properties).

File: ui/app/AppLayouts/Profile/views/NotificationsView.qml (hunk 5 above)
Comment (saledjenic) [reply ui/app/AppLayouts/Profile/views/NotificationsView.qml:83]: @jrainville yes, that's true, simpler, updated (initially I had some other logic there and just continued in that way).

File: ui/app/AppLayouts/Profile/views/NotificationsView.qml (hunk 6 above)
Comment (saledjenic) [reply ui/app/AppLayouts/Profile/views/NotificationsView.qml:216]: @jrainville in this particular case we don't have `RichText` explicitly set, it's left to the `StatusBaseText` component to decide what to do, but if you see beneath, it's just a simple `Text` component so `Text.AutoText` will be used as that's default for `Text`, which is I guess fine. Otherwise if we ever decide to set explicitly `textFormat: Text.PlainText` in `StatusBaseText` that will be a breaking change which will affect lot of places (hope that won't happen ever :) ).

File: ui/app/AppLayouts/Profile/views/NotificationsView.qml (hunk 7 above)
Comment (saledjenic) [reply ui/app/AppLayouts/Profile/views/NotificationsView.qml:427]: @jrainville didn't know that. Thanks.

File: ui/app/AppLayouts/Profile/views/NotificationsView.qml (hunk 8 above)
Comment (saledjenic) [reply ui/app/AppLayouts/Profile/views/NotificationsView.qml:444]: @jrainville updated.

File: src/app/modules/main/profile_section/notifications/module.nim (hunk 10 above)
[the remark this answers is not in the document]
Comment (jrainville) [reply src/app/modules/main/profile_section/notifications/module.nim:130]: My bad, I missed the `else`

File: ui/app/AppLayouts/Profile/views/NotificationsView.qml (hunk 6 above)
Comment (jrainville) [reply ui/app/AppLayouts/Profile/views/NotificationsView.qml:209]: > Otherwise if we ever decide to set explicitly textFormat: Text.PlainText in StatusBaseText that will be a breaking change which will affect lot of places (hope that won't happen ever :) ).

Yeah that was my point. We've had a couple of "XSS" issues that we caused by Texts accepting HTML. We proposed the change to never allow HTML soit doesn't happen again.
Like you pointed out, it would be a breaking change, so maybe we don't do it. 
I was just proposing that you set it manually here, just in case we ever do change it.

**Review by jrainville — APPROVED** [review]
Nice job.

**Review by iurimatias — APPROVED** [review]
