### PR TITLE
fix(users): user not added when joining group + only show joined users

### LINKED ISSUE #5202: recently accepted group chat invites don't show up in the user list until app restart
# Bug Report

## Steps to reproduce

1. start a group chat
2. have a contact accept the group request

#### Expected behavior

recently joined user should show in the user list

#### Actual behavior

user isn't shown until app restarts

Screen Shot 2022-03-27 at 11 50 17 AM

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #5202

You had to restart the app to see newly joined users in a group chat. Now they are added when they join.

**Note**: This also changes the behaviour of the user list. Only `joined` users (of a group or a community) will show in the list.
First, it fixes the weird behaviour of group chats where on creating them, the list would be empty, but on restarting, every user would be there, even if they didn't join.
Second, it also makes sense, because the user isn't actually in the group chat or community, so seeing them in the list is misleading.
I tested public chats as well, and it didn't affect them.

### CODE REVIEW

File: src/app/modules/main/chat_section/chat_content/users/module.nim [hunk 1]
```diff
@@ -154,29 +140,39 @@ method loggedInUserImageChanged*(self: Module) =
   self.view.model().setIcon(singletonInstance.userProfile.getPubKey(), singletonInstance.userProfile.getIcon(),
   singletonInstance.userProfile.getIsIdenticon())
 
+method addChatMember*(self: Module,  id: string) =
```
Comment (jrainville) [inline src/app/modules/main/chat_section/chat_content/users/module.nim:143]: This is just the code from `onChatMembersAdded` that I moved out to this function so I can reduce duplication.

File: src/app/modules/main/chat_section/chat_content/users/module.nim [hunk 2]
```diff
@@ -154,29 +140,39 @@ method loggedInUserImageChanged*(self: Module) =
...
+  if(self.view.model().isContactWithIdAdded(id)):
+    return
+
+  let (admin, joined) = self.controller.getChatMemberInfo(id)
+  if (joined == false):
```
Comment (saledjenic) [inline src/app/modules/main/chat_section/chat_content/users/module.nim:148]: @jrainville you could just do this (somehow more natural):
```
if(not joined):
  return
```

**Review by saledjenic — APPROVED** [review]

**Review by borismelnik — APPROVED** [review]

**Review by iurimatias — CHANGES_REQUESTED** [review]
_
