### PR TITLE
fix(chat_section): fix parent badge not updating on chat close and open

### LINKED ISSUE #14025: Closing a chat with unread message should clear the unread badge
### Description

@benjthayer wdyt?

https://github.com/status-im/status-desktop/assets/82375995/996ab0dd-9e08-43fe-87ce-fbdddc1e8196

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #14025

[unread-badge.webm](https://github.com/status-im/status-desktop/assets/11926403/2cfbd367-492e-4ad1-8c36-24ce8cd639e5)

### CODE REVIEW

File: src/app/modules/main/chat_section/module.nim [hunk 1]
```diff
@@ -1406,7 +1404,7 @@ proc addOrUpdateChat(self: Module,
   if chat.id == activeChatId:
     self.updateActiveChatMembership()
 
-  if chatExists:
+  if self.doesCatOrChatExist(chat.id):
```
Comment (MishkaRogachev) [inline src/app/modules/main/chat_section/module.nim:1407]: Cat?

**Review by MishkaRogachev — APPROVED** [review]

File: src/app/modules/main/chat_section/module.nim (hunk 1 above)
Comment (caybro) [reply src/app/modules/main/chat_section/module.nim:1407]: Just the English version of "chat" :wink:

**Review by igor-sirotin — APPROVED** [review]
