### PR TITLE
fix(@desktop/chat): messages sometimes assigned to the wrong user

### LINKED ISSUE #6004: Messages sometimes assigned to the wrong user
# Bug Report

## Steps to reproduce

Not easy to reproduce but steps in this case were
1. add contact desktop
2. send messages to each other

eventually one of the images was incorrect (see screenshots), it seems to 'recover' and show the messages correctly after more messages are sent in the chat

Screen Shot 2022-06-03 at 2 43 41 PM

### Additional Information

- Status desktop version: branch `dogfooding_1` `b9c65be808c6a06ecfafd9066f305c8e0a52cdc9`

### PR DESCRIPTION
**Pull request by saledjenic**
Fixes #6004

### CODE REVIEW

**Review by Hbouaz — APPROVED** [review]

File: src/app/modules/main/chat_section/chat_content/messages/module.nim [hunk 1]
```diff
@@ -183,7 +183,7 @@ method newMessagesLoaded*(self: Module, messages: seq[MessageDto], reactions: se
         m.image,
         m.containsContactMentions(),
         m.seen,
-        m.timestamp,
+        m.whisperTimestamp,
```
Comment (richard-ramos) [inline src/app/modules/main/chat_section/chat_content/messages/module.nim:186]: why `whisperTimestamp` instead of `timestamp`?

Comment (saledjenic) [reply src/app/modules/main/chat_section/chat_content/messages/module.nim:186]: > why `whisperTimestamp` instead of `timestamp`?

Whisper time should be one defined by the  mailserver, timestamp is generated on the status-go side, in case of message I am sending it could be different time set for timestamp and whisper time, while message I am receiving has the same time set for whisper time and timestamp. Now in order to avoid displaying messages in a different order for users A and B if they have sent messages to each other in the same time I think that correct way should be to use whisper timestamp.

**Review by richard-ramos — APPROVED** [review]
