### PR TITLE
fix: unbreak chat categories height and highlight 

### LINKED ISSUE #9493: Category height is not updated when collapsing it
# Bug Report

## Description

In a community, if you have a category with channels inside, collapsing the category hides the channels, but the height doesn't get reduced to 0.

Moreover, the category is not highlighted (bold) when it contains new messages either.

### PR DESCRIPTION
**Pull request by caybro**
- fix chat category/section height not being (re)set to 0 properly and
  hidden
- restore the chat category header highlighting when it contains new
  messages/mentions after the new flattened chat model refactoring

Fixes #9493

### Affected areas

StatusChatList; chat model

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

Mobile category collapsed; alleged new msg in desktop:
Snímek obrazovky z 2023-02-08 20-19-46

Desktop channel activated, whole category unmarked:
Snímek obrazovky z 2023-02-08 20-19-53

### CODE REVIEW

File: src/app_service/service/chat/service.nim [hunk 1]
```diff
@@ -207,7 +207,7 @@ QtObject:
       return false
 
     for chat in self.channelGroups[communityId].chats:
-      if chat.unviewedMentionsCount > 0 or chat.unviewedMentionsCount > 0:
+      if chat.unviewedMessagesCount > 0 or chat.unviewedMentionsCount > 0:
```
Comment (caybro) [inline src/app_service/service/chat/service.nim:210]: @0x-r4bbit

this was a pain to find :D

File: ui/StatusQ/src/StatusQ/Components/StatusChatList.qml [hunk 2]
```diff
@@ -38,66 +37,69 @@ Item {
         height: contentHeight
         objectName: "chatListItems"
         model: root.model
-        spacing: 4
+        spacing: 0
```
Comment (caybro) [inline ui/StatusQ/src/StatusQ/Components/StatusChatList.qml:40]: This, together with turning the delegate into a `Control` and enabling its `verticalPadding`, is here to fully hide a section of items; otherwise it would still have some height due to the spacing between items

**Review by jrainville — APPROVED** [review]
Good job. Nice finds

**Review by 0x-r4bbit — APPROVED** [review]

File: ui/app/AppLayouts/Wallet/views/CollectiblesView.qml [hunk 3]
```diff
@@ -8,8 +8,6 @@ import StatusQ.Components 0.1
 import shared.panels 1.0
 import utils 1.0
 
-import utils 1.0
```
Comment (alexandraB99) [inline ui/app/AppLayouts/Wallet/views/CollectiblesView.qml:11]: merge artifact? :D

Comment (caybro) [reply ui/app/AppLayouts/Wallet/views/CollectiblesView.qml:11]: Yup, it was a bad merge in master

**Review by alexandraB99 — APPROVED** [review]
liked this `visible: height` :)
