### PR TITLE
(fix/desktop) fix sporadic empty community token hodler list

### LINKED ISSUE #13650: Community Token holder list empty sometimes
# Bug Report

## Description

Weird issue. I was a TokenMaster in a community that had multiple tokens. One of the token was an NFT needed to join the community.

2 people owned that token, yet, when I went to see the list of holders in the admin panel, they didn't appear (the list was empty).

The owner could see them. However, after a restart, the owner also lost the list.

After doing something, not sure what, the list reappeared for both of us. I assume the community description was updated and that is how it got propagated again.

## Steps to reproduce

0. Be part of a community that has a permission to join, and you are TM, and 1 or 2 other people are holders of the token to join
1. Go to the admin panel -> Tokens
2. Click the Join token
3. See that the list of hodler might be empty

As of writing this issue, the list is empty again. I did restart the app.

I know that there are 3 members of the community that own it, including myself.

image

#### Expected behavior

The token holder list is populated with the people owning the token

#### Actual behavior

The list is often empty

### Additional Information

- Status desktop version: 2.27RC2
- Operating System: Ubuntu 20

### PR DESCRIPTION
**Pull request by kounkou**
### Description

This PR fixes #13650

- Reduces the timer for fetching the token hodlers to refresh cashe
- Check for temporary contract address before making requests

### What does the PR do

During my testing, I noticed that sometimes the contract address provided to status-go is temporary (It ends with `-owner` or `-master` and caused  the error :

```bash
ERR 2024-03-19 09:32:33.670-07:00 Can't fetch community token owners         topics="community-tokens-
service" tid=271622 file=service.nim:1407 chainId=421613
 contractAddress="\"0x24b23b3f095f33909b23cff69fc67f6c67242d026a1b93b16a02a4f308cfcf4b-master\""
 errorMsg="\nstatus-go error [methodName:wallet_getCollectibleOwnersByContractAddress, code:-32602,
 message:invalid argument 1: json: cannot unmarshal hex string of odd length into Go value of type
 common.Address ]\n"
```

### Affected areas

- community token service

### Cool Spaceship Picture

I have tried to reproduce the problem by testing several times the scenario of relaunching the application and going in managed community, then tokens to list the tokens, and then selecting any tokens to spectate the owners. I couldn't reproduce the empty list issue out of 10 tests

### Test

[](https://github.com/status-im/status-desktop/assets/2589171/24316b6a-abf1-4403-81a3-34efc96e2390)

### CODE REVIEW

File: src/app_service/service/community_tokens/service.nim [hunk 1]
```diff
@@ -1411,10 +1411,13 @@ QtObject:
...
     return self.tokenOwnersCache.getOrDefault((chainId: chainId, address: contractAddress))
 
+  proc isTokenDeployed*(self: Service, token: CommunityTokenDto): bool =
+    return token.deployState == DeployState.Deployed
+
   proc onRefreshTransferableTokenOwners*(self:Service) {.slot.} =
     let allTokens = self.getAllCommunityTokens()
     for token in allTokens:
-      if token.transferable:
+      if token.transferable and self.isTokenDeployed(token):
```
Comment (endulab) [inline src/app_service/service/community_tokens/service.nim:1420]: I think it would be safer to check it in fetchCommunityOwners() function, because it is used in a few places.

**Review by endulab — CHANGES_REQUESTED** [review]

File: src/app_service/service/community_tokens/service.nim [hunk 2]
```diff
@@ -1392,6 +1398,8 @@ QtObject:
       )
       self.threadpool.start(arg)
       return
+    else:
+      debug "Unknown tokenType received ", token=communityToken.tokenType
```
Comment (endulab) [inline src/app_service/service/community_tokens/service.nim:1402]: can you make the message more related? Eg. "can't fetch holders for unknown token type", or sth like this

File: src/app_service/service/community_tokens/service.nim [hunk 3]
```diff
@@ -1369,7 +1369,13 @@ QtObject:
       dataToEmit.requestId = responseJson{"requestId"}.getStr
       self.events.emit(SIGNAL_COMPUTE_AIRDROP_FEE, dataToEmit)
 
+  proc isTokenDeployed*(self: Service, token: CommunityTokenDto): bool =
```
[the remark this answers is not in the document]
Comment (kounkou) [reply src/app_service/service/community_tokens/service.nim]: Fixed

File: src/app_service/service/community_tokens/service.nim (hunk 2 above)
Comment (kounkou) [reply src/app_service/service/community_tokens/service.nim]: Fixed

**Review by MishkaRogachev — APPROVED** [review]
