### PR TITLE
fix(@desktop/settings): Store pass to keychain does not validate entered password

### LINKED ISSUE #4358: Store pass to keychain does not validate current password which results to inability to login
### Description

**Precondition:** this feature is applicable only on MacOS, so u need to use mac

**Steps:**

1. install a build, i used latest master commit 528210b50f40de99a951e7f95b8c57940aea6467
2. create an account and remember a password, lets say set it as `111111`
3. open Privacy and Security section
4. open Store to keychan
5. select Store
6. in password prompt enter any value that is different than your actual password, lets say `22222222`
7. confirm the action with the same value of `22222222`. _Notice that there is no validation of entered value against the actual password u set when u created an account_
8. logout
9. try to login back with your correct password (your laptop password)
10. try to login back with touch ID

As result, all attempts to login fail with an error. User is locked out from the app. 

```
Network Cache Dir:  "/Users/anastasiya/status-desktop/Status/tmp/netcache"
INF 2022-01-04 09:47:53.885+03:00 Starting application...                    topics="main" tid=385878 file=nim_status_client.nim:235
Network Cache Dir:  "/Users/anastasiya/status-desktop/Status/tmp/netcache"
DBG 2022-01-04 09:47:57.030+03:00 Account logged in                          topics="accounts-service" tid=385878 file=service.nim:311
ERROR[01-04|09:47:57.108] failed to initialize db                  package=status-go/api.GethStatusBackend err="file is not a database"
ERROR[01-04|09:47:57.109] failed to start a node                   key-uid=0xe94fd077fc9f8e0d46eb9b04ed72ad130cc4f8092cfdbf4126b12ab121aeb4ee error="file is not a database"
ERR 2022-01-04 09:47:57.110+03:00 node.login                                 topics="signals" tid=385878 file=signal_controller.nim:46 error="file is not a database"
ERR 2022-01-04 09:47:57.110+03:00 error:                                     topics="startup-controller" tid=385878 file=controller.nim:41 methodName=init errDesription="login error file is not a database"
INF 2022-01-04 09:48:03.981+03:00 Status app is shutting down...             topics="main" tid=385878 file=nim_status_client.nim:178
anastasiya@MacBook-Pro-Anastasiya status-desktop % 
```

Screenshot 2022-01-04 at 09 47 26

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
fixes #4358

### What does the PR do

Validated the entered password before it is stored to the keychain

### Affected areas

Onboarding, Settings

### Screenshot of functionality

https://user-images.githubusercontent.com/60327365/155523517-56f7c732-0c47-45e0-b6df-afa5c1513d81.mov

### CODE REVIEW

File: src/app_service/service/privacy/service.nim [hunk 1]
```diff
@@ -130,3 +130,24 @@ QtObject:
       return
 
     return mnemonics[index]
+
+  proc validatePassword*(self: Service, password: string): bool =
+    try:
+      var isValid = false
```
Comment (saledjenic) [inline src/app_service/service/privacy/service.nim:136]: @Khushboo-dev-cpp please remove this `isValid` variable (it's cleaner that way) and in each `then` block of your conditions below just to `return false` and at the end of the `try` block `return true`. 

Also as a final step either in `except` section or as the last line of this method do `return false` (that's in case an error has been thrown).

**Review by saledjenic — APPROVED** [review]
@Khushboo-dev-cpp looks good, approved.

Please just do that change mentioned in the comment below.

File: src/app_service/service/privacy/service.nim (hunk 1 above)
Comment (Khushboo-dev-cpp) [reply src/app_service/service/privacy/service.nim]: done @saledjenic thanks for pointing it out :)

**Review by anastasiyaig — APPROVED** [review]

**Review by iurimatias — APPROVED** [review]
