### PR TITLE
fix: fix warning and inconsistencies with spectating

### LINKED ISSUE #13957: Spectating a community crashes the app
# Bug Report

## Description

When you click on a community to spectate it, it crashes the app immediately

## Steps to reproduce

1. Receive a link to a community you do not spectate yet
2. Click on the link/unfurl
3. It crashes

The logs don't say much 
```
DBG 2024-03-13 14:07:32.747-04:00 NewBE_callPrivateRPC                       topics="rpc" tid=2727358 file=core.nim:27 rpc_method=wakuext_spectateCommunity
DBG 2024-03-13 14:07:32.768-04:00 NewBE_callPrivateRPC                       topics="rpc" tid=2727358 file=core.nim:27 rpc_method=chat_getChannelGroupByID
DBG 2024-03-13 14:07:32.781-04:00 NewBE_callPrivateRPC                       topics="rpc" tid=2727358 file=core.nim:27 rpc_method=wakuext_activityCenterNotifications
DBG 2024-03-13 14:07:32.786-04:00 setCommunityInfo                           tid=2727358 file=status_community_link_preview.nim:133 communityId=0x039a7ae0a02f28fe873506d49ac4d4e073e58855af3febaf460d928f08867fdf0e communityName=stay-owner-2
DBG 2024-03-13 14:07:32.786-04:00 setCommunityInfo                           tid=2727358 file=status_community_link_preview.nim:133 communityId=0x039a7ae0a02f28fe873506d49ac4d4e073e58855af3febaf460d928f08867fdf0e communityName=stay-owner-2
ERR 2024-03-13 14:07:32.791-04:00 unexisting chat key                        topics="chat-section-module" tid=2727358 file=module.nim:442 chatId= methodName=getChatContentModule
DBG 2024-03-13 14:07:32.793-04:00 NewBE_callPrivateRPC                       topics="rpc" tid=2727358 file=core.nim:27 rpc_method=wakuext_getLatestVerificationRequestFrom
ERR 2024-03-13 14:07:32.796-04:00 unexisting chat key                        topics="chat-section-module" tid=2727358 file=module.nim:442 chatId= methodName=getChatContentModule
ERR 2024-03-13 14:07:32.797-04:00 unexisting chat key                        topics="chat-section-module" tid=2727358 file=module.nim:442 chatId= methodName=getChatContentModule
ERR 2024-03-13 14:07:32.808-04:00 unexisting chat key                        topics="chat-section-module" tid=2727358 file=module.nim:442 chatId= methodName=getChatContentModule
ERR 2024-03-13 14:07:32.808-04:00 unexisting chat key                        topics="chat-section-module" tid=2727358 file=module.nim:442 chatId= methodName=getChatContentModule
DBG 2024-03-13 14:07:32.819-04:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=2727389 file=threadpool.nim:54 messageType=AsyncGetRevealedAccountsArg:ObjectType threadid=2727389 task="{\"$type\":\"AsyncGetRevealedAccountsArg:ObjectType\",\"communityId\":\"0x039a7ae0a02f28fe873506d49ac4d4e073e58855af3febaf460d928f08867fdf0e\",\"memberPubkey\":\"0x04a2e8d039383760b1b5d06ab2336068198da3b615f39c5efa863bbf99b4236062ca19fb0e9168c4f964a1260f63357cb111df8aae155dbb606018766f8b77d5f9\",\"vptr\":94641314140112,\"slot\":\"onAsyncGetRevealedAccountsForMemberCompleted\",\"tptr\":94641274798240}"
DBG 2024-03-13 14:07:32.820-04:00 NewBE_callPrivateRPC                       topics="rpc" tid=2727389 file=core.nim:27 rpc_method=wakuext_getRevealedAccounts
DBG 2024-03-13 14:07:32.820-04:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=2727378 file=threadpool.nim:54 messageType=AsyncCheckPermissionsToJoinTaskArg:ObjectType threadid=2727378 task="{\"$type\":\"AsyncCheckPermissionsToJoinTaskArg:ObjectType\",\"communityId\":\"0x039a7ae0a02f28fe873506d49ac4d4e073e58855af3febaf460d928f08867fdf0e\",\"addresses\":[],\"vptr\":94641314140112,\"slot\":\"onAsyncCheckPermissionsToJoinDone\",\"tptr\":94641274676832}"
DBG 2024-03-13 14:07:32.820-04:00 NewBE_callPrivateRPC                       topics="rpc" tid=2727378 file=core.nim:27 rpc_method=wakuext_checkPermissionsToJoinCommunity
DBG 2024-03-13 14:07:32.820-04:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=2727386 file=threadpool.nim:54 messageType=AsyncCheckAllChannelsPermissionsTaskArg:ObjectType threadid=2727386 task="{\"$type\":\"AsyncCheckAllChannelsPermissionsTaskArg:ObjectType\",\"communityId\":\"0x039a7ae0a02f28fe873506d49ac4d4e073e58855af3febaf460d928f08867fdf0e\",\"addresses\":[],\"vptr\":94641316790560,\"slot\":\"onAsyncCheckAllChannelsPermissionsDone\",\"tptr\":94641274165920}"
DBG 2024-03-13 14:07:32.820-04:00 NewBE_callPrivateRPC                       topics="rpc" tid=2727386 file=core.nim:27 rpc_method=wakuext_checkAllCommunityChannelsPermissions
Warning: qrc:/app/AppLayouts/Communities/views/CommunityColumnView.qml:484:9: QML StatusButton: Cannot anchor to an item that isn't a parent or sibling. (qrc:/app/AppLayouts/Communities/views/CommunityColumnView.qml:484, )
ERR 2024-03-13 14:07:32.853-04:00 unexisting chat key                        topics="chat-section-module" tid=2727358 file=module.nim:442 chatId= methodName=getChatContentModule
Warning: qrc:/app/AppLayouts/Chat/views/ChatColumnView.qml:179: TypeError: Cannot read property 'inputAreaModule' of undefined (qrc:/app/AppLayouts/Chat/views/ChatColumnView.qml:179, )
Warning: qrc:/app/AppLayouts/Chat/views/ChatColumnView.qml:90: TypeError: Cannot read property 'inputAreaModule' of undefined (qrc:/app/AppLayouts/Chat/views/ChatColumnView.qml:90, )
Warning: qrc:/imports/shared/status/StatusChatInput.qml:1357:33: Unable to assign [undefined] to QStringList (qrc:/imports/shared/status/StatusChatInput.qml:1357, )
Warning: qrc:/app/AppLayouts/Chat/views/ChatColumnView.qml:86: TypeError: Cannot read property 'inputAreaModule' of undefined (qrc:/app/AppLayouts/Chat/views/ChatColumnView.qml:86, )
Warning: qrc:/app/AppLayouts/Chat/views/ChatColumnView.qml:267: TypeError: Cannot read property 'inputAreaModule' of undefined (qrc:/app/AppLayouts/Chat/views/ChatColumnView.qml:267, )
Warning: qrc:/app/AppLayouts/Chat/views/ChatColumnView.qml:277: TypeError: Cannot read property 'chatDetails' of undefined (qrc:/app/AppLayouts/Chat/views/ChatColumnView.qml:277, )
Warning: qrc:/app/AppLayouts/Communities/views/CommunityColumnView.qml:308:17: Unable to assign [undefined] to bool (qrc:/app/AppLayouts/Communities/views/CommunityColumnView.qml:308, )
Warning: qrc:/app/AppLayouts/Communities/views/CommunityColumnView.qml:406: TypeError: Cannot read property 'height' of null (qrc:/app/AppLayouts/Communities/views/CommunityColumnView.qml:406, )
Warning: qrc:/app/AppLayouts/Communities/views/CommunityColumnView.qml:423: TypeError: Cannot read property 'height' of null (qrc:/app/AppLayouts/Communities/views/CommunityColumnView.qml:423, )
Warning: qrc:/app/AppLayouts/Chat/views/ChatView.qml:50: TypeError: Cannot read property 'viewAndPostPermissionsSatisfied' of null (qrc:/app/AppLayouts/Chat/views/ChatView.qml:50, )
Warning: qrc:/app/AppLayouts/Chat/views/ChatView.qml:49: TypeError: Cannot read property 'viewOnlyPermissionsSatisfied' of null (qrc:/app/AppLayouts/Chat/views/ChatView.qml:49, )
Warning: qrc:/app/AppLayouts/Chat/stores/RootStore.qml:20: TypeError: Cannot read property 'chatDetails' of undefined (qrc:/app/AppLayouts/Chat/stores/RootStore.qml:20, )
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [Makefile:817: run-linux] Segmentation fault (core dumped)
```

#### Expected behavior

No crashes. It adds the community in spectate mode in the left bar and shows it

#### Actual behavior

:skull: 

### Additional Information

- Status desktop version: master `fc16b81caf2fa08205fdf03497423a63520e45e3`
- Operating System: Ubuntu 20

### PR DESCRIPTION
**Pull request by jrainville**
Kinda fixes #13957

Turns out the crash was only in my own account and even though I kept pushing the crash back, it still happened sometimes and finally, it crashed on the weirdest place, ie a `return`.

@kounkou tried to reproduce to help me, and he couldn't. I then tried with a new account and lo and behold, the crash doesn't happen anymore.

So long story short, I was fighting a windmill.

I did at least improve the windmill a little, so there's that. This PR is the result of that. 

So we should see less warnings at least.

### CODE REVIEW

File: src/app/modules/main/chat_section/module.nim [hunk 1]
```diff
@@ -411,8 +411,8 @@ method activeItemSet*(self: Module, itemId: string) =
     return
 
   # update view maintained by this module
-  self.view.chatsModel().setActiveItem(itemId)
   self.view.activeItemSet(chat_item)
+  self.view.chatsModel().setActiveItem(itemId)
```
Comment (jrainville) [inline src/app/modules/main/chat_section/module.nim:415]: This fixes the problem where the active item is undefined when switching to a section. Now the active item will be set in the view before switching.

File: src/app/modules/main/module.nim [hunk 2]
```diff
@@ -1411,6 +1413,9 @@ method onStatusUrlRequested*[T](self: Module[T], action: StatusUrlAction, commun
     of StatusUrlAction.OpenCommunity:
       let item = self.view.model().getItemById(communityId)
       if item.isEmpty():
+        if self.controller.getCommunityById(communityId).id != "":
+          self.controller.spectateCommunity(communityId)
+          return
```
Comment (jrainville) [inline src/app/modules/main/module.nim:1418]: This saves us a useless fetch. If we already know the community, just spectate it.

File: src/app_service/service/community/service.nim
Comment (jrainville) [inline src/app_service/service/community/service.nim:1]: Most of this file has nothing but a change to use the util function. It's safer that way, since we do an `exists`. 
There is a real change below though.

File: src/app_service/service/community/service.nim [hunk 3]
```diff
@@ -1048,7 +1048,9 @@ QtObject:
       self.events.emit(SIGNAL_COMMUNITY_SPECTATED, CommunityArgs(community: updatedCommunity, fromUserAction: true, isPendingOwnershipRequest: (ownerTokenNotification != nil)))
 
       for k, chat in updatedCommunity.chats:
-        let fullChatId = communityId & chat.id
+        var fullChatId = chat.id
+        if not chat.id.startsWith(communityId):
+          fullChatId = communityId & chat.id
```
Comment (jrainville) [inline src/app_service/service/community/service.nim:1053]: I think this code never worked before. The chat ID returned was the long one with the community ID prefixed, so we were double prefixing. Because of that `asyncLoadInitialMessagesForChat` (called below) would always fail

File: ui/app/AppLayouts/Chat/ChatLayout.qml
Comment (jrainville) [inline ui/app/AppLayouts/Chat/ChatLayout.qml:1]: Just a name change here

File: ui/app/AppLayouts/Chat/views/ChatColumnView.qml
Comment (jrainville) [inline ui/app/AppLayouts/Chat/views/ChatColumnView.qml:1]: Most of the changes here are to avoid warnings because `activeChatContentModule` might be undefined on first load.

There is an added Loader too

File: ui/app/AppLayouts/Chat/views/ChatColumnView.qml [hunk 4]
```diff
@@ -203,33 +216,38 @@ Item {
...
-                    onOpenStickerPackPopup: {
-                        root.openStickerPackPopup(stickerPackId)
-                    }
-                    onShowReplyArea: (messageId) => {
-                                         d.showReplyArea(messageId)
-                                     }
-                    onForceInputFocus: {
-                        chatInput.forceInputActiveFocus()
-                    }
+                    active: model.type !== Constants.chatType.category && model.type !== Constants.chatType.unknown
```
Comment (jrainville) [inline ui/app/AppLayouts/Chat/views/ChatColumnView.qml:222]: I added this Loader, because it's completely useless to create a `ChatContentView` for a category. And for unknown types too obviously

File: ui/imports/shared/views/chat/InvitationBubbleView.qml [hunk 5]
```diff
@@ -206,7 +206,7 @@ Control {
                     if (d.communityJoined || d.communitySpectated) {
                         root.store.setActiveCommunity(communityId)
                     } else {
-                        root.store.spectateCommunity(communityId, userProfile.name)
+                        root.store.spectateCommunity(communityId)
```
Comment (jrainville) [inline ui/imports/shared/views/chat/InvitationBubbleView.qml:209]: That param is useless

**Comment by kounkou** [comment]
I tested on my side and everything works perfect. I am able to leave the community and join again no problem. thanks!

Screenshot from 2024-03-19 13-21-43

**Review by kounkou — APPROVED** [review]
LGTM

File: src/app/modules/main/module.nim [hunk 6]
```diff
@@ -1038,6 +1037,9 @@ method communityLeft*[T](self: Module[T], communityId: string) =
 method communityEdited*[T](
     self: Module[T],
     community: CommunityDto) =
+  if(not self.channelGroupModules.contains(community.id)):
+    echo "main-module, unexisting community key to edit: ", community.id
```
Comment (MishkaRogachev) [inline src/app/modules/main/module.nim:1041]: maybe it's better to use `warn` from `chronicles`?

**Review by MishkaRogachev — APPROVED** [review]

**Review by alexjba — APPROVED** [review]
LGTM!

File: src/app/modules/main/module.nim (hunk 6 above)
Comment (jrainville) [reply src/app/modules/main/module.nim:1041]: I'll actually delete the log. It was useful for debugging the crash, but it's not a necessary log, because it's normal for some communities to be edited while not being joined or spectated (in the portal for example)
