### PR TITLE
fix(@wallet): Fix event for transaction

### LINKED ISSUE #9228: [Wallet] Fix transaction system notification
## Description

During implementation of contract deployment it turned out that transaction system 
notification does not work correctly.
After trackPendingTransaction(), which stores pending transaction in database,
checkPendingTransactions() is not executed and the signal about transaction state is not propagated.
checkPendingTransactions() is executed after restart, at the beginning of the application startup, and then the signal
is emitted.

### PR DESCRIPTION
**Pull request by alaibe**
* Make get pending tx returning object instead of json
* Fix deserialization of small float for suggested routes
* Move wallet event handler to services
* Fix handling event with watch tx and check recent history

fixes #9228

### CODE REVIEW

File: src/app_service/service/transaction/service.nim [hunk 1]
```diff
@@ -82,16 +89,15 @@ QtObject:
...
+  proc loadTransactions*(self: Service, address: string, toBlock: Uint256, limit: int = 20, loadMore: bool = false)
 
   proc delete*(self: Service) =
     self.QObject.delete
 
   proc newService*(
       events: EventEmitter,
       threadpool: ThreadPool,
-      networkService: network_service.Service,
+      networkService: network_service.Service,
```
Comment (jrainville) [inline src/app_service/service/transaction/service.nim:100]:
```suggestion
      networkService: network_service.Service,
```

**Review by jrainville — APPROVED** [review]
Looks good

**Review by Khushboo-dev-cpp — APPROVED** [review]

**Review by saledjenic — APPROVED** [review]

**Review by endulab — APPROVED** [review]
