### PR TITLE
fix(Qt6): various mostly Storybook fixes

### LINKED ISSUE #17447: [Qt 5->6]: Storybook - refactor `logs.logEvent`
# Bug Report

## Description

Because of https://bugreports.qt.io/browse/QTBUG-134215 calls to `logs.logEvent` in arrow functions may lead to crash on Qt 6. It's also not fully valid code in Qt 5, but working even if it shouldn't according to JS specification.

## Steps to reproduce
1. (Under qt 6) Open storybook, `OnboardingLayout`
2. Enable `show login screen`
3. Press `Paste password` button and log in

#### Expected behavior
Log should be printed in `Events` tab

#### Actual behavior
The application crashes

### LINKED ISSUE #17685: [Qt 5->6]: Fix various SB pages incompatibilities
## Description

SB itself:
- Dark mode is half broken (due to the Universal builtin style usage)

Some pages behave improperly in Qt 6:

- CreateCommunityPopup page hangs the SB
- LoginScreen, PasswordView (`import QtQuick.Extras 1.4`)
- ManageHiddenPanel looks differently:

Image

(The list is intended to be extended)

### PR DESCRIPTION
**Pull request by caybro**
### What does the PR do

See the individual commits

Fixes #17685
Fixes #17447

### Affected areas

Storybook

### Architecture compliance

- [x] I am familiar with the application architecture and agreed good practices.
My PR is consistent with this document: [Status Desktop Architecture Guide](https://github.com/status-im/status-desktop/blob/master/CONTRIBUTING.md)

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

image

Dark mode:

image

### CODE REVIEW

**Review by dlipicar — APPROVED** [review]

File: storybook/main.cpp [hunk 1]
```diff
@@ -56,6 +60,10 @@ int main(int argc, char *argv[])
 
     QQmlApplicationEngine engine;
 
+#if QT_VERSION > QT_VERSION_CHECK(6, 0, 0)
```
[the remark this answers is not in the document]
Comment (caybro) [reply storybook/main.cpp]: Fixed, thanks!

File: storybook/main.qml [hunk 2]
```diff
@@ -20,18 +20,16 @@ ApplicationWindow {
...
 
+    Universal.theme: darkModeCheckBox.checked ? Universal.Dark : Universal.Light
+
     onCurrentPageChanged: {
         testsReRunTimer.restart()
         settings.setValue("currentPage", currentPage)
     }
 
-    Component.onCompleted: currentPage = settings.value("currentPage")
+    Component.onCompleted: currentPage = settings.value("currentPage") ?? "Playground"
```
Comment (micieslak) [inline storybook/main.qml:32]: Plese move it directly to the property declaration to avoid warning like
```
status-desktop/storybook/pages/Page.qml: No such file or directory
```
```qml
property string currentPage: settings.value("currentPage") ?? "Playground"
```

File: storybook/pages/CommunitiesPortalLayoutPage.qml [hunk 3]
```diff
@@ -51,8 +51,8 @@ SplitView {
                     }
                 }
 
-                function navigateToCommunity() {
-                    logs.logEvent("CommunitiesStore::navigateToCommunity", ["communityId"], arguments)
```
Comment (micieslak) [inline storybook/pages/CommunitiesPortalLayoutPage.qml:55]: unfortunately it's not correct as it will print e.g.:
```
11:20:43: CommunitiesStore::navigateToCommunity: [communityId: "i", "d", "1"]
```
similarly is some other places

File: ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml [hunk 4]
```diff
@@ -286,7 +286,7 @@ QtObject {
         }
     }
 
-    readonly property Settings settings: Settings {
+    readonly property var settings: Settings {
```
Comment (micieslak) [inline ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml:289]: please add
```
/* https://bugreports.qt.io/browse/QTBUG-135039 */
```
as it maybe tempting for sb to set explicit type there :)

**Review by micieslak — COMMENTED** [review]
Nice! Just several minor comments.

File: storybook/pages/CommunitiesPortalLayoutPage.qml (hunk 3 above)
Comment (caybro) [reply storybook/pages/CommunitiesPortalLayoutPage.qml:55]: Hmm... I'll have a look

**Review by micieslak — APPROVED** [review]
